### ISSUE TITLE
CameraTarget: missing class?

### ISSUE THREAD

**Issue by stephane-lallee** [watson-developer-cloud/unity-sdk#1]
I'm giving a try to Watson and unity. I just cloned the git repo and imported that in a blank Unity project. The project is not compiling as there are several references to a missing class : `CameraTarget`
All of them are within the `WatsonCamera.cs` script.

EDIT: I commented the whole WatsonCamera class and I am able to proceed with the credential configuration, etc.

**Comment by rolyle** [comment]
Seems we published some in-progress changes to the develop branch, try switching to the master branch for now until we can resolve that issue.
 
                                                                        Regards,
                         
                        RICHARD O. LYLE                        Creative 3D Developer                                                                         
                                                                                                                                Phone: 1-512-968-1266                        E-mail: rolyle@us.ibm.com                        Watson CTO Labs Tour request form:: ibm.biz/watsonlabstourrequest                                                                        11501 Burnet Rd                        Austin, TX 78758-3400                        United States                        
 
 
----- Original message -----From: Stephane Lallee <notifications@github.com>To: watson-developer-cloud/unity-sdk <unity-sdk@noreply.github.com>Cc:Subject: [unity-sdk] CameraTarget: missing class? (#1)Date: Tue, Jan 12, 2016 11:59 PM 
I'm giving a try to Watson and unity I just cloned the git repo and imported that in a blank Unity project The project is not compiling as there are several references to a missing class : CameraTargetAll of them are within the WatsonCameracs script
—Reply to this email directly or view it on GitHub.

**Comment by ereneld** [comment]
CameraTarget has been pushed, it is ok now. Thanks for feedback.
