### ISSUE TITLE
Update the user-agent to include the sdk version

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/unity-sdk#10]
All the requests should include a `User-Agent` header with the following format:

```
watson-developer-cloud-unity-sdk-<version-number>
```
Where `<version-number>` follows semantic versioning like `0.2.0`, `0.5.1`, etc.

**Comment by germanattanasio** [comment]
We will use this to measure the usage of our sdks

**Comment by germanattanasio** [comment]
Looks like `ThirdParty/WebSocketSharp/HttpRequest.cs` is defining it's own `User-Agent`.

**Comment by mediumTaj** [comment]
added User-Agent to RESTConnector and WSConnector
