### ISSUE TITLE
Readme.md..

### ISSUE THREAD

**Issue by rolyle** [watson-developer-cloud/unity-sdk#102]
The readme.md has the following comment which I think is incorrect:

Change the build settings in Unity (File > Build Settings) to PC, Mac & Linux Standalone. Click PC, Mac & Linux Standalone and click the Switch Platform button.

So far as I know, this SDK should work for Android and iOS platforms as well. I don't know why this comment was added to the readme.md.

**Comment by mediumTaj** [comment]
There was a case where someone reported errors when installing the SDK. It turned out to be they had build settings set to Web Player. 

I can add Android and iOS to this or once I have some time to download modules and test for building other platforms, add something like "anything but web player" to the readme.

**Comment by rolyle** [comment]
Web player is not support, i think it's sufficient to just state any platform but web player.
 
----- Original message -----From: Ajiemar Santiago <notifications@github.com>To: watson-developer-cloud/unity-sdk <unity-sdk@noreply.github.com>Cc: Richard O Lyle/Austin/IBM@IBMUS, Author <author@noreply.github.com>Subject: Re: [watson-developer-cloud/unity-sdk] Readme.md.. (#102)Date: Sun, Jul 10, 2016 10:50 PM 
There was a case where someone reported errors when installing the SDK. It turned out to be they had build settings set to Web Player.
I can add Android and iOS to this or once I have some time to download modules and test for building other platforms, add something like "anything but web player" to the readme.
