### ISSUE TITLE
Add travis to build, test, and document the repository

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/unity-sdk#11]
See https://jonathan.porta.codes/2015/04/17/automatically-build-your-unity3d-project-in-the-cloud-using-travisci-for-free/

**Comment by germanattanasio** [comment]
@mediumTaj something you can do is to fork this repo and work on a fork. That will help you with Travis because you need to commit changes to start a build and I learned that at the end you end up creating a lot of commits before you get travis to work.

**Comment by germanattanasio** [comment]
and feel free to share your progress here

**Comment by mediumTaj** [comment]
Good call on the fork. I'll test that this afternoon.

From the link above, we will only be able to build using a repo with an actual Unity project. The sdk currently is set up as a plugin and doesn't have an actual Unity project (The developer integrates the sdk into their project). 

I set up a project to test travis integration here: https://github.com/mediumTaj/watson-unity-sdk-testbed

I have travis currently downloading and installing Unity on the build machine and building the actual project on push to origin. I don't have the actual builds uploading anywhere yet.

This morning I am adding script to execute unit tests along with building.

After that I'll fork the unity-sdk repo and see if I can get any worthwhile (possibly unit tests) from travis in the actual sdk repo. I don't think we will be able to actually build a project though. 

Some caveats here though:
1) At this point we can only test builds with a repo with Unity project files. At this point I structured it as a project with the Unity SDK as a submodule. Eventually I'd like to move the widgets and examples on this project level and keep core functionality in the SDK along with unit tests.

2) The build process requires a download of Unity for each build. There are only mac and windows versions of Unity - no linux. We spin up a mac vm by setting the programming language to objective-c and the build scripts are currently mac specific.

3) C# support in travis is experimental and community supported. setting csharp as the language spins up linux vm.

Let me know if anything sounds off to you or if I'm missing some functionality here.

**Comment by mediumTaj** [comment]
@germanattanasio Implementing unit tests - how do we handle credentials for services?

**Comment by mediumTaj** [comment]
Sanjay here in the lab says Unity is going to block us if we keep doing direct download from their site and suggests we host the package somewhere.... I know you mentioned putting the installer in the repo but it's pretty big. what do you think @germanattanasio ?

**Comment by germanattanasio** [comment]
we can probably use object store from SoftLayer. Can you estimate the file size ?

**Comment by germanattanasio** [comment]
we can probably use object store from SoftLayer. Can you estimate the file size ?

**Comment by germanattanasio** [comment]
You should also check how other people are doing the integration. See https://github.com/search?utf8=%E2%9C%93&q=unity+travis

**Comment by mediumTaj** [comment]
Unity mac app: 409 MB
Windows build module: 178 MB
Mac build module: 97.1 MB
Linux build module: 131 MB
Total: 815 MB

**Comment by germanattanasio** [comment]
We should host the unity mac and the mac build module for now
