### ISSUE TITLE
Add Text to Speech SSML support examples to the ReadMe

### ISSUE THREAD

**Issue by deepakakkil** [watson-developer-cloud/unity-sdk#118]
Does the TTS API support SSML (add pause, control the rate of speech etc). 
Add examples and  Update the ReadMe.md with details on SSML support or lack of it.

**Comment by mediumTaj** [comment]
The speech to Text to Speech service supports SSML as described here

`http://www.ibm.com/watson/developercloud/doc/text-to-speech/SSML.shtml`

I will add some documentation to the read me.

**Comment by deepakakkil** [comment]
Thanks. While you are at it, could you give me a quick heads up on how to do it?

I tried the following:

```
string m_TestString = "<speak version=\"1.0\"><prosody rate=\"20\"> Hello </prosody></speak>";
m_TextToSpeech.Voice = VoiceType.en_US_Michael;
m_TextToSpeech.ToSpeech(m_TestString, HandleToSpeechCallback);
```

This seems to work fine, as in I get the audio clip, however the SSML seems to make no difference. (in this case, it should make the speech rate noticeably slower.  The same text seems to work in the SSML demo page located here : [https://text-to-speech-demo.mybluemix.net/](url)

**Comment by mediumTaj** [comment]
Apologies... I see the issue now. Go to 'Scripts/Services/TextToSpeech/TextToSpeech.cs' and delete line 97 'text = Utility.RemoveTags(text);'. That should keep your tags intact. Also the expressions only work with the Allison voice. The line deletion will be added next push.

**Comment by mediumTaj** [comment]
[ ] Remove tag stripping in ToSpeech
[ ] Update ReadMe to show SSML documentation
