### ISSUE TITLE
API Reference does not work in Unity 5.3.2f1

### ISSUE THREAD

**Issue by nsbingham** [watson-developer-cloud/unity-sdk#13]
Using the nav option `Watson > API Reference` nothing happens. Menu item appears to point to `WatsonUnitySDK.chm` which I cannot find.

**Comment by mediumTaj** [comment]
Hmm, we have the api reference in compiled html format. For a mac, at least, this requires a chm reader. Without a chm reader nothing seems to happen when we click API Reference. Should the reference be in a different format? Should we include instructions on getting a chm reader in the read me? What do you think?

**Comment by germanattanasio** [comment]
Probably is a good idea to add instructions in the readme. Something short like

## Documentation
To read the documentation you need to have a chm reader installed.
