### ISSUE TITLE
[retrieve-and-rank] revise data models, test and examples

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#174]
Title, body, author and bibliography changed from array to a single string. 

```
                if (!string.IsNullOrEmpty(doc.title))
                {
                  Log.Debug("ExampleRetrieveAndRank", "Search | title: {0}", doc.title);
                }
                else
                {
                  Log.Debug("ExampleRetrieveAndRank", "Search | title is null");
                }

                if (!string.IsNullOrEmpty(doc.author))
                {
                  Log.Debug("ExampleRetrieveAndRank", "Search | author: {0}", doc.author);
                }
                else
                {
                  Log.Debug("ExampleRetrieveAndRank", "Search | Authors is null");
                }

                if (!string.IsNullOrEmpty(doc.body))
                {
                  Log.Debug("ExampleRetrieveAndRank", "Search | body: {0}.", doc.body);
                }
                else
                {
                  Log.Debug("ExampleRetrieveAndRank", "Search | Body is null");
                }

                if (!string.IsNullOrEmpty(doc.bibliography))
                {
                  Log.Debug("ExampleRetrieveAndRank", "Search | bibliography: {0}.", doc.bibliography);
                }
                else
                {
                  Log.Debug("ExampleRetrieveAndRank", "Search | Bibliography is null");
                }
```

**Comment by mediumTaj** [comment]
This isn't true - The response object is dependent on the request. As far as I can tell it depends on the schema.xml in the training data. The `cranfield_solr_config` training data lists the following in the schema

```
<field name="id" type="string" indexed="true" stored="true" required="true" multiValued="false" /> 
   <field name="title" type="watson_text_en" indexed="true" stored="true" required="false" multiValued="true" />
   <field name="author" type="watson_text_en" indexed="true" stored="true" required="false" multiValued="true" />
   <field name="bibliography" type="watson_text_en" indexed="true" stored="true" required="false" multiValued="true" />
   <field name="body" type="watson_text_en" indexed="true" stored="true" required="false" multiValued="true" />
```

This is why we have arrays for title, author, bibliography and body in the data model (`multiValued = "true"`)

The user will have to change the data model in the service in to compensate for their training schema.

**Comment by mediumTaj** [comment]
According to German we shouldnt be able to search or index within the Unity SDK - only create clusters, rankers, etc. We need to remove functionality for searching and indexing and find a solr library that will work with Unity.

**Comment by Dwitee** [comment]
Hi Ajiemar,

Using the web tool from bluemix I created a cluster , collection and upload the content and then question. I check in the tool asked the questions and give star rating to the answers. It worked fine.

Now I am making use of the unity SDK to send the query and get the response.

so I used the ExampleRetrieveAndRank.cs and used the following with correct clusterID , collection name and query.
  //  Standard Search
        Log.Debug("ExampleRetrieveAndRank", "Attempting to search!");
        string[] fl ={ "title", "id", "body", "author", "bibliography" };  
        if (!m_RetrieveAndRank.Search(OnSearch, testClusterID, testCollectionName, testQuery, fl))
            Log.Debug("ExampleRetrieveAndRank", "Failed to search!");



but in the function    OnSearch(SearchResponse resp, string data) I  getting null in body, title ,and biibiliography but I am getting populated IDs for each of the Docs .

can you please suggest me how to get the correct response  with Body.

**Comment by mediumTaj** [comment]
Hi Dwitee,
The data model for R&R changes based on training. Do you have the returned json output from the request? Set a breakpoint in `OnSearchResponse`. You will have to change the DataModel.cs file based on the returned data (Doc class in DataModel.cs).

**Comment by sdalmia** [comment]
Hi medium,

I am having the same problem as Dwitee. I have a returned json output from the request which also contains title and body similar to the example. On your suggestion in the above post i also changed my DataModel.cs file's Doc class by commenting out author and bibliography. I am not sure if what I did was what you suggested. Could please elaborate a little more on what changes I would have to make to the Doc class.

Best,
Sid

**Comment by mediumTaj** [comment]
hi @sdalmia 
So the DataModel.cs must be revised since the data model is based on how you trained the instance of R&R. You must revise the `Response` class to follow the response you get from the service. Follow the pattern set up in the DataModel file ([fsObject]) to ensure the data is properly deserialized. If you can provide the json data that is returned from the service I can help more.
