### ISSUE TITLE
[conversation] README.md file example text is not up to date

### ISSUE THREAD

**Issue by Mukarillo** [watson-developer-cloud/unity-sdk#175]
In the README file there an example of coding that is not representing the latest version:

```
void OnMessage (DataModels.MessageResponse resp)
{
    foreach(DataModels.MessageIntent mi in resp.intents)
        Debug.Log("intent: " + mi.intent + ", confidence: " + mi.confidence);

    Debug.Log("response: " + resp.output.text);
}
```

While it should be:
```
void OnMessage (MessageResponse resp)
{
    foreach(Intent mi in resp.intents)
        Debug.Log("intent: " + mi.intent + ", confidence: " + mi.confidence);

    Debug.Log("response: " + resp.output.text);
}
```

**Comment by mediumTaj** [comment]
Hi Murrilo, Would you like to fork the repo or create a branch, make the change and create a pull request? The Unity SDK is open source and we would love to have more contributors! Especially talented Unity developers.

**Comment by mediumTaj** [comment]
I made these changes - waiting for CI in PR
