### ISSUE TITLE
Cannot find SpechResultList library

### ISSUE THREAD

**Issue by doanhtai00** [watson-developer-cloud/unity-sdk#187]
Hi.
I cannot find SpeechResultList import on file for function SpeechToText.
Please help me.
Thanks.

**Comment by Miojo** [comment]
change it to SpeechRecognitionEvent instead.
If you are trying to make the speech to texto tutorial work, also change the variables to lower case:

    void HandleOnRecognize(SpeechRecognitionEvent result)
       
    {
        if (result != null && result.results.Length > 0)
        {
            foreach (var res in result.results)
            {
                foreach (var alt in res.alternatives)
                {
                    string text = alt.transcript;
                    Debug.Log(string.Format("{0} ({1}, {2:0.00})\n", text, res.final ? "Final" : "Interim", alt.confidence));
                }
            }
        }
    }

**Comment by mediumTaj** [comment]
@doanhtai00 Were you able to resolve the issue?

**Comment by Joshua-Carr** [comment]
The above fix resolved the same problems I was facing. 

For others: the examples/scripts/ folders show the SpeechRecognitionEvent and not SpeechResultList as found in the readme

**Comment by mediumTaj** [comment]
Thanks, tracking here

https://github.com/watson-developer-cloud/unity-sdk/issues/216

**Comment by daphna-kaplan** [comment]
hey I am having similar issue
the SpeechResultList and the SpeechResult are not recognized and I dont know how to replace them
 the function is :
        protected void OnSpeechToTextResult(SpeechResultList results)
        {
            if (results.HasResult())
            {
                SpeechResult watsonResult = results.Results[0];
                var textResult = m_WatsonSpeechToTextComponent.CreateSpeechToTextResult(watsonResult);
                if (m_OnTextResult != null)
                {
                    m_OnTextResult(textResult);
                }
                m_LastResult = textResult;
            }
        }
