### ISSUE TITLE
Credential Parsing

### ISSUE THREAD

**Issue by stephane-lallee** [watson-developer-cloud/unity-sdk#2]
There seems to be a problem when parsing the credentials.
I'm pasting in something like :
```
{
  "credentials": {
    "url": "https://stream.watsonplatform.net/speech-to-text-beta/api",
    "username": "zzzzz-6666-zzzz-zzzz-zzzz",
    "password": "xxxxxxx"
  }
}
```
But when clicking "Apply Credentials" I just get an error with a copy of the credentials.

**Comment by nfriedly** [comment]
Try removing the `-beta` from the url.

**Comment by rolyle** [comment]
Hi, You signed up for the beta speech to text, if you sign up for the non-beta speech to text and use those credentials it will work. We use the URL to figure out which service credentials your applying, currently we're not looking for "speech-to-text-beta".
 
 
                                                                        Regards,
                         
                        RICHARD O. LYLE                        Creative 3D Developer                                                                         
                                                                                                                                Phone: 1-512-968-1266                        E-mail: rolyle@us.ibm.com                        Watson CTO Labs Tour request form:: ibm.biz/watsonlabstourrequest                                                                        11501 Burnet Rd                        Austin, TX 78758-3400                        United States                        
 
 
----- Original message -----From: Stephane Lallee <notifications@github.com>To: watson-developer-cloud/unity-sdk <unity-sdk@noreply.github.com>Cc:Subject: [unity-sdk] Credential Parsing (#2)Date: Wed, Jan 13, 2016 12:01 AM 
There seems to be a problem when parsing the credentialsI'm pasting in something like :{"credentials": {"url": "https://streamwatsonplatformnet/speech-to-text-beta/api","username": "zzzzz-6666-zzzz-zzzz-zzzz","password": "xxxxxxx"}}
But when clicking "Apply Credentials" I just get an error with a copy of the credentials
—Reply to this email directly or view it on GitHub.

**Comment by rolyle** [comment]
That wouldn't work, because she signed up for the beta service.. changing the URL, will make it go to the correct URL, but the credentials won't work there.
 
 
                                                                        Regards,
                         
                        RICHARD O. LYLE                        Creative 3D Developer                                                                         
                                                                                                                                Phone: 1-512-968-1266                        E-mail: rolyle@us.ibm.com                        Watson CTO Labs Tour request form:: ibm.biz/watsonlabstourrequest                                                                        11501 Burnet Rd                        Austin, TX 78758-3400                        United States                        
 
 
----- Original message -----From: Nathan Friedly <notifications@github.com>To: watson-developer-cloud/unity-sdk <unity-sdk@noreply.github.com>Cc:Subject: Re: [unity-sdk] Credential Parsing (#2)Date: Wed, Jan 13, 2016 9:40 AM 
Try removing the -beta from the url.
—Reply to this email directly or view it on GitHub.

**Comment by stephane-lallee** [comment]
Working indeed. So I assume the SDK is restricted so far to the services listed (STT,TTS, Translation, Dialog, and Natural Language Classifier). Is it planned to extend it to the visual recognition services (i.e. Alchemy API)?

In any case, thank you for the quick answer.

**Comment by rolyle** [comment]
The tentative plan is to keep doing additional services, Visual Recognition is next on our list of services to implement. This is not official yet.
 
 
----- Original message -----From: Stephane Lallee <notifications@github.com>To: watson-developer-cloud/unity-sdk <unity-sdk@noreply.github.com>Cc: Richard O Lyle/Austin/IBM@IBMUSSubject: Re: [unity-sdk] Credential Parsing (#2)Date: Wed, Jan 13, 2016 6:27 PM 
Working indeed. So I assume the SDK is restricted so far to the services listed (STT,TTS, Translation, Dialog, and Natural Language Classifier). Is it planned to extend it to the visual recognition services (i.e. Alchemy API)?
In any case, thank you for the quick answer.
