### ISSUE TITLE
Update Alchemy Key

### ISSUE THREAD

**Issue by jzhang300** [watson-developer-cloud/unity-sdk#20]
We're making sure any SDK or demo that uses Alchemy should be using the same super key.

PM me for the Alchemy key you should be using.

**Comment by mediumTaj** [comment]
We aren't saving any credentials in the Unity SDK. We store our Config.json file in the project's StreamingAssets directory outside of the SDK. Do the rest of the SDKs provide credentials for end users to test drive?

**Comment by germanattanasio** [comment]
This is for the integration tests

**Comment by mediumTaj** [comment]
updated
