### ISSUE TITLE
[unity-sdk] Travis OSX alternative

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#203]
Travis uses Linux and OSX for their build machines. To build and test the Unity SDK we need to install Unity. There are currently OSX and Windows versions of the Unity editor. Currently open source Travis OSX builds are taking several hours. They only have 128 build machines and often have a backlog of over 1000 continuous integration jobs in the queue. 

There is an experimental Unity 5.1.0 editor for Linux [https://blogs.unity3d.com/2015/08/26/unity-comes-to-linux-experimental-build-now-available/] but we are currently on editor v5.5.0 and a few dependencies are higher than 5.1. 

Windows builds through AppVeyor may be an option and may allow us to run better testing for the Unity SDK in the Windows environment.

**Comment by germanattanasio** [comment]
https://circleci.com/

**Comment by mediumTaj** [comment]
Currently we are using Travis for continuous integration. Unity does not have a production Linux version and Travis only supports OSX and Linux so we are forced to spin up OSX VMs and download Unity to do CI. Unfortunately public Travis only has a few OSX VMs available and backlog jobs for OSX often are in the hundreds. CI jobs often sit in the queue for several hours before running.

See [Backlog macOS Builds for Open Source projects](https://www.traviscistatus.com/)

We need to investigate transitioning from Travis to AppVeyor which uses Windows build machines. Installing Unity is the hacky step here. We either need to install via cmd or somehow have Unity dll files hosted somewhere outside of the repo for us to download in the install phase. I didn't think installing via cmd was possible without an msi since Unity uses a download assistant but it looks like legacy versions of Unity were able to [install](https://docs.unity3d.com/500/Documentation/Manual/InstallingUnity.html) this way. We need to see if this works with the latest version Unity.

**Comment by mediumTaj** [comment]
The suggested command seems to work in cmd except for the target directory. 

```
UnityDownloadAssistant-2017.2.0f3.exe /S /D="C:\Program Files\Unity 2017.2"
```

This takes at least 20 minutes to download and cannot be cached since the download is happening through the download assistant. Need to investigate if we can download components separately like we do in the Travis build.
