### ISSUE TITLE
[speech-to-text] error with sample scene

### ISSUE THREAD

**Issue by aantn** [watson-developer-cloud/unity-sdk#208]
Hi, I'm encountering some errors with the scene ServiceExamples in Unity 5.5.0f3. See attached.

[errors.txt](https://github.com/watson-developer-cloud/unity-sdk/files/743327/errors.txt)

**Comment by mediumTaj** [comment]
Hi,
It looks like the WorkspaceID might be incorrect. Can you ensure the WorkspaceID is available in your service instance.

```
A workspace should be created using Conversation tooling and a variable `ConversationV1_ID` should be set in the Config Editor with the Workspace ID (In the Config Editor, click Advanced Mode and click Add Variable). This is required for the service status check in the Config Editor.
```

**Comment by mediumTaj** [comment]
@aantn Were you able to resolve the issue?

**Comment by aantn** [comment]
I haven't had a chance to check yet. I'll let you know next week.
