### ISSUE TITLE
[documentation] "Developing a basic application in one minute" not working

### ISSUE THREAD

**Issue by superquest** [watson-developer-cloud/unity-sdk#210]
I'm trying to run the [Developing a basic application in one minute](https://github.com/watson-developer-cloud/unity-sdk#developing-a-basic-application-in-one-minute) demo.

### Steps to Reproduce
* Install SDK in `Assets` and rename folder to `Watson`.
* Upload the Speech-To-Text & Natural Language Classifier API config files.
* Follow steps 1, 2 & 3 in [the directsions](https://github.com/watson-developer-cloud/unity-sdk#developing-a-basic-application-in-one-minute) exactly.
* Step 4 is unclear to me. I couldn't find the "Natural Language Classifier Editor" that it mentions. I think this documentation could be improved.
![image](https://cloud.githubusercontent.com/assets/4335621/22739036/d8843700-ee44-11e6-8611-ee201617435f.png)
* Run the application

### Expected behavior
I would be able to record my voice and something interesting would happen! Or at least, there would be an error in the console — but it's empty.

png)

### Actual behavior
The UI is frozen with this image:
![image](https://cloud.githubusercontent.com/assets/4335621/22738945/97a51d62-ee44-11e6-904a-a33ba5ba9858.png)

### Unity SDK version
SDK v0.13.0 
Unity 5.5.1f1
OSX 10.11.6.

### Other

The directions "Ensure that you prepare the test data before you complete the the following steps". I have no idea what is meant by this. Perhaps this is also part of the problem.

**Comment by mediumTaj** [comment]
The Natural Language Classifier editor is found under the `Watson` menu. Watson -> Natural Language Classifier Editor. I will update the documentation. Let me know if that was the issue.

**Comment by superquest** [comment]
I was able to the Natural Language Classifier Editor, but I still can't get the application to run.

The documentation is still pretty confusing. Here are some details:

> "expand the classes, and determine which questions about the weather to ask to test the classifier"

Not sure whether I'm actually required to do anything here. Its seems that there are already 2 preconfigured "classes", each with many example phrases. It seems like it's already configured?

<img width="865" alt="screen shot 2017-02-09 at 12 46 10 pm" src="https://cloud.githubusercontent.com/assets/4335621/22769929/2ec3f1b4-eec7-11e6-80fb-471a8a79c44e.png">

The documentation doesn't mention anything about the "train" button that is visible in the previous screenshot. I'm assuming this needs to be clicked before the NLC service will work?

If I do click that "train" button and wait until the "instance" has the "Status: Available" attribute and then run, I get an error:

> ArgumentException: GUILayout: Mismatched LayoutGroup.Repaint
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at /Users/builduser/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:268)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7153)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7133)
IBM.Watson.DeveloperCloud.Editor.NaturalLanguageClassifierEditor.OnGUI () (at Assets/Watson/Scripts/Editor/NaturalLanguageClassifierEditor.cs:267)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

So at least I have an error now :)

Any idea what might be going wrong here?

**Comment by mediumTaj** [comment]
The Natural Language Classifier Editor edits a json file on your local filesystem. You define intents (classes) and phrases to trigger the intent. In this case the two classes are `temperature` and `conditions`. 

This json file is used to train your particular Natural Classifier service instance. You simply need to click the `train` button and it will create a classifier associated with your service instance. You must wait for the status of the classifier to change from `training` to `available` to be able to use it. 

After training is complete you need to speak into the microphone ("What's the weather like?"). The `MicrophoneWidget` will convert microphone audio into `AudioData` and pass it to the `SpeechToTextWidget`. The `SpeechToTextWidget` then passes the result text to the `NaturalLanguageClassifierWidget`. The `NaturalLanguageClassifierWidget` passes the returned intent to the `ClassDisplayWIdget` displaying the intent and the confidence.

Using this you would be able to create an application that will execute logic based on the received intent.

**Comment by mediumTaj** [comment]
@superquest Is it working?

**Comment by superquest** [comment]
No, it is not.

**Comment by mediumTaj** [comment]
Have you asked the application a question? Say "is it raining today?"

**Comment by superquest** [comment]
Yes I did, but nothing happened.

In an hour I will try again and update you.

On Wed, Feb 15, 2017 at 10:12 AM, Ajiemar Santiago <notifications@github.com

**Comment by mediumTaj** [comment]
Any update on this? I'd like to help find the issue if possible.

**Comment by superquest** [comment]
I tried it again from scratch, and I'm getting exactly the same error I described 9 days ago.

> ArgumentException: GUILayout: Mismatched LayoutGroup.Repaint
> UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at /Users/builduser/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:268)
> UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7153)
> UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options) (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7133)
> IBM.Watson.DeveloperCloud.Editor.NaturalLanguageClassifierEditor.OnGUI () (at Assets/Watson/Scripts/Editor/NaturalLanguageClassifierEditor.cs:267)
> System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by mediumTaj** [comment]
That error is just a front end error coming from the NLC editor window and shouldn't stop the service from working. Close the Natural Language Classifier editor window after you train your instance. Be sure your classifier instance is "Available" and when you click play check the connections of the microphone widget, speech to text widget, natural language classifier widget and class display widget are working by looking at each game object's properties.
