### ISSUE TITLE
[speech-to-text] Watson Ambient Noise & Children's Voice's

### ISSUE THREAD

**Issue by subvertio** [watson-developer-cloud/unity-sdk#218]
I'm not sure if this is a 'feature request' or  bug, but Speech to Text has a very hard time with ambient noise and Children's voices.

Any ambient noise gives erratic results, and voices of young people results are very unreliable.

**Comment by mediumTaj** [comment]
There are different ways to handle ambient noise, but all of these should be implemented on the application level, not on the SDK level. 

You can add [audio filters](https://docs.unity3d.com/Manual/class-AudioEffect.html) to the audio or use a microphone where you can control the gain.

However, if you come up with a cross-platform Unity-Based solution, we do accept pull requests!

**Comment by mediumTaj** [comment]
As far as children's voices are concerned, Speech to Text can be customized to specific language domains (healthcare, law, etc). Words and their pronunciations can also be added to this customization. Look [here](https://www.ibm.com/watson/developercloud/doc/speech-to-text/custom.shtml) and search "Using the sounds_like field". 

In the Unity SDK you can add customizations by writing [C# script](https://github.com/watson-developer-cloud/unity-sdk/blob/develop/Examples/ServiceExamples/Scripts/ExampleSpeechToText.cs) or you can use another SDK such as the Python SDK or a REST client such as PostMan to train.

**Comment by mediumTaj** [comment]
Trying to strikethrough the above comment about the "sounds_like" field. This note came from the Speech to Text division:

>Current STT customization does language model adaptation.  For children voices, the more critical adaptation is on the acoustic space, as opposed to the language domain.  So it might help a bit (if what the child says is out of domain, e.g. they speak in less grammatical fashion).  We are planning to have acoustic model customization later this year which will be more helpful for children voices.
