### ISSUE TITLE
[speech to text] OverFlowException error

### ISSUE THREAD

**Issue by jeffreythegreat7** [watson-developer-cloud/unity-sdk#228]
I cant fix this error, does somebody help me regarding on this error? 

OverFlowException: Value is greater than Char.Max Value or less than Char.Min Value
System.Convert.ToChar (Int 32 Value) (at/Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Convert.cs:624) 

Thank you for your kindness :) Badly need for my thesis :(

**Comment by mediumTaj** [comment]
Can you provide more details on this? Sample code, full stack trace, etc? Is speech to text working for you in the example file (examplestreaming scene)?

**Comment by mediumTaj** [comment]
@jeffreythegreat7 made contact over email. This is for hololens development. We are not currently supporting hololens in the Unity SDK. @eusebiu has a fork of the SDK with updated plugins for errors he was running into when developing for Hololens.

https://github.com/eusebiu/unity-sdk/tree/WSA_Support

Also you can try the .NET Standard SDK

https://github.com/watson-developer-cloud/dotnet-standard-sdk
