### ISSUE TITLE
[Text-to-Speech] CORS (Cross-Origin Resourse Sharing) in WebGL not working

### ISSUE THREAD

**Issue by bhenry6** [watson-developer-cloud/unity-sdk#231]
I am currently having an issue using Watson Text-to-Speech in WebGL where I receive a Cross-Origin Blocked Message when trying to retrieve audio data from stream.watsonplatform. (See Image Attached Below)

<img width="1438" alt="screen shot 2017-04-17 at 12 40 44 pm" src="https://cloud.githubusercontent.com/assets/4574099/25097824/bb2cfbfe-236b-11e7-81f4-9536c6ae9fb6.png">

I know at one time CORS was not enabled for a lot of Watson Services and in the past I used a Proxy to work around it when using WebGL.

On the [developerWorks Forum](https://developer.ibm.com/answers/questions/260008/is-there-a-plan-for-the-watson-services-gateway-to.html), it was said that CORS was now enabled on Text-to-Speech but when using it through the SDK I still get the above error.

I was thinking it was because the allowed headers that are allowed now are "**X-Watson-Authorization-Token**" and "**X-Watson-UserInfo**" not "**authorization**" and "**user-info**" and I changed that in the RESTConnecter Script but I still receive the CORS warning. I also experimented with quite a few other tweaks but no solution as of yet.

I'm not sure what the issue is since CORS should be enabled on the Watson Server side. I'd really like to use this Watson SDK but it looks like I may have to create my own service using a proxy again. Would love to know if I am doing something wrong.

Thanks!

**Comment by mediumTaj** [comment]
The Unity SDK does not support publishing to WebGL. If you can get it working, we will happily accept pull requests! We are creating a dotnet standard sdk that will eventually contain the Unity SDK. 

https://github.com/watson-developer-cloud/dotnet-standard-sdk

**Comment by bhenry6** [comment]
Ahh! Thanks! I was wondering if maybe I was doing something wrong in general.

I will continue tooling around with the current code and see if I can get something working with WebGL using your SDK framework.

And cool, I will check out what you guys are doing with donnet. Also, I work for IBM so if we need to connect internally, that is possible as well.

As an aside, the current Documentation on the Github page says it build to all platforms except Web Player. It may be good to add WebGL to that statement as well.

**Comment by mediumTaj** [comment]
No worries, Yeah it's more about the 3rd party plugins we are using than anything. I don't think Web Sockets will work in WebGL but if you can get it to work let me know. Yeah we have to update that Readme as well...

**Comment by ShahSoft** [comment]
@bhenry6 Did you made any progress with this? @mediumTaj Any plans to Add WebGL support in near future? Thanks.

**Comment by mediumTaj** [comment]
There currently aren’t any plans to get this to work in WebGL. We do accept pull requests if you can get it working though
