### ISSUE TITLE
Release Watson Unity SDK to the Unity Asset Store

### ISSUE THREAD

**Issue by rlyle** [watson-developer-cloud/unity-sdk#237]
This entire project should be packaged and made available on the Unity asset store under the "Services" section IMHO..

- [x] Support for authentication via token
- [x] Support multiple service instances
- [x] Support credentials through `VCAP_SERVICES`

**Comment by mediumTaj** [comment]
I have a meeting about that today, actually :)

**Comment by mediumTaj** [comment]
Finish all changes to the asset by Nov 17 for 12/8 launch

**Comment by mediumTaj** [comment]
@rlyle https://assetstore.unity.com/packages/tools/ai/ibm-watson-unity-sdk-108831
🎮
