### ISSUE TITLE
README instructions for Conversation still refer to MessageResponse instead of object

### ISSUE THREAD

**Issue by scottdangelo** [watson-developer-cloud/unity-sdk#241]
The README for [Conversation](https://github.com/watson-developer-cloud/unity-sdk#conversation) still refers to the deprecated MessageResponse object. This has been changed in the latest Conversation API to a generic object, and using (MessageResponse) resp.intent (for example) will not work.

**Comment by mediumTaj** [comment]
Fixed in https://github.com/watson-developer-cloud/unity-sdk/pull/244
