### ISSUE TITLE
Unity package

### ISSUE THREAD

**Issue by rohitdesaidev** [watson-developer-cloud/unity-sdk#251]
Can I get unity package for this it will be a great help for all.
Because It's getting hard to work on this without a package. Or else can you please guide me how can I import this project to unity.
I just copy pasted the folder but watson option in menu doesn't show full options for me.

**Comment by mediumTaj** [comment]
You should download this package into the `Assets` directory of your project. Rename the package to `Watson` since `unity-sdk` is not very descriptive.
