### ISSUE TITLE
IBM Unity SDK Demo Scene TestSpeechToText not working

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/unity-sdk#252]
> Question by Muhammad Faizan Khan  (1) | Sep 09 at 02:58 AM
> I have downloaded Unity SDK of IBM Watson but the problem (necessary after configuration), its TestSpeechToText scene still not working. No Log, No output while I am continuously giving voice input. What else settings are required to run the scene. I also inspect its different script that is attached to game objects some of them have not assigned UI game-object.

source: https://developer.ibm.com/answers/questions/399772/demo-scene-testspeechtotext-not-working.html

**Comment by ghettokon** [comment]
I tried the example streaming, the speech to text in there works pretty well. Make sure you have all the right credentials.

**Comment by mediumTaj** [comment]
Addressed in developerWorks - `TestSpeechToText.unity` has been deprecated and removed. Use `ExampleStreaming` instead.
