### ISSUE TITLE
[Conversation]When passing an empty string as message content, an "Argument Null" exception is thrown.

### ISSUE THREAD

**Issue by sdhubbardJF** [watson-developer-cloud/unity-sdk#254]
When calling Conversation.Message, when passing an empty string as the value for the input argument, an ArgumentNullException is thrown. This prevents the client using the Watson Unity SDK from getting the start node's message from a Conversation workspace. On line 121 in Conversation.cs, there's a call to "string.IsNullOrEmpty". Changing this to a straight null check against the input variable allows an empty string to be sent to the conversation service, which in turn response with its Start node content.

**Comment by mediumTaj** [comment]
https://github.com/watson-developer-cloud/unity-sdk/pull/264
