### ISSUE TITLE
Generate audio for Speech to Text keep alive

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#258]
We need to send audio to the Speech to Text service to keep the collection alive. Currently we rely on a small audio file in the resources directory. We need to remove this dependency and generate a small audio clip to send to the service to keep the connection alive.

**Comment by mediumTaj** [comment]
From https://github.com/watson-developer-cloud/unity-sdk/issues/271

>If the Websocket "Keep Alive" is still needed, it must match recording format of Microphone to avoid confusing the Watson STT service. Currently, my Microphone is capturing at a sample rate of 48kHz in Stereo. The Unity Watson SDK is trying to use a "highHat" as a keepalive but this is a WAV format so presumably recorded at a sample rate of 48 kHz. Ideally, I'm going to implement a downsampling routine so that I can downsample my microphone to match Watson's "Wideband" sampling rate of 16 kHz, and "Narrowband" or any other Watson-supported sampling rates must also be handled by the Watson Websocket "Keep Alive" service.

**Comment by RMichaelPickering** [comment]
@mediumTaj It is worth further testing to determine if the keep alive is even still needed. I'd think that it would be much better to properly implement silence detection and use it combined with setting Websocket timeout to -1 (never timeout). This should allow us to simply open and close the audio stream as non-silent passages are detected. We just need to ensure that the Websocket doesn't get closed by Watson after some arbitrary (and undocumented) length of time during which no audio is streamed at all.
Of course this does assume that we're able to get audio streaming working properly!

**Comment by RMichaelPickering** [comment]
I still vote for properly fixing the STT websocket connection!

**Comment by mamoonraja** [comment]
Still active.
