### ISSUE TITLE
[speech-to-text] Custom corpus adding unexpected words

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#261]
The `AddCustomCorpus` method is adding some unexpected words. Running the speech-to-text unit test, we see the following result:

`[10/16/2017 20:08:30][ExampleSpeechToText][DEBUG] Speech to Text - Get custom words response: {"words":[{"display_as":"OOV","sounds_like":["O. O. V.","OOV"],"count":2,"source":["unity-corpus"],"word":"OOV"},{"display_as":"cshqmgjm","sounds_like":["cshqmgjm"],"count":2,"source":["unity-corpus"],"word":"cshqmgjm"},{"display_as":"epijbhx","sounds_like":["epijbhx"],"count":2,"source":["unity-corpus"],"word":"epijbhx"},{"display_as":"trainingdata.txt","sounds_like":["trainingdata txt"],"count":1,"source":["unity-corpus"],"word":"trainingdata.txt"},{"display_as":"wunfvyoqxso","sounds_like":["wunfvyoqxso"],"count":2,"source":["unity-corpus"],"word":"wunfvyoqxso"}]}`

Only the first word (OOV) actually appears in the source text.

Tested with release 1.0.0 in Unity 2017.1.1f1

**Comment by mediumTaj** [comment]
Asking the service team what might be going on here. I get the same results - strange that it's picking up the filename.

**Comment by mediumTaj** [comment]
I grabbed a new corpus and ran the document through the Document Conversion service. I sent the corpus to speech to text and the speech team is saying this is what the corpus contains.

```
--WoxzQEMntkWdIzwki8RvpsLK1Y5N5IBzlzbk2rdp
Content-Type: text/plain
Content-disposition: form-data; name="body"; filename="test-stt-corpus.txt"

no title

 The Entwives song Treebeard sings to Merry and Pippin but especially the last three verses When Winter comes the winter wild that hill and wood shall slay When trees shall fall and starless night devour the sunless day When wind is in the deadly East then in the bitter rain I'll look for thee and call to thee I'll come to thee again When Winter comes and singing ends when darkness falls at last When broken is the barren bough and light and labour past I'll look for thee and wait for thee until we meet again Together we will take the road beneath the bitter rain Together we will take the road that leads into the West And far away we'll find a land where both our hearts may rest
--WoxzQEMntkWdIzwki8RvpsLK1Y5N5IBzlzbk2rdp--
```

The jibberish is from the boundary I'm guessing. I'll have to do some testing. For some reason boundary and headers are being included in the corpus.

**Comment by mediumTaj** [comment]
@kimberlysiva I created a branch `gh-261-customCorpus`. I adjusted the `AddCustomCorpus` method and added a `AddCustomCorpusString` method that will take a training string. It seems to be working with the training string method. I may replace the `AddCustomCorpus` method with the new method. The service documentation says this should be multipart form data but it is ingesting the boundary and headers. It may have something to do with Unity adding quotes to their header definitions.

Can you check it out when you have a chance?

**Comment by mediumTaj** [comment]
https://github.com/watson-developer-cloud/unity-sdk/pull/263

**Comment by kimberlysiva** [comment]
The new `AddCustomCorpusString` works correctly, thanks so much! `AddCustomCorpus` does not work (it still introduces junk). I agree that we can probably remove this.
