### ISSUE TITLE
[speech-to-text] Update WebSocket parameters

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#262]
The SpeechToText class exposes `RecognizeModel`, but this isn't the correct way to set a customization id (to use a custom language model). We need an extra field that will set the `customization_id` parameter on the SendStart request.

**Comment by mediumTaj** [comment]
https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/#websockets
https://console.bluemix.net/docs/services/speech-to-text/websockets.html#websockets
https://console.bluemix.net/docs/services/speech-to-text/input.html#input

**Comment by kimberlysiva** [comment]
Thanks for linking those docs, I was trying to put `customization_id` on the start request but it needs to go on `CreateConnector`. It's finally working!

We should probably enable this on the sessionless non-streaming requests as well.

**Comment by kimberlysiva** [comment]
It'd also be helpful to expose `customization_weight`, this is a powerful way to tune things at runtime! That one goes on the start request.

**Comment by mediumTaj** [comment]
I’m glad there were helpful. I’ll work to update all of the missing params.

**Comment by mediumTaj** [comment]
From @RMichaelPickering 

>I tried a few more things, including adding a Debug to log any Warnings returned back by Watson. Based on this, I found that the parameter as defined in the Unity SDK as "small_formatting" should actually be "smart_formatting" (that is, smaRT rather than small) and the "continuous" parameter is not used by the Watson STT API at all.
>I also tried a few other values for "inactivity_timeout" including 0, 60, and 3600. Only zero seemed to have some effect on the STT behaviour but unfortunately it resulted in an immediate timeout.

Revisit all params for STT and remove deprecated.

**Comment by mediumTaj** [comment]
Cleaned up `small_formatting` vs `smart_formatting` and `continuous` in `gh-174-stt-timeout`

**Comment by mediumTaj** [comment]
@kimberlysiva FYI `customization_weight` is implemented in `gh262-update-stt-parameters`

**Comment by kimberlysiva** [comment]
Confirmed that `CustomizationId` and `CustomizationWeight` work as expected. Thanks so much!
