### ISSUE TITLE
Service Callbacks Improved Error Handling

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#265]
I've run into a couple issues with error handling on the service callbacks. First and foremost is the possibility of null pointer exceptions. Each service uses callback logic similar to this:

`((GetCustomCorpusReq)req).Callback(resp.Success ? corpus : null, !string.IsNullOrEmpty(customData) ? customData : data.ToString());`

If `resp.Success` is false then `data` is never initialized, and `data.ToString()` throws a NullReferenceException. At the very least we should fix this, as it tends to put a halt to chained requests.

Beyond this, it would be *really* nice if the callbacks returned the error code/message. For example, I'm getting a lot of 409 error codes in my Speech-to-Text customization work. This is expected, the service is locked while processing the last request. It'd be great to catch this error code and wait a little bit, rather than injecting longer delays in hopes of avoiding the error.

**Comment by RMichaelPickering** [comment]
I agree that improved warning & error handling is needed! This is true across the entire Unity SDK. There have simply been too many undetected & unhandled warnings lurking in the parts of the SDK that I've been working with (mainly Websocket 'streaming') that, even though the warnings mostly didn't cause issues directly, trying to debug my way through what was causing them took much longer because the debugging first revealed the warnings which then would need to be investigated and ruled out before I could get into the actual cause of the issue!
At the very least, the SDK itself needs to catch and pass through ALL the return codes and error/warning messages. It shouldn't be the task of 'user' developers to go refactor the SDK code just to figure out what bits are fully working vs. what bits aren't -- and in cases where bugs do get past the QA process, having more and better information would help all of us to more quickly resolve the issue!

**Comment by kimberlysiva** [comment]
@mediumTaj Let me know if this is a priority for the first asset store release. If not I'll try to get a pull-request together.

**Comment by mediumTaj** [comment]
@kimberlysiva Yes that would be great! Thanks!!!

**Comment by kimberlysiva** [comment]
@mediumTaj @RMichaelPickering

So my first thought for better error handling is something like this...

Add this class to RESTConnector:
```
/// <summary>
/// Class to encapsulate an error returned from a server request.
/// </summary>
public class Error
{
    /// <summary>
    /// The url that generated the error.
    /// </summary>
    public string URL { get; set; }
    /// <summary>
    /// The error code returned from the server.
    /// </summary>
    public int ErrorCode { get; set; }
    /// <summary>
    /// The error message returned from the server.
    /// </summary>
    public string ErrorMessage { get; set; }
    /// <summary>
    /// The contents of the response from the server.
    /// </summary>
    public string Response { get; set; }

    public override string ToString()
    {
        return string.Format("URL: {0}, ErrorCode: {1}, Error: {2}, Response: {3}", URL, ErrorCode,
                             string.IsNullOrEmpty(ErrorMessage) ? "" : ErrorMessage,
                             string.IsNullOrEmpty(Response) ? "" : Response);
    }
}
```

`RESTConnector.Response.Error` is now an Error object instead of just a string.

Now each service delegate turns into something like this:

```
public delegate void GetCustomWordsCallback(WordsList wordList, RESTConnector.Error error, string customData);
```

And the response handler looks like this:

```
private void OnGetCustomWordsResp(RESTConnector.Request req, RESTConnector.Response resp)
{
    ...
    string customData = ((GetCustomWordsReq)req).Data;
    if (((GetCustomWordsReq)req).Callback != null)
    {
        if (resp.Success)
            ((GetCustomWordsReq)req).Callback(wordsList, null, !string.IsNullOrEmpty(customData) ? customData : data.ToString());
        else
            ((GetCustomWordsReq)req).Callback(null, resp.Error, customData);
    }
}
```

(this also resolves our null reference exceptions)

The downside here is that the delegate signatures are changing... I don't mind updating everything everywhere, but are we okay with this? I'm not sure how else we can return a proper error. We could overload the customData string again and just return an error string for the user to parse, but I really want easy access to those error codes!

Finally, we need to decide where the Error class should live. The way I have it set up, devs will have to use the `IBM.Watson.DeveloperCloud.Connection` namespace to get access to `RESTConnector.Error`. Maybe that's okay, but it's something else we'll have to add everywhere (e.g. all the unit tests).

Let me know what you think! I'm open to suggestions.

**Comment by mediumTaj** [comment]
@kimberlysiva I don't think it's a bad solution. I think one of the issues that we run into for errors is that each service is a bit different and there are several types of ErrorResponse. I think the node sdk supports something like 6 different error types. 

For example Speech to Text error looks like 
```
{
  "error": "string",
  "code": 0,
  "code_description": "string",
  "warnings": [
    "string"
  ]
}
```

and Conversation looks like
```
{
  "error": "string",
  "errors": [
    {
      "message": "string",
      "path": "string"
    }
  ]
}
```

Optimally though this should be handled in the RESTConnector to avoid having to change any existing code.

**Comment by RMichaelPickering** [comment]
I think this makes sense, but as I've not used the REST connector I can't speak from direct experience! I do very much want to take a similar approach on the STT Websocket connector. In that case, it appears that we'll also have to deal with de-JSON-ifying the response from Watson.

Is there any way that the SDK itself could standardize all the Watson error messages across all the different methods and services, and just return whichever fields are applicable to a particular case, with the remainder either nullified or set to 'Unspecified by Watson' or the equivalent?

**Comment by kimberlysiva** [comment]
I've completed the service delegate error changes, you can see them in this branch of my fork: https://github.com/kimberlysiva/unity-sdk/tree/265-errorHandling

I'll open a PR once my other PR is accepted (so we don't have overlapping commits).

@mediumTaj I definitely get what you're saying about the different error formats. Right now I'm getting pretty good results from STT and Conversation. The error codes are correctly parsed, which is the most important thing! Here's an example error result from Conversation:

```
ErrorURL: https://stream.watsonplatform.net/speech-to-text/api/v1/customizations/<id>/corpora/Lexicon_Sample_Intents?allow_overwrite=True
ErrorCode: 409
ErrorMessage: 409 Conflict
ErrorResponse: {
   "code": 409,
   "code_description": "Conflict",
   "error": "Customization '<id>' is currently locked to process your last request."
}
```

So the message could be parsed better, but the user has access to the full response and can parse it further if they want.

I wasn't sure how to handle errors on the web socket... STT streaming and non-streaming share a delegate, so the streaming OnRecognize delegate also has the RESTConnector.Error parameter. Right now this is null, but we could fill it in. Or we could break those into two different delegates.
