### ISSUE TITLE
[speech-to-text] "DetectSilence" Implemented Incorrectly

### ISSUE THREAD

**Issue by RMichaelPickering** [watson-developer-cloud/unity-sdk#266]
Current implementation of silence detection is not implemented correctly. Silence threshold is recorded as a float value, presumably in the range of 0 to 1. A 'small' value that might be expected to work is something like 0.09f. However, audio samples in Unity range between -1.0f to 1.0f. In the current implementation, samples are recorded with MaxLevel is set using mathf.max which would work correctly only if the audio samples are in positive range. With the current implementation, any sample with values less than zero, such as {-0.8f, -0.9f, -0.85f, -0.7f} would be considered as 'silence' even though it actually represents a quite noisy audio sample -- but one that happens to coincide with the 'trough' of a sound wave rather than the peak!  The correct value for MaxLevel in this case should be -0.9f, although it could be argued that just using absolute value and returning MaxLevel of 0.9f in this case would be acceptable, as long as the comparison between MaxLevel and silence threshold is implemented accordingly.

This is an important feature because many real-world STT implementations (including mine) would want to listen for user voice activity and only send audio to Watson service when user is talking, to minimize bandwidth and reduce potential issues with Watson listening timeouts.

**Comment by mediumTaj** [comment]
Is this what you are proposing?

https://github.com/watson-developer-cloud/unity-sdk/pull/268
