### ISSUE TITLE
[speech-to-text] Websocket audio downsampling for Unity standalone

### ISSUE THREAD

**Issue by RMichaelPickering** [watson-developer-cloud/unity-sdk#267]
This would likely be considered an enhancement request.

On my Windows 10 development machine, the native sample rates available on my microphone are only 48,000 Hz (DVD quality) and 44,100 Hz ('Red book' CD audio quality). I believe that Unity standalone will default to 48,000 Hz, and certainly this seems to be the default for my microphone on Windows 10.

This is much higher than is needed by Watson STT service, in fact, it is my understanding that sending audio at a higher sample rate than 16,000 Hz or "Wideband" results in the Watson service downsampling to 16,000 Hz anyway.

Could we please get a downsampler implemented as part of the Unity SDK for Watson?

The current example streaming implementation is rather poorly documented and quite obscure.  Here's the code from the RecordingHandler included in the Unity SDK example, with some comments added by me:

private IEnumerator RecordingHandler()
    {
        Log.Debug("ExampleStreaming", "devices: {0}", Microphone.devices);
// RMPickering - As far as I see it, _recordingBufferSize is always just 2 samples!
// RMPickering - Also, _recordingHZ defaults to 22050 but what would happen if some mobile devices don't support such a high sample rate?
        _recording = Microphone.Start(_microphoneID, true, _recordingBufferSize, _recordingHZ);
        yield return null;      // let _recordingRoutine get set..

        if (_recording == null)
        {
            StopRecording();
            yield break;
        }

        bool bFirstBlock = true;
// RMPickering - This seems a confusing way to say midPoint = 1!
        int midPoint = _recording.samples / 2;
// RMPickering - Really, we need an array to hold one sample??
        float[] samples = null;

        while (_recordingRoutine != 0 && _recording != null)
        {
            int writePos = Microphone.GetPosition(_microphoneID);
            if (writePos > _recording.samples || !Microphone.IsRecording(_microphoneID))
            {
                Log.Error("MicrophoneWidget", "Microphone disconnected.");

                StopRecording();
                yield break;
            }

            if ((bFirstBlock && writePos >= midPoint)
              || (!bFirstBlock && writePos < midPoint))
            {
                // front block is recorded, make a RecordClip and pass it onto our callback.
                samples = new float[midPoint];
// RMPickering - Wait, does this mean that we might pick up either the first or the second sample? Why?
                _recording.GetData(samples, bFirstBlock ? 0 : midPoint);

                AudioData record = new AudioData();
// RMPickering - I already logged an issue that this code doesn't work because the samples might be negative. Use of absolute value might be required.
                record.MaxLevel = Mathf.Max(samples);
                record.Clip = AudioClip.Create("Recording", midPoint, _recording.channels, _recordingHZ, false);
                record.Clip.SetData(samples, 0);
// RMPickering - So after all this, we just end up sending the a sample up to Watson via Websocket!
                _speechToText.OnListen(record);

                bFirstBlock = !bFirstBlock;
            }
            else
            {
                // calculate the number of samples remaining until we ready for a block of audio, 
                // and wait that amount of time it will take to record.
                int remaining = bFirstBlock ? (midPoint - writePos) : (_recording.samples - writePos);
                float timeRemaining = (float)remaining / (float)_recordingHZ;
// RMPickering - This code hurts my head, but I think the second sample will never get sent, or if it does it will be after a very short wait on the next cycle through this code!
                yield return new WaitForSeconds(timeRemaining);
            }

        }

        yield break;
    }

Wouldn't a better implementation be something like this:

private IEnumerator SimpleRecordingDownSampler()

// Set SampleBuffer size to number of samples to be captured from source for each recording sample set.
// Downsampler will always record and pass on only the first sample from each samplebuffer
// So for recording at same sample rate as original recording, set SampleBuffer size = 1.
// Or to downsample, for example, from 48,000 Hz to 16,000 Hz, set SampleBuffer size = 3. (48,000 / 3 = 16,000)

This would be a very simple implementation that would work as long as a small, even integer number of source samples need to be discarded on each cycle to correctly implement the downsampler.

**Comment by RMichaelPickering** [comment]
Upon further consideration, I believe that the existing Streaming example is likely implemented as a full audio Re-Sampler in that it may be capable of up-sampling audio as well as down-sampling. For re-sampling audio captured at a lower sample rate and streaming at a higher rate (up-sampling), it appears to use a rather naive approach by simply copying the last value rather than interpolating between captured values. For re-sampling at a lower rate (down-sampling) it uses the 'closest' sample in time, which again is a somewhat more naive approach as compared to interpolation which should give better results in case the sample rates differ by a non-integer factor.

Some better documentation, such as putting comments into the code to explain all this, would go a long way towards helping future SDK users to get through some of the potential gotchas much more easily.

**Comment by RMichaelPickering** [comment]
OK, now I've thoroughly looked through the Streaming example and am in the midst of making some significant changes. One more issue that I've found is that the example implementation uses a two second audio clip as a circular audio buffer, and in starting up the pseudo-streaming microphone handler service it essentially pauses the handler to wait at least one second for the audio buffer to be written by Unity with at least one second's worth of audio samples. This will introduce a significant lag even before Watson's speech recognizer starts to receive data, and as the handler finishes pseudo-streaming the first one second of audio data, the microphone handler will be paused again to wait for the next one second worth of audio samples to be written by Unity, and so on. Essentially this means that there will be an average lag of more than one second before Watson STT receives the end of each user utterance. Of course, this doesn't account for network latency or Watson processing lags. I believe that this implementation puts Watson STT at a significant disadvantage to delivering a responsive and engaging user experience!
Just one final note: upon deeper analysis, it now seems clear that audio re-sampling is not included in the Example implementation so it should be clearly documented that the sample rate used by the standard Unity Microphone recorder must match the sample rate as specified on the AudioData array that is pseudo-streamed to Watson via Websocket. Furthermore, if a lower sample rate such as 16 kHz is supported by the SDK, this should be recommended as a better match to the Watson STT service because that service would need to downsample any audio send at a higher rate to 16 kHz anyway as this is the sample rate used by the Watson "Wideband" recognition model. Sending data to Watson via Websocket at a higher rate than 16 kHz thus wastes network bandwidth and could incur higher than needed data Upload charges.

**Comment by mediumTaj** [comment]
@RMichaelPickering The streaming example is mean to simply show that audio can be grabbed from microphone input and sent to Speech to Text. It's really left up to the user how they want to get audio data based on their use case. I do agree it needs a lot of work to make something more permanent...If you would like to take a stab at creating an example, we gladly accept pull requests!

As far as downsampling audio, we have been stripping out excess functionality from the Watson Unity SDK to bring it in line with all of the other Watson SDKs - only service abstractions. We will, however, be building another package that will depend on the SDK for all of this extra functionality. Previous versions of the SDK had a widget system that would let users easily drag and drop prefabs to connect Watson services.

**Comment by RMichaelPickering** [comment]
@mediumTaj This needs to be upgraded to a bug. On my development machine running Windows 10 and Unity, my standard hardware microphone only offers sample rates of 44.1 and 48 kHz. The only way to set these sample rates is by configuring the device using Windows. Thus, setting any lower sample rate in the Watson Speech To Text SDK and example, such as 22050, does not actually work as it gets overridden to whatever is set at the Windows device level. This isn't being picked up by the standard SDK code and examples, as the Method to check what sample rates are supported by the device, Unity's Microphone.GetDeviceCaps, isn't being checked in this code.
At a minimum, it should be documented that the actual sample rate will be as specified at the o/s and device level. Furthermore, there is a strong argument that an audio downsampler should be included in the SDK given that there isn't any compression available and the available hardware-supported sample rates are much higher than is needed for Watson STT.
To be clear, I've implemented a new version of the pseudo-streamer to minimize latency. This was relying on the microphone sample rate being set as documented in the Watson SDK. Unfortunately, because the actual behaviour is quite different, my entire Unity project crashes every time I try to run it now.
It looks like I'll need to add a rudimentary Downsampler to get this working properly!

**Comment by mediumTaj** [comment]
@RMichaelPickering I don't know when I'll have time to look at this. If you end up with a good solution please create a PR! Thanks for your help identifying this issue!

**Comment by RMichaelPickering** [comment]
@mediumTaj I guess this issue should be changed to request explicit documentation that the setting of sample rate in Unity, and especially, the variable "_recordingHZ" in the streaming example, will over-ride the sample rate as shown at the Windows o/s level. Ideally, there should be some test cases for this across different platforms.

**Comment by mamoonraja** [comment]
I am closing this one as we provide examples as a way to get started with the service, please feel free to open PR's to echance the functionality in examples.
