### ISSUE TITLE
[speech-to-text] Websocket "Keep Alive" audio format much match Microphone

### ISSUE THREAD

**Issue by RMichaelPickering** [watson-developer-cloud/unity-sdk#271]
If the Websocket "Keep Alive" is still needed, it must match recording format of Microphone to avoid confusing the Watson STT service. Currently, my Microphone is capturing at a sample rate of 48kHz in Stereo. The Unity Watson SDK is trying to use a "highHat" as a keepalive but this is a WAV format so presumably recorded at a sample rate of 48 kHz. Ideally, I'm going to implement a downsampling routine so that I can downsample my microphone to match Watson's "Wideband" sampling rate of 16 kHz, and "Narrowband" or any other Watson-supported sampling rates must also be handled by the Watson Websocket "Keep Alive" service.

**Comment by mediumTaj** [comment]
Moving to related issue https://github.com/watson-developer-cloud/unity-sdk/issues/258
