### ISSUE TITLE
[speech-to-text] Websocket Enqueues AudioData but Never Sends!

### ISSUE THREAD

**Issue by RMichaelPickering** [watson-developer-cloud/unity-sdk#273]
Trying to send AudioData up to Watson STT recognizer from Unity SDK using Websocket streaming and with InactivityTimeout = -1. Audio data is being enqueued by Watson STT service in Unity but it never gets dequeued and sent up to Watson. This crashes Unity as the buffer grows without bound.

I'm not sure why, but the ListenTimeout, which is set to a default value of 10.0f in the SDK, does not seem to ever be tripped.

**Comment by RMichaelPickering** [comment]
I'm willing to share my code for debugging purposes if it will help.

**Comment by RMichaelPickering** [comment]
OK, I hacked the STT OnListen routine to just start sending without waiting on ACK from Watson. This at least sends data but never seems to catch up with the available Audio clip data. I see that Unity keeps eating memory but there is also some network traffic. It appears that the OnListen sender has to loop on sending as long as there's more data to send. Will try this tomorrow.

**Comment by mediumTaj** [comment]
@RMichaelPickering Did you get this working? One thing we have an open issue for is [updating stt websocket parameters](https://github.com/watson-developer-cloud/unity-sdk/issues/262). These should be set as soon as the websocket opens but right now they aren't. 

See [here](https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/#websockets).

**Comment by RMichaelPickering** [comment]
@mediumTaj Thanks for the suggestions but I don't believe the other issue is quite the same thing, unless I"m missing something. It seems to be saying that certain optional parameters are needed, such as for using a custom corpus, but these are not yet defined in the Unity SDK. However, I don't believe that there are any missing parameters in my case. It seems like the recognize session and Websocket gets created but then there's some issue with actually sending the audio out the Websocket. It appears that at least part of the problem is that the STT SDK service is waiting on some kind of acknowledgement from Watson that it is listening.

On the other hand, it's hard to know exactly what should be happening because as far as I know there's no detailed documentation of the expected API interactions in Unity. It would be great to have the equivalent of what's included on this link, but with the equivalent Unity calls and syntax: https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/?node#recognize_audio_websockets

**Comment by RMichaelPickering** [comment]
@mediumTaj To be clear, I'm not trying to use a custom corpus, or anything custom at all. I just need 'standard' Watson STT with some custom keywords.

Looking at the code inside the STT API calls from Unity themselves, it seems unclear as to which method or class is intended to stream the audio into the Websocket. I think I see the call to open the Websocket itself but I'm not able to find the sending code itself, which would presumably get called sometime after the Websocket has been opened. Is there perhaps a missing bit to send the audio stream?

Would it help to trace through what calls get received by the Watson cloud service itself?

**Comment by RMichaelPickering** [comment]
Further hacking seems to be getting closer to fully working. I added a call to SendStart just after calling CreateListenConnector. I guess I need to check the return codes to see if Watson is happy with the stream format!
