### ISSUE TITLE
[Speech To Text] Can't open stream to Frankfurt server

### ISSUE THREAD

**Issue by janhassel** [watson-developer-cloud/unity-sdk#277]
With the API Endpoint host set to `stream-fra.watsonplatform.net` I can't open a stream (tested with your example). The host `stream.watsonplatform.net` works fine though. 

Seems to be an issue with the host server.

**Comment by mediumTaj** [comment]
Addressed in https://github.com/watson-developer-cloud/unity-sdk/releases/tag/2.4.1

Please use Unity 2018.2 since the endpoint is TLS 1.2
