### ISSUE TITLE
Platform dependent tests and examples

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#282]
#Tests and examples were built to use paths for osx/windows machines. The tests and examples fail in ios and android because the paths are different on those platforms. Update the tests and examples to change path based on platform. Move the TestData to StreamingAssets.

```
#region Platform specific data path
public static string GetPlatformDependentPath(string pathInStreamingAssets)
{
    string path;
#if UNITY_IOS
    path = string.Format("{0}/Raw/{1}", Application.dataPath, pathInStreamingAssets);
#elif UNITY_ANDROID
    path = string.Format("jar:file://{0}!/assets/{1}", Application.dataPath, pathInStreamingAssets);
#else
    path = string.Format("{0}/StreamingAssets{1}", Application.dataPath, pathInStreamingAssets);
#endif
    return path;
}
#endregion
```

**Comment by kimberlysiva** [comment]
@mediumTaj Good call, I actually moved the test data to streaming assets when testing on Hololens.

Why not use `Application.streamingAssetsPath`?

**Comment by mediumTaj** [comment]
Yes, this is a case of me not reading through the [whole page](https://docs.unity3d.com/Manual/StreamingAssets.html)!

**Comment by mediumTaj** [comment]
Actually I realize why we don't do this. The SDK does not have a Unity Project thus doesn't have a `StreamingAssets` directory. If we could have multiple StreamingAssets directories it would be OK but I don't think that's possible. Maybe `Resources` directory? I'm not sure that's appropriate either. I might end up having to store `TestData` in the sdk root and copy it when running tests or examples.
