### ISSUE TITLE
Android deployement ?

### ISSUE THREAD

**Issue by stephane-lallee** [watson-developer-cloud/unity-sdk#3]
Hi,

Sorry to spam. I just tried deploying the demo speech recognition app to an android phone. The compilation / deployement has no issue, but when it comes to the authentification it seems to fail to load the credential (I saw that in the adb log).

Is the SDK supposed to work for Android as well or is it restricted to windows / unity editor ?
Will it be supported any time in the future ?

**Comment by rolyle** [comment]
Hi,
 
 
It works on android, but you need to add a wait for the configuration to be loaded before you attempt to use the services, Android has to load using the WWW class. 
 
see MainUI.cs.. 
 
        while (!Config.Instance.ConfigLoaded)            yield return null; 
Not much of a way around this, just the nature of Android..
 
 
----- Original message -----From: Stephane Lallee <notifications@github.com>To: watson-developer-cloud/unity-sdk <unity-sdk@noreply.github.com>Cc:Subject: [unity-sdk] Android deployement ? (#3)Date: Wed, Jan 13, 2016 10:28 PM 
Hi,
Sorry to spam I just tried deploying the demo speech recognition app to an android phone The compilation / deployement has no issue, but when it comes to the authentification it seems to fail to load the credential (I saw that in the adb log)
Is the SDK supposed to work for Android as well or is it restricted to windows / unity editor ?Will it be supported any time in the future ?

**Comment by rolyle** [comment]
I Added a ConfigLoader component that you can put in your main scene, it will wait for the Config to get loaded then will instantiate a prefab that you provide.

**Comment by bmahajan** [comment]
@rlyle Sorry for asking, but where exactly do we insert this line ?

**Comment by Musclelad** [comment]
Hello, I'm also having this same issue when I run it my PC. The Speech to Text Watson services isn't working fine, but when I take a build in android the Speech to text service isn't working.

**Comment by shyamraje1012** [comment]
I am developing 3d voice bot by using unity 2019.3.1f7, vuforia , watson 4.6 sdk from gethub. I created 1)  speech to text 2) voice bot. It works fine in unity playmode and windows pc . but when i create android application. android app  does not work. in condo i get error message with this line.  
System.Windows.Forms.dll assembly is referenced by user code, but is not supported on Android platform. Various failures might follow.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) kindly suggest me solution.
