### ISSUE TITLE
Internet Unreachable Handling

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#305]
If we call any REST API function when not connected to the internet we should receive the error callback. Currently, we are getting the success callback instead.

**Comment by mediumTaj** [comment]
@kimberlysiva Took a quick stab at this, can you try it out?

https://github.com/watson-developer-cloud/unity-sdk/pull/306

**Comment by kimberlysiva** [comment]
@mediumTaj Seems to do the trick, thanks so much!
