### ISSUE TITLE
Allow Runnable to work in play mode

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#310]
Currently the Runnable class does not update while the application is playing:

```
        static void UpdateRunnable()
        {
            if (!Application.isPlaying)
                Instance.UpdateRoutines();
        }
```

For our extension, we would like to be able to sync with the cloud in the Editor, even while in play mode. We currently have an `EnableRunnableInEditor` static function, could we add `EnableRunnableInPlayMode`? Thanks!

**Comment by kimberlysiva** [comment]
Actually let me investigate this a bit further, I think there's a simple workaround.

**Comment by kimberlysiva** [comment]
Hmm, this is a tricky one... We don't want to call `UpdateRoutines` in play mode, because that causes each Runnable to update twice per frame (once manually and once by the coroutine).

The problem lies with runnables on MonoBehaviours that don't exist in the scene.. So for example a MonoBehaviour set up as a singleton with `HideFlags.HideAndDontSave`. Coroutines don't work in this situation. Our extension uses a singleton like this to manage syncing with the cloud, and I'd like the sync to continue to work even when the user presses play. I can create my own runnable class and handle these separately, but the RESTConnector uses the existing runnable and therefore won't update while in play mode in the editor (unless attached to a scene object, but we don't really want to do that).

This situation is probably pretty specific to our use-case, so I'll close this for now. Leaving this comment here in case anyone else stumbles on this issue!

**Comment by kimberlysiva** [comment]
Okay! Finally figured this out. It was definitely a problem with our code. We have an editor singleton for syncing with Watson, and I was starting our process loop (and coroutines) in OnEnable (with ExecuteInEditMode set). For some reason, with singletons that are being recreated after an assembly reload, OnEnable is too early a point to start a coroutine. I've moved our process startup logic to the first pass through the Update method, and now things work!

**Comment by mediumTaj** [comment]
Ah nice! Ok good to hear
