### ISSUE TITLE
Singleton visibility

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#311]
Currently the Singleton class has `SINGLETONS_VISIBLE` defined, making singletons always visible in the Editor. This causes a little confusion with our extension. Can we add a static function to enable/disable singleton visibility, instead of using a #define? Or, simply set the singletons to be invisible as default.

**Comment by mediumTaj** [comment]
Sure, Ill take a look when I get a chance! Alternatively if its time sensitive you could put in a PR with a prop to control this

**Comment by kimberlysiva** [comment]
Sure thing @mediumTaj, I'll make a PR tomorrow.

**Comment by kimberlysiva** [comment]
Ah, never mind! You can change the hide flags after the instance has been created. This works:

```
Runnable.Instance.gameObject.hideFlags = HideFlags.HideAndDontSave;
```
