### ISSUE TITLE
Watson and Socket.IO

### ISSUE THREAD

**Issue by NawarRajab** [watson-developer-cloud/unity-sdk#315]
Hi, I'm trying to run watson and socket.io on unity. I'm using the following for socket.io : [socket.io](https://github.com/floatinghotpot/SocketIoClientDotNet)

both watson and socket.io work find separately but once I put them together I get the following error: 

> Assets/WatsonUnity/unity-sdk-develop/ThirdParty/FullSerializer/fsConfig.cs(71,16): error CS0433: The imported type `System.Func<T1,T2,TResult>' is defined multiple times

In addition, watson and socket.io use a different builds of websocket for .net that don't seem to be interchangeable. Is there any solution to this? Did any one manage to get watson and socket.io working together?

**Comment by mediumTaj** [comment]
The Watson Unity SDK has a dependency on WebSocketSharp and the dll is included in the plugins directory. We have not tried to use socket.io with the SDK. You might want to try to reach out to StackOverflow for this question.

**Comment by NawarRajab** [comment]
Thanks for the reply. I managed to find a socket.io that uses WebSocketSharp . Problem solved.
