### ISSUE TITLE
[visual-recognition] Latest Visual Recognition service fails with the POST format of Classify with byte[] array

### ISSUE THREAD

**Issue by DSDubit** [watson-developer-cloud/unity-sdk#320]
As of 15/02/2018, the format of the POST request made in VisualRecognition.cs.Classify (:251) seems to reliably cause a 500 Internal Server Error response from Watson. We have determined that sending the full image data in the body of the request (as the current revision of the SDK does) is no longer supported, but now expects the image to be sent as a jSon body { "Image" : <imageData> } with an appropriate MIME type.

We solved the issue by making the following change to line 274:

    req.Headers["Content-Type"] = "multipart/form-data";
    req.Headers["Accept"] = "application/json";

...and changing the request body to:

    if (imageData != null)
    {
        req.Forms = new Dictionary<string, RESTConnector.Form>
        {
            { "images_file", new RESTConnector.Form(imageData, System.Net.Mime.MediaTypeNames.Image.Jpeg) }
        };
    }

You may wish to parameterise the MIME type, but as far as I know since WVR only supports Jpeg and Png, the only valid MIME type is image/jpeg.

Also, it doesn't seem to matter what the key is. "images_file", "image", "img", "ahjdfhfjdgyhfsn", all work.

**Comment by mediumTaj** [comment]
Good catch! Waiting for CI and review. https://github.com/watson-developer-cloud/unity-sdk/pull/323
