### ISSUE TITLE
[Speech to text] Suddenly getting error "Expected a JSON header message before receiving binary data."

### ISSUE THREAD

**Issue by Naphier** [watson-developer-cloud/unity-sdk#324]
Reproduction:
Run ExampleStreaming with correct credentials. Wait about 30 seconds. Error will log "Expected a JSON header message before receiving binary data.", speech recognition will not work. Using Unity 2017.3.1f1 on Windows 10. Unfortunately, there are no further details to provide as this code and connection worked flawlessly just a few hours ago. I've tried rebooting the Unity editor.
Log:
[Editor.log](https://github.com/watson-developer-cloud/unity-sdk/files/1744163/Editor.log)

Expected: 
No error and OnRecognize callback to receive data.

Environment:
Watson Unity SDK 2.0.0
Unity 2017.3.1f1 (Editor)
Windows 10 pro 64-bit

**Comment by Naphier** [comment]
....and of course as soon as I report the issue, it seems to start working again. Perhaps IBM cloud was unreachable.
Requesting documentation on the various possible error strings and potential remedies. Or at least error messages that are a bit more helpful. Thanks!

**Comment by aestiff** [comment]
I was getting this issue intermittently a few weeks ago. I cooked in a check every second to see if listening was stopped, and restarted if not. Seems to work OK, but it'd be nice if it weren't necessary.

**Comment by stormihoebe** [comment]
I have been having this problem for the past 2 days. Any updates on this?

**Comment by mediumTaj** [comment]
Did this just start happening? It may be a service issue. If you have a way of reproducing please post it here.

**Comment by stormihoebe** [comment]
@mediumTaj Actually, never mind. It was my own error. Thanks for the response.

**Comment by mediumTaj** [comment]
Closing this as I haven't been able to reproduce. If there are steps to reproduce I will reopen.
