### ISSUE TITLE
[Speech to text] Keep alive fails to keep service running

### ISSUE THREAD

**Issue by Naphier** [watson-developer-cloud/unity-sdk#325]
Unity 2017.3.1f1
Watson Unity SDK 2.0.0
Windows 10 64-bit pro - Unity Editor

Unity Watson SDK - ExampleStreaming scene (no modifications to code)

Expected:
Session doesn't timeout and remains alive.

Actual:
After about 1 minute Session Timeout error occurs. "Sending keep alive" console messages appear, but doesn't seem to help.

Editor log attached.
[Editor.log](https://github.com/watson-developer-cloud/unity-sdk/files/1748571/Editor.log)

Current workaround: 
I'm just using a coroutine to wait half a second and then restart the service. Not really ideal as there will be periods when the service is off.

**Comment by mediumTaj** [comment]
Can you see if setting `DetectSilence` to false helps?

https://github.com/watson-developer-cloud/unity-sdk/blob/develop/Examples/ServiceExamples/Scripts/ExampleStreaming.cs#L63

Trying to narrow down this issue.

**Comment by Olegjan** [comment]
Hello, I also have similar error, but in string 
[SpeechToText.OnListenClosed()][DEBUG] OnListenClosed(), State = DISCONNECTED
Can you help?

**Comment by mediumTaj** [comment]
@Olegjan This is a different issue. Services just switched from TLS 1.0 to TLS 1.2 and the ws library is not liking it. see this issue https://github.com/watson-developer-cloud/unity-sdk/issues/330

A hotfix for this will be out soon

**Comment by cjloh** [comment]
hi, is there any other way to keep the session alive with DetectSilence set to true? currently i set InactivityTimeout = -1 and every 20 seconds i will send "highHat" clip with OnListen method and yet i couldn't keep the session alive.

**Comment by erics1033** [comment]
@mediumTaj Was wondering what you would recommend to solve this issue? (error CS0117: `System.Security.Authentication.SslProtocols' does not contain a definition for `Tls12') If I get rid of the line with Tls12, I end up having the same issue as @Olegjan . Any help would be greatly appreciated.

<img width="1026" alt="screen shot 2018-07-24 at 8 55 31 am" src="https://user-images.githubusercontent.com/27321586/43143012-6b08643a-8f1f-11e8-982e-0c13a1e1b1c4.png">

**Comment by mediumTaj** [comment]
If using Unity 2018.2 or later you'll need to set Scripting Runtime Version in Build Settings to .NET 4.x equivalent. We need to access security options to enable TLS 1.2.

https://github.com/watson-developer-cloud/unity-sdk#configuring-unity

**Comment by erics1033** [comment]
Thanks got it working!

**Comment by rasca0027** [comment]
Hi, I did everything above but still get this error.
After SendStart I immediately get OnListenClosed(), State = DISCONNECTED and KeepAlive exited.

**Comment by HjoshM** [comment]
My Scripting Runtime Version in Build Settings is already set to .NET 4.x but I still get this error message... What am I missing?

**Comment by cocapasteque** [comment]
Same here, using Unity 2018.3.0f2. 
Can't get the samples to work.

`[01/14/2019 09:10:39][SpeechToText.CreateListenConnector()][DEBUG] Created listen socket. Model: en-US_BroadbandModel, parsedParams: 
[01/14/2019 09:10:39][ExampleStreaming.RecordingHandler()][DEBUG] devices: Microphone (Realtek Audio)
[01/14/2019 09:10:40][SpeechToText.SendStart()][DEBUG] SendStart() with the following params: {"action":"start","content-type":"audio/l16;rate=22050;channels=1;","inactivity_timeout":-1,"interim_results":true,"max_alternatives":0,"profanity_filter":false,"smart_formatting":true,"speaker_labels":false,"timestamps":true,"word_confidence":true}
[01/14/2019 09:10:41][SpeechToText.OnListenClosed()][DEBUG] OnListenClosed(), State = DISCONNECTED
[01/14/2019 09:10:41][SpeechToText.KeepAlive()][DEBUG] KeepAlive exited.
`

I used both https://stream-tls10.watsonplatform.net/speech-to-text/api and https://gateway-lon.watsonplatform.net/speech-to-text/api URLs but it didn't work..

Is this unity-sdk is still maintained ?

**Comment by mediumTaj** [comment]
@cocapasteque Yes the sdk is still maintained. London endpoint is relatively new. I've had users successfully access it even though we are not explicitly handling it in the SDK. I will patch that up this week though. Are you using .NET 4.x Scripting Runtime?

https://github.com/watson-developer-cloud/unity-sdk#configuring-unity

You can also join our #unity-sdk slack channel in `wdc-community`: http://wdc-slack-inviter.mybluemix.net/

**Comment by cocapasteque** [comment]
@mediumTaj Yes of course I'm using .NET 4.x. 
Should I use a different endpoint and test with this ? 

Gonna join on slack also :)
Thanks for your answer

**Comment by cocapasteque** [comment]
@mediumTaj Created a new resource located in Washington DC, still not working.
I'm going to try with a older unity version.

**Comment by cocapasteque** [comment]
@mediumTaj 
Working with 2018.2.0f2, didn't worked with 2018.3.0f2. I really have no idea why.

**Comment by cocapasteque** [comment]
@mediumTaj Last message in this thread for me, found why it wasn't working...
Scripting Runtime was set on .NET 4.x but the Api Compatibility Level was on .NET Standard 2.0, switched it to 4.x and it worked. 

You should at this somewhere in your documentation, not only the Scripting runtime should be on .NET 4.x but also the API Compatibility Level. :) Thank you !

**Comment by mediumTaj** [comment]
Hmm ok. I’ll add to the readme. I’m glad you got it working!

**Comment by tiancaipipi110** [comment]
@mediumTaj Just upgraded and migrated my STT service to resource group using IAM authentication, however STT stops working. See error:
```
1.) [02.12.2019 18:16:07][SpeechToText.SendStart()][DEBUG] SendStart() with the following params: {"action":"start","content-type":"audio/l16;rate=22050;channels=1;","inactivity_timeout":-1,"interim_results":true,"max_alternatives":0,"profanity_filter":false,"smart_formatting":true,"speaker_labels":false,"timestamps":true,"word_confidence":true}
UnityEngine.Debug:Log(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Debug/DebugReactor.cs:68)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Debug(String, String, Object[]) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:228)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:SendStart() (at Assets/Watson-2.13.2/Scripts/Services/SpeechToText/v1/SpeechToText.cs:765)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:OnListen(AudioData) (at Assets/Watson-2.13.2/Scripts/Services/SpeechToText/v1/SpeechToText.cs:592)
<RecordingHandler>d__51:MoveNext() (at Assets/MyAssets/Scripts/Watson_newServices.cs:348)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson-2.13.2/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

2.) [02.12.2019 18:16:08][SpeechToText.OnListenClosed()][DEBUG] OnListenClosed(), State = DISCONNECTED
UnityEngine.Debug:Log(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Debug/DebugReactor.cs:68)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Debug(String, String, Object[]) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:228)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:OnListenClosed(WSConnector) (at Assets/Watson-2.13.2/Scripts/Services/SpeechToText/v1/SpeechToText.cs:901)
IBM.Watson.DeveloperCloud.Connection.<ProcessReceiveQueue>d__47:MoveNext() (at Assets/Watson-2.13.2/Scripts/Connection/WSConnector.cs:406)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson-2.13.2/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

3.) [02.12.2019 18:16:08][SpeechToText.KeepAlive()][DEBUG] KeepAlive exited.
UnityEngine.Debug:Log(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Debug/DebugReactor.cs:68)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Debug(String, String, Object[]) (at Assets/Watson-2.13.2/Scripts/Logging/Logger.cs:228)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.<KeepAlive>d__148:MoveNext() (at Assets/Watson-2.13.2/Scripts/Services/SpeechToText/v1/SpeechToText.cs:808)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson-2.13.2/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

I'm using Unity 2018.3.0f2, Watson 2.13.2, runtime version .NET4.xEquivalent,  API compatibility level .NET 4.x, `SilenceThreshold=0.0001f`, and` InactivityTimeout = -1`. IAM api key is tested to be valid. I have no idea what else can be wrong in here. Could you please help?

**Comment by samuelthomson** [comment]
Hello, I'm getting the same error message (KeepAlive exited).  But I'm using Unity 2019.2.1 and the option "Scripting Runtime Version" options are no longer available.  Instead I set Api Compatibility to .Net 4.x, and I set "Scripting Backend" to IL2CPP.  However, I'm still getting the same error message. 

Is there anything else to try?

**Comment by mediumTaj** [comment]
@samuelthomson Can you try the branch in this PR? https://github.com/watson-developer-cloud/unity-sdk/pull/602

The important part being yielding for the keepAlive audio to load
```cs
AudioClip _keepAliveClip = Resources.Load<AudioClip>("highHat");
while (_keepAliveClip.loadState != AudioDataLoadState.Loaded)
    yield return null;
```

**Comment by samuelthomson** [comment]
I'm not a regular Github user, can you tell me how I can do that?  I'm not sure how to integrate anything from that page into my project.  Is there a quick explanation?

**Comment by samuelthomson** [comment]
Well, I manually added the line recommended here: "https://github.com/watson-developer-cloud/unity-sdk/issues/601" to ExampleStreaming.cs and it now seems to be working.  Where would you add the code you quoted, and what would that add?

**Comment by mediumTaj** [comment]
Search for the following line in `Scripts/Services/SpeechToText/V1/SpeechToTextServiceExtension.cs`
```cs
AudioClip _keepAliveClip = Resources.Load<AudioClip>("highHat");
```

Add these two lines below that line
```cs
while (_keepAliveClip.loadState != AudioDataLoadState.Loaded)
    yield return null;
```

**Comment by samuelthomson** [comment]
Thanks, that seems much better.

**Comment by samuelthomson** [comment]
Hello, I loaded up the same project today, it works for about 20-30 seconds, and then I get the following error messages: 

[10/22/2019 12:20:13][SpeechToText.OnListen()][ERROR] Failed to enter listening state.
UnityEngine.Debug:LogError(Object)
[10/22/2019 12:20:13][ExampleStreaming.OnError()][DEBUG] Error! Failed to enter listening state.
UnityEngine.Debug:Log(Object)
[10/22/2019 12:20:13][SpeechToText.KeepAlive()][DEBUG] KeepAlive exited.
UnityEngine.Debug:Log(Object)

I haven't change anything since last night, when I tested it for a few minutes and it seemed fine.

**Comment by LuckyAnix** [comment]
Working fine in the unity editor but in exe build it throwing error. Seems token empty. Can anyone help ?
InvalidOperationException: Nullable object must have a value.
  at System.Nullable`1[T].get_Value () [0x00000] in <00000000000000000000000000000000>:0 
  at IBM.Cloud.SDK.Authentication.Iam.IamToken..ctor (IBM.Cloud.SDK.Authentication.Iam.IamTokenResponse response) [0x00000] in <00000000000000000000000000000000>:0 
  at IBM.Cloud.SDK.Authentication.Iam.IamAuthenticator.OnGetToken (IBM.Cloud.SDK.DetailedResponse`1[T] response, IBM.Cloud.SDK.IBMError error) [0x00000] in <00000000000000000000000000000000>:0 
  at IBM.Cloud.SDK.Authentication.Iam.IamAuthenticator.OnRequestIamTokenResponse (IBM.Cloud.SDK.Connection.RESTConnector+Request req, IBM.Cloud.SDK.Connection.RESTConnector+Response resp) [0x00000] in <00000000000000000000000000000000>:0 
  at IBM.Cloud.SDK.Connection.RESTConnector+<ProcessRequestQueue>d__33.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at IBM.Cloud.SDK.Utilities.Runnable+Routine.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0

**Comment by WarriorWork** [comment]
> Working fine in the unity editor but in exe build it throwing error. Seems token empty. Can anyone help ? InvalidOperationException: Nullable object must have a value. at System.Nullable`1[T].get_Value () [0x00000] in <00000000000000000000000000000000>:0 at IBM.Cloud.SDK.Authentication.Iam.IamToken..ctor (IBM.Cloud.SDK.Authentication.Iam.IamTokenResponse response) [0x00000] in <00000000000000000000000000000000>:0 at IBM.Cloud.SDK.Authentication.Iam.IamAuthenticator.OnGetToken (IBM.Cloud.SDK.DetailedResponse`1[T] response, IBM.Cloud.SDK.IBMError error) [0x00000] in <00000000000000000000000000000000>:0 at IBM.Cloud.SDK.Authentication.Iam.IamAuthenticator.OnRequestIamTokenResponse (IBM.Cloud.SDK.Connection.RESTConnector+Request req, IBM.Cloud.SDK.Connection.RESTConnector+Response resp) [0x00000] in <00000000000000000000000000000000>:0 at IBM.Cloud.SDK.Connection.RESTConnector+d__33.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 at IBM.Cloud.SDK.Utilities.Runnable+Routine.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0

Me too, when I changed newtonsoft.Json to newer... what can I do? have you solved it?
