### ISSUE TITLE
Unable to register IBM Cloud Account in China.

### ISSUE THREAD

**Issue by fingerx** [watson-developer-cloud/unity-sdk#327]
Unable to register IBM Cloud Account in China.
using gmail and Google Chrome  62.0.3202.94 . I want know why? Is service unavailable in China?
thanks.

**Comment by tufeixp** [comment]
Well, you need to break the GFW first.

**Comment by mediumTaj** [comment]
@fingerx Do you have more info on this? What are you seeing? Is there an error message?

**Comment by fingerx** [comment]
thanks @mediumTaj @tufeixp  update Google Chrome register is ok and dnot need to use vpn.
