### ISSUE TITLE
[log-system] Warn user to installDefaultReactors()

### ISSUE THREAD

**Issue by JimZeeKing** [watson-developer-cloud/unity-sdk#328]
I just stumbled upon this problem and while it's not a bug, maybe throwing a warning if we use ` Log.Debug` without first calling ` LogSystem.InstallDefaultReactors();` would be a good idea for new users.

Thanks for your great work!

- [x] Check if default reactors are installed when calling `Log.Debug()`
- [ ] Install default reactors or output message for developer to install default reactor

**Comment by mediumTaj** [comment]
Addressed in this PR https://github.com/watson-developer-cloud/unity-sdk/pull/380
