### ISSUE TITLE
[speech-to-text] Unable to connect to streaming service.

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#330]
Transition for TLS 1.0 to 1.2 has broken the SDK's connection to STT streaming. Working on a fix to use the TLS 1.0 endpoint until this is resolved.

For now you can set the endpoint to `https://stream-tls10.watsonplatform.net/speech-to-text/api`

**Comment by Naphier** [comment]
Thank you.

**Comment by mediumTaj** [comment]
waiting for CI https://github.com/watson-developer-cloud/unity-sdk/pull/331

**Comment by mediumTaj** [comment]
fixed and merged into develop. updating on asset store.

**Comment by Naphier** [comment]
Is that new endpoint going to remain alive? Mono.Security has issues with TLS 1.2, which will likely never be fixed and we may have to wait for non-experimental support of .NET 4.5 in Unity for it to work. As someone who pays for this service, I'm a bit disappointed that, in our second week of usage, there's already been a major breaking issue.

**Comment by mediumTaj** [comment]
The TLS 1.0 endpoints should keep working.

https://console.bluemix.net/docs/get-support/appsectls.html#tlssupportwithdraw

>If you need to continue to use TLS 1.0 or 1.1 when connecting to Watson products and services after support is withdrawn you can replace gateway.watsonplatform.net with gateway-tls10.wastonplatform.net or stream.watsonplatform.net with stream-tls10.watsonplatform.net. gateway-tls10.watsonplatform.net and stream-tls10.watsonplatform.net support TLS 1.0, 1.1, and 1.2 and will continue be available for your use after TLS 1.0 and 1.1 are removed from gateway.watsonplatform.net and stream.watsonplatform.net.

**Comment by jagatfx** [comment]
@mediumTaj fyi typo in your last comment and also on webpage https://console.bluemix.net/docs/get-support/appsectls.html#tlssupportwithdraw `gateway-tls10.wastonplatform.net` instead of `gateway-tls10.watsonplatform.net` (waston instead of watson)

Also, shouldn't there also be a replacement for gateway at https://github.com/watson-developer-cloud/unity-sdk/blob/682c8a0ed6488d7f166ad486b4cbc5e69a996778/Scripts/Connection/WSConnector.cs#L177 like what was done in https://github.com/watson-developer-cloud/unity-sdk/pull/331?

**Comment by mediumTaj** [comment]
@jagatfx thanks, will look into the typo! As far as gateway - it looks like tests connecting to gateway are running fine. Only wss calls are having issues. I will need to investigate further. If you are having issues with the gateway endpoint please let me know!

**Comment by jagatfx** [comment]
@mediumTaj sure thing. I haven't tested with `gateway.watsonplatform.net` used by the conversation service after the TLS1.2 change but glad to hear it should work as is. Cheers!

**Comment by NawarRajab** [comment]
The Unity store plugin was updated over the week end, but it's still not working.  Replaced the URL to 
[](https://stream-tls10.watsonplatform.net/speech-to-text/api)  but still not working. Any suggestion  on what to do next?

**Comment by mediumTaj** [comment]
@NawarRajab what is your error?

**Comment by NawarRajab** [comment]
@mediumTaj it seems that Watson disconnects immediately. I was working one week ago.
![image](https://user-images.githubusercontent.com/32341311/37060330-cde3c3a4-2144-11e8-96f9-cebae22e4a68.png)

**Comment by mediumTaj** [comment]
Please delete your SDK and redownload it from either the Asset Store or GitHub

**Comment by NawarRajab** [comment]
@mediumTaj it worked! Thanks.

**Comment by BirdInTheCity** [comment]
@mediumTaj  Is there a plan to deprecate the TLS 1.0 endpoint? (https://stream-tls10.watsonplatform.net/speech-to-text/api)

I realize it won't be officially supported, but will it be eliminated? And, if so, when?

**Comment by mediumTaj** [comment]
Right now they will keep this endpoint open. I will make sure this is the case - they offered to keep a tls 1.0 endpoint for Unity open if needed. If this happens there will be a small update to change the URL of the streaming endpoint again.

**Comment by Marq91** [comment]
hi! in this momment i have the same problem :c 

![watson](https://user-images.githubusercontent.com/20464129/45255697-dfeec680-b360-11e8-8c32-3d420f4b61cf.PNG)

any help is welcome pls

**Comment by mediumTaj** [comment]
What version of Unity are you using and what is you speech to text instance endpoint?

**Comment by Marq91** [comment]
really really sorry, for one reason was copied only some characters of my username, was my fault i need delete my last comment if u think necessary xd
