### ISSUE TITLE
[unity-sdk] websocket-sharp.dll uses the standard namespace 'WebSocket' which can be find in other plugins causing conflicts with code

### ISSUE THREAD

**Issue by prlosana** [watson-developer-cloud/unity-sdk#334]
The websocket-sharp.dll uses the standard namespace 'WebSocket' which can be find in other third party plugins causing conflicts with code.

**Steps to reproduce:**
- Create new project
- Download Watson Unity SDK from Asset store
- Download SmartFox Server SDK from Asset store

**Expected behaviour:** 
- Being able to use Watson plugin with other third party plugins to different services.

**Actual behaviour:**
- Unity shows the following errors:
'The type WebSocket exists in both SmartFox2X.dll and web socket-sharp.dll'
'The type CloseEventArgs exists in both SmartFox2X.dll and web socket-sharp.dll'
'The type MessageEventArgs exists in both SmartFox2X.dll and web socket-sharp.dll'
'The type ErrorEventArgs exists in both SmartFox2X.dll and web socket-sharp.dll'
'The type Opcode exists in both SmartFox2X.dll and web socket-sharp.dll'

**Development Environment:**
- Unity 2017.3.0f3
- Watson Unity SDK 2.0.0
- Windows 10 Enterprise / Mac OS High Sierra

**Comment by NawarRajab** [comment]
I've faced this issue. Fortunately, I have found an alternative to the plugin I'm using. For Watson team, I highly recommend implementing WebSocket under Watson namespace. Check BestHTTP unity plugin implementation, it's very clean.

**Comment by mediumTaj** [comment]
In this PR among other things https://github.com/watson-developer-cloud/unity-sdk/pull/362

**Comment by MirajM** [comment]
Facing the same issue on my project with the SendBird SDK.

Unity shows the following errors:
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name websocket-sharp.dll included for the current platform. Only one assembly with the same name is allowed per platform.

Development Environment:
Unity 2018.3.5f1
IBM Watson Unity SDK -  unity-sdk-3.4.1, unity-sdk-core-0.3.0
SendBird SDK
Windows 7
