### ISSUE TITLE
Utility.cs error with isNetworkError and SendWebRequest

### ISSUE THREAD

**Issue by scottdangelo** [watson-developer-cloud/unity-sdk#335]
Using: Unity 5.6.5f1
           unity-sdk (develop) commit 682c8a0ed6488d7f166ad486b4cbc5e69a996778

I get errors:
Assets/Watson/Scripts/Utilities/Utility.cs(1347,37): error CS1061: Type `UnityEngine.Networking.UnityWebRequest' does not contain a definition for `isNetworkError' and no extension method `isNetworkError' of type `UnityEngine.Networking.UnityWebRequest' could be found. Are you missing an assembly reference?

Also an error using isHTTPError()

Both can be fixed by changing to:
isError()

(see https://answers.unity.com/questions/1389119/a-script-of-my-asset-has-an-error.html)

I also get an error:

Assets/Watson/Scripts/Utilities/Utility.cs(1345,46): error CS1061: Type `UnityEngine.Networking.UnityWebRequest' does not contain a definition for `SendWebRequest' and no extension method `SendWebRequest' of type `UnityEngine.Networking.UnityWebRequest' could be found. Are you missing an assembly reference?

Looks like SendWebRequest is only for >=2017.3
otherwise, we need Send()

**Comment by mediumTaj** [comment]
Platform dependent compilation - Ill need to change a few things around
https://github.com/watson-developer-cloud/unity-sdk/blob/feature-asset-store/Scripts/Utilities/Utility.cs#L1345-L1354
https://github.com/watson-developer-cloud/unity-sdk/blob/feature-asset-store/ThirdParty/FullSerializer/Aot/Editor/fsAotConfigurationEditor.cs#L15-#L26

**Comment by mediumTaj** [comment]
Taking care of this in https://github.com/watson-developer-cloud/unity-sdk/pull/346
