### ISSUE TITLE
[Speech to text] [SpeechToText.OnListenMessage()][ERROR] Error: list index out of range

### ISSUE THREAD

**Issue by redmage0602** [watson-developer-cloud/unity-sdk#336]
In the scene "ExampleStreaming", if I change model from "en-US_BroadbandModel" to "ja-JP_BroadbandModel" in line 94 - SpeechToText.cs, I get this error

![capture](https://user-images.githubusercontent.com/4232198/37445795-7c8a3de4-284c-11e8-99aa-7e0385cf6883.PNG)

**Comment by ARGs-code** [comment]
Same error, but mines coming from Line #791 from SpeechToText.cs
```c#
else if (json.Contains("error"))
                    {
                        string error = (string)json["error"];
                        Log.Error("SpeechToText.OnListenMessage()", "Error: {0}", error);
                        StopListening();
                        if (OnError != null)
                            OnError(error);
                    }
```

**Comment by ARGs-code** [comment]
Providing keywords to _speechToText.Keywords in the ExampleStreaming.cs seems to resolve this issue. However it does occur if no keywords are provided.

**Comment by mediumTaj** [comment]
@redmage0602 @ARGs-code Can you test these changes to see if they fix your issues? https://github.com/watson-developer-cloud/unity-sdk/pull/340

**Comment by redmage0602** [comment]
@mediumTaj I have tested these changes and they work. Thank you very much.

**Comment by kolinz** [comment]
@mediumTaj  
I was also experiencing the same problem, but using branch "336-null-keyword-args" solved it. Thank you very much.
