### ISSUE TITLE
Fix broken ReadMe documentation for the Asset Store plugin

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#341]
Currently we are generating html documentation for the Unity Asset Store version of the SDK by converting markdown readme files to html using Pandoc. This is generating pretty terrible html documentation. For the Unity Asset Store version of the plugin we need better documentation or a link to the latest documentation. There are a few choices here:

- [x] Create a short readme and link to the online documentation in [gh-pages](https://github.com/watson-developer-cloud/unity-sdk/tree/gh-pages).
_or_
~~- [ ] Include the generated gh-pages documentation with the plugin (might be not desirable to have the extra files).~~

Along with this we should
~~- [ ] Remove the current generated confusing html readme and markdown files.~~
- [x] Rename the `Docs` directory (SupportingFiles).
- [x] Add a `Documentation` directory with either html documentation or a link to the online documentation.
- [x] Remove unit tests.
- [x] Resolve warnings.
- [x] Write out steps for preparing a release to the Asset Store.
    - [x] Include step to resolve warnings.

**Comment by kimberlysiva** [comment]
"Write out steps for preparing a release to the Asset Store."

Any docs like this should not be included in the Asset Store release itself. Is it possible to have a folder that doesn't end up in the release?

**Comment by mediumTaj** [comment]
Yeah most likely it will live in the repo [wiki](https://github.com/watson-developer-cloud/unity-sdk/wiki)

**Comment by mediumTaj** [comment]
@kimberlysiva I'm leaning toward having a Documentation directory with a plain text readme linking to the `gh-pages` documentation. What do you think?

**Comment by kimberlysiva** [comment]
@mediumTaj I think that's fine! IIRC Unity does want a bit of offline documentation, but it doesn't have to be much. Maybe the readme would have a few simple steps and then a link to the online docs.

**Comment by mediumTaj** [comment]
Ok that sounds good!

**Comment by kimberlysiva** [comment]
This looks good @mediumTaj! Just tested it with Lexicon, everything still works. The links in the html documentation work, and the plain text readme it definitely helpful.

Do we need the SupportingFiles directory? No big deal if so, was just curious.

**Comment by mediumTaj** [comment]
These changes are in the `asset-store-release` branch. Closing this issue. Feel free to reopen if anything else needs to be addressed.
