### ISSUE TITLE
[Android] Speech-To-Text sometimes not work

### ISSUE THREAD

**Issue by jacktsai526** [watson-developer-cloud/unity-sdk#345]
I am building an android app with the latest Watson-Unity-sdk's Speech-To-Text via Unity. However, it sometimes work and sometimes not. After I dig into the log, it sometimes shows:

[SpeechToText.OnListen()][ERROR] Failed to enter listening state.
and 
[WSConnector][ERROR] Caught WebSocket exception: System.InvalidOperationException: The current state of the connection is not Open.

and sometimes even there is no message sent back but not work either. So I guess the config is not loaded successfully before I call service?

In my project, I do this first:
Credentials credentials = new Credentials(_username, _password, _url);
_speechToText = new SpeechToText(credentials);
Active = true;

then after that, system will call StartRecording() and StopRecording().

I checked some old discussion and also add one line to wait one sec right before SpeechToText(credentials), but did not solve the problem. 

How can I solve this situation? or is there anyway I could make sure config is loaded before calling the service?

Thanks!!

**Comment by mediumTaj** [comment]
Is there a sample project or code you can share? I just published on Android and everything seems to be working as expected.

**Comment by mediumTaj** [comment]
Please reopen this if you are still having issues.

**Comment by McGake** [comment]
I seem to be getting the same problem. Seems to happen about one time in thirty with no particular pattern, So might be a timing issue as suggested above. I do not get the WSConnector error. Requesting reopen bug.

```
[02/20/2019 22:16:44][SpeechToText.OnListen()][ERROR] Failed to enter listening state.
UnityEngine.Debug:LogError(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Debug/DebugReactor.cs:60)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Error(String, String, Object[]) (at Assets/Watson/Scripts/Logging/Logger.cs:279)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:OnListen(AudioData) (at Assets/Watson/Scripts/Services/SpeechToText/v1/SpeechToText.cs:692)
<RecordingHandler>d__22:MoveNext() (at Assets/NewBasicAudioFunc/WatsonStreaming.cs:188)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by mediumTaj** [comment]
Can you post a sample project or code where I can reproduce the error? I will reopen if you can post some code. I just tried Speech to Text on Android today (for https://github.com/watson-developer-cloud/unity-sdk/issues/515) and everything works fine. How long is the socket open before the error?

**Comment by McGake** [comment]
```
[02/20/2019 22:16:33][SpeechToText.CreateListenConnector()][DEBUG] Created listen socket. Model: en-US_BroadbandModel, parsedParams: 
UnityEngine.Debug:Log(Object)
```

If the above represents opening the socket (i don't know much about this) then it looks like it is open for eleven seconds before the error in this particular case. I am basically using a modified version of your example code to trigger recording. But I trigger it in various ways. It would be ugly to post the entire project, so I will try to see if I can narrow it down to something that will reproduce the error regularly. This may take me a couple days.

**Comment by mediumTaj** [comment]
Do you get the error with the unmodified ExampleStreaming scene?

**Comment by McGake** [comment]
Unfortunately, I have run into a different problem that is keeping me from even testing the unmodified ExampleStreaming scene. Sorry about that. If I am ever able to reproduce the issue I will update.

**Comment by Code-Console** [comment]
I solved Error 

I encounter the same issue with Unity 2018.3.14f1.
I just change player settings and then works fine
**file -> build settings - > player settings -> Other Settings
Configuration**

- **Scripting runtime version : _.Net 4x equivalent_**
- **API Compatibility level: .Net 4x**

![update](https://user-images.githubusercontent.com/52966236/74748878-3e76de80-528f-11ea-9594-8133ea20655e.jpg)
