### ISSUE TITLE
[speech-to-text] Service will not accept 8000Hz audio

### ISSUE THREAD

**Issue by ragichug** [watson-developer-cloud/unity-sdk#358]
I am trying to change the frequency of microphone samples that the audioclip sends to cloud server for converting speech to text.
In ExampleStraming.cs, the default frequency is set to 22050Hz and when I tried to set it to 8000Hz, I got an an error in unity saying unable to transcode audio. The code in ExampleStreaming that I attempted to modify is: 
 private int _recordingHZ = 22050;   //tried changing this value to 8000Hz.

Is there any way server can accept the samples created with frequency of 8000, please let me know. I am doing this because my application has a service which is collecting microphone sample at 8Khz separately. One solution I came up was to use same audio recording for both the services. Is there any other alternative I should opt to make both the services run in parallel ? Can I use same microphone device but collect two recordings at same time with different frequency ?

**Comment by mediumTaj** [comment]
@ragichug Which speech model are you using? Can you try using the narrowband model?

```
_speechToTextInstance.RecognizeModel = "en-US_NarrowbandModel";
```

**Comment by mediumTaj** [comment]
@ragichug Closing this - Please reopen if you are still having issues.
