### ISSUE TITLE
Same response after sending message to Watson Assistant

### ISSUE THREAD

**Issue by anthonyherveHCS** [watson-developer-cloud/unity-sdk#361]
Hello, 
If i try to send a message to Watson Assistant using 'Assistant' object, i always get the same response.
When i add a log into Message function (Assistant.cs), the message sent is a serialized fsData string : for example '{"text":{"$content":"My question to Assistant","$type":"System.String"}}'.

If i do the same but using 'Conversation' object, everything is working well (the input message in my log is correct : '{"input": {"text": "My question to Assistant"}}').

Did you notice the same ? 

Thank you

**Comment by mediumTaj** [comment]
@anthonyherveHCS I will take a look at this today - Can you post the code you are using to call Assistant?

**Comment by anthonyherveHCS** [comment]
Thank you. 

I'm using the SDK sample "Example Assistant". 

I tested with the following code : 
        MessageRequest messageRequest = new MessageRequest()
        {
			Input = new Dictionary<string, object>()
			{
				{ "text", "This is my sentence" }
			}
        };
        _service.Message(OnMessage, OnFail, _workspaceId, messageRequest);
        while (!_messageTested)
            yield return null;

**Comment by mediumTaj** [comment]
Your code seems to work for me. Can you email me the cs file you are trying to run? ajiemar at gmail dot com

**Comment by mediumTaj** [comment]
This looks like a deserialization issue in the Message operation. Let me rewrite some of this (this was the first service in the Unity SDK to be generated) and push an update.

**Comment by mediumTaj** [comment]
Fixed in https://github.com/watson-developer-cloud/unity-sdk/pull/363. Waiting for approval and releasing a patch for this.

**Comment by mediumTaj** [comment]
Released Watson Unity SDK v2.2.1. Submitted update to the Unity Asset Store.
