### ISSUE TITLE
[speech-to-text] NullReferenceException when runing ExampleStreaming.cs

### ISSUE THREAD

**Issue by Towerss** [watson-developer-cloud/unity-sdk#374]
- [ ] Steps to reproduce: Followed the tutorials from here: https://assetstore.unity.com/packages/tools/ai/ibm-watson-unity-sdk-108831
Opened an IBM Cloud account and selected desired services including Speech to Text
Got valid credentials
Created a new Unity Project
Included the Watson-unity-SDK in the project as per instructions in the video
Included the credentials and URL in the inspector.
Pressed play.
- [ ] Expected behavior: The audio captured from the microphone should be streamed, recognized, and returned to update the text.
- [ ] Actual behavior: The example crashes producing the following message:
NullReferenceException: Object reference not set to an instance of an object
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText.StartListening (IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.OnRecognize callback, IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.OnRecognizeSpeaker speakerLabelCallback, System.Collections.Generic.Dictionary`2 customData) (at Assets/Watson/Scripts/Services/SpeechToText/v1/SpeechToText.cs:514)
ExampleStreaming.set_Active (Boolean value) (at Assets/Watson/Examples/ServiceExamples/Scripts/ExampleStreaming.cs:80)
ExampleStreaming.Start () (at Assets/Watson/Examples/ServiceExamples/Scripts/ExampleStreaming.cs:56)
- [ ] Unity SDK version: 2.2.1

**Comment by mediumTaj** [comment]
Thanks for pointing this out. I saw it this morning. I have a fix here. You can try to apply it and let me know if it doesn’t fix the issue. 

https://github.com/watson-developer-cloud/unity-sdk/pull/373

**Comment by Towerss** [comment]
@mediumTaj , Indeed that solved the issue. Thank you for your quick reply.

**Comment by ImanCol** [comment]
help 
![image](https://user-images.githubusercontent.com/26169049/41618331-8416effe-73c8-11e8-9dea-ab5010e36d22.png)
