### ISSUE TITLE
Support for tracking IBM Cloud accounts opened resulting from SDK downloads from the Unity Asset Store

### ISSUE THREAD

**Issue by Perefin** [watson-developer-cloud/unity-sdk#378]
Need to add a lightbox that pops up to a user upon download and importation of the Unity Asset version of the Watson Unity SDK.

This lightbox should include copy that informs a user that they need to sign up for an IBM Cloud account and get their account credentials for the necessary services.

The lightbox should then include a tagged link to the IBM Cloud sign up page at console.bluemix.net - please also mask the url and link the words IBM Cloud so there's not confusion with the brand name changing from Bluemix to IBM cloud at the point of click.
 
 This is the tag that should be included:

<?cm_mmc=Display_UnitySDK-_-Developer_Innovation-_-WW_WW-_-unity_sdk_watson_dw > 

See email from Unity to @mediumTaj  for details on exactly how to do this, and contacts within Unity to help.

Also tagging @scottdangelo in case the above explainer helps him and Taj maintain parity in implementation so the results should be statistically similar.

**Comment by mediumTaj** [comment]
Add tag in readme link on asset store branch as well

**Comment by mediumTaj** [comment]
```
<?cm_mmc=Display_UnitySDK-_-Developer_Innovation-_-WW_WW-_-unity_sdk_watson_dw >
```

**Comment by mediumTaj** [comment]
@Perefin This is the link we are changing to. Does this work for you?
```
http://console.bluemix.net/registration?cm_mmc=Display_UnitySDK-_-Developer_Innovation-_-WW_WW-_-unity_sdk_watson_dw
```

**Comment by Perefin** [comment]
Yes, that works for me!

**Comment by mediumTaj** [comment]
I have a version working that pops up a dialog upon SDK installation asking if the user wants to sign up for IBM cloud. Both that link and the link in the readme have the requested query param 

```
cm_mmc=Display_UnitySDK-_-Developer_Innovation-_-WW_WW-_-unity_sdk_watson_dw
```

I need to create a link for the github version of the SDK before I can push this into the asset store.

**Comment by mediumTaj** [comment]
@Perefin Can you test this by downloading this branch into a new Unity project?

https://github.com/watson-developer-cloud/unity-sdk/tree/asset-store-release

**Comment by mediumTaj** [comment]
<img width="883" alt="screen shot 2018-05-16 at 1 17 59 pm" src="https://user-images.githubusercontent.com/4381558/40135793-d0dea9c6-590b-11e8-999c-668e4bf93e00.png">
<img width="768" alt="screen shot 2018-05-16 at 1 18 05 pm" src="https://user-images.githubusercontent.com/4381558/40135797-d359bbe6-590b-11e8-8314-c2f0aa5dd68d.png">
<img width="334" alt="screen shot 2018-05-16 at 1 19 14 pm" src="https://user-images.githubusercontent.com/4381558/40135802-d5fcef80-590b-11e8-9a9c-737deca21e8c.png">

**Comment by Perefin** [comment]
Looks good Taj - unless there is any way to embed the tagged link directly
into the pop up iteslf - perhaps the "ok" button could have an intent to
open the web page via the tagged url?

If not, and so long as the "Sign up for IBM Cloud" link is correctly
tagged, then I say push the update!

Thanks,

M

On Wed, May 16, 2018 at 11:20 AM, Ajiemar Santiago <notifications@github.com

**Comment by mediumTaj** [comment]
Supported in v2.2.3
