### ISSUE TITLE
[Assistant] message not handling simple string

### ISSUE THREAD

**Issue by akeller** [watson-developer-cloud/unity-sdk#383]
![image](https://user-images.githubusercontent.com/1051363/39712797-fdd41c14-51e9-11e8-81f6-588d03e8440a.png)

I changed my previous code using Conversation to Assistant and the simple string use case does not seem to be work in the latest SDK from the GitHub asset store. I can wrap it in a messageRequest and the code will compile just fine.

**Comment by mediumTaj** [comment]
Hi @akeller ,
The Assistant service was partially generated via Swagger rather than hand written like the Conversation service so we will need to send in a MessageRequest instead of a string.
