### ISSUE TITLE
Asset store package handling

### ISSUE THREAD

**Issue by rgjones33** [watson-developer-cloud/unity-sdk#397]
When upgrading in place the asset store upgrade process will not remove any files that were added in previous installs if they no longer exist in the new package.

You need to supply a clean up script if allowing updates in place or recommend to remove the Watson dir first then do a fresh install

- [ ] Unity SDK version - 2.3.0

**Comment by mediumTaj** [comment]
Added a note to delete old versions of the SDK before updating the SDK. This will be live in the description next release.
