### ISSUE TITLE
[ToneAnalyzer] success callback does not correctly populate ToneAnalyzerResponse parm.

### ISSUE THREAD

**Issue by o2deprived** [watson-developer-cloud/unity-sdk#408]
Unity SDK versions 2.3.0 and 2.4.0.
**Expected behavior:** success callback should populate the ToneAnalyzerResponse parm with complete tone analysis data. 

**Actual behavior:** the ToneAnalyzerResponse data structure is not fully populated and returns null ref errors when accessed beyond the document_tone element. The Dictionary parm's "json" key is populated with data, so it is confirmed the account settings are working and data is present.

**Reproduce with SDK example file ExampleToneAnalyzer.cs:** Change success callback method as follows:
```
private void OnGetToneAnalyze(ToneAnalyzerResponse resp, Dictionary<string, object> customData)
{
    Log.Debug("ExampleToneAnalyzer.OnGetToneAnalyze()", "{0}", customData["json"].ToString());
    _analyzeToneTested = true;

    Debug.Log("1" + resp.ToString());
    Debug.Log("2" + resp.document_tone.ToString());
    Debug.Log("3" + resp.document_tone.tone_categories[0].ToString());
}
```

**Output:**
**_json payload:_**
{"document_tone":{"tones":[{"score":0.557493,"tone_id":"joy","tone_name":"Joy"},{"score":0.987645,"tone_id":"analytical","tone_name":"Analytical"}]},"sentences_tone":[{"sentence_id":0,"text":"\"This service enables people to discover and understand, and revise the impact of tone in their content.","tones":[{"score":0.93336,"tone_id":"analytical","tone_name":"Analytical"}]},{"sentence_id":1,"text":"It uses linguistic analysis to detect and interpret emotional, social, and language cues found in text.\"","tones":[{"score":0.929463,"tone_id":"analytical","tone_name":"Analytical"}]}]}

**_Debug log 1:_**
1[ToneAnalyzerResponse: document_tone=[DocumentTone: tone_categories=], sentenceTone=[SentenceTone: sentence_id=0, input_from=0, input_to=0, text="This service enables people to discover and understand, and revise the impact of tone in their content., tone_categories=]]

**_Debug log 2:_**
2[DocumentTone: tone_categories=]

**_Debug log 3:_**
[06/20/2018 16:54:57][Unity][CRITICAL] Unity Exception NullReferenceException: Object reference not set to an instance of an object : ExampleToneAnalyzer.OnGetToneAnalyze (IBM.Watson.DeveloperCloud.Services.ToneAnalyzer.v3.ToneAnalyzerResponse resp, System.Collections.Generic.Dictionary`2 customData) (at Assets/Watson/Examples/ServiceExamples/Scripts/ExampleToneAnalyzer.cs:117)

**Comment by mediumTaj** [comment]
@o2deprived Can you please try this PR and see if it works for you?

https://github.com/watson-developer-cloud/unity-sdk/pull/409

**Comment by o2deprived** [comment]
I pulled 408-tone-analyzer-data-model and the data structure has changed; however, the behavior has not. The new ToneAnalysis type is not populated past the ToneAnalysis.ToneDocument. IOW, the ToneCategories type is null (same as with the previous structure) even tho the json payload delivers the following, indicating successful tone analysis:
```
{"document_tone":{"tones":[{"score":0.557493,"tone_id":"joy","tone_name":"Joy"},{"score":0.987645,"tone_id":"analytical","tone_name":"Analytical"}]},"sentences_tone":[{"sentence_id":0,"text":"\"This service enables people to discover and understand, and revise the impact of tone in their content.","tones":[{"score":0.93336,"tone_id":"analytical","tone_name":"Analytical"}]},{"sentence_id":1,"text":"It uses linguistic analysis to detect and interpret emotional, social, and language cues found in text.\"","tones":[{"score":0.929463,"tone_id":"analytical","tone_name":"Analytical"}]}]}
```

In the ExampleToneAnalyzer.cs file, replacing the OnGetToneAnalyze() method with the following illustrates the problem.

```
    private void OnGetToneAnalyze(ToneAnalysis resp, Dictionary<string, object> customData)
    {
        if(resp == null ) Debug.Log("ToneAnalysis object is null.");
        if(resp.DocumentTone == null ) Debug.Log("DocumentTone object is null.");
        if(resp.DocumentTone.ToneCategories == null ) Debug.Log("ToneCategories object is null.");

        if (resp.DocumentTone.ToneCategories != null)
            foreach (var toneCategory in resp.DocumentTone.ToneCategories)
            {
                foreach (var tone in toneCategory.Tones)
                {
                    Debug.Log("**** RESP TONE ANALYSIS: " + tone.ToneId + " > " + tone.ToneName + " > " + tone.Score);
                }
            }
        else Debug.Log("#### NO ANALYSIS RETURNED...");

        Log.Debug("ExampleToneAnalyzer.OnGetToneAnalyze()", "{0}", customData["json"].ToString());
        _analyzeToneTested = true;
    }
```

**Comment by mediumTaj** [comment]
In the json you list above I don't see `tone_categories`, only `tones`. The service does not seem to be returning `tone_categories`.

```
{
    "document_tone": {
        "tones": [
            {
                "score": 0.557493,
                "tone_id": "joy",
                "tone_name": "Joy"
            },
            {
                "score": 0.987645,
                "tone_id": "analytical",
                "tone_name": "Analytical"
            }
        ]
    },
    "sentences_tone": [
        {
            "sentence_id": 0,
            "text": "\"This service enables people to discover and understand, and revise the impact of tone in their content.",
            "tones": [
                {
                    "score": 0.93336,
                    "tone_id": "analytical",
                    "tone_name": "Analytical"
                }
            ]
        },
        {
            "sentence_id": 1,
            "text": "It uses linguistic analysis to detect and interpret emotional, social, and language cues found in text.\"",
            "tones": [
                {
                    "score": 0.929463,
                    "tone_id": "analytical",
                    "tone_name": "Analytical"
                }
            ]
        }
    ]
}
```

The model for `document_tone` (DocumentAnalysis)
```
DocumentAnalysis {
    tones (Array[ToneScore], optional): 2017-09-21: An array of ToneScore objects that provides the results of the analysis for each qualifying tone of the document. The array includes results for any tone whose score is at least 0.5. The array is empty if no tone has a score that meets this threshold. 2016-05-19: Not returned. ,
    tone_categories (Array[ToneCategory], optional): 2017-09-21: Not returned. 2016-05-19: An array of ToneCategory objects that provides the results of the tone analysis for the full document of the input content. The service returns results only for the tones specified with the tones parameter of the request. ,
    warning (string, optional): 2017-09-21: A warning message if the overall content exceeds 128 KB or contains more than 1000 sentences. The service analyzes only the first 1000 sentences for document-level analysis and the first 100 sentences for sentence-level analysis. 2016-05-19: Not returned.
}
```

**Comment by o2deprived** [comment]
Ahhh, yes. Of course you are correct. ToneAnalysis.DocumentTone.Tones (List<ToneScore>) was not part of the data structure at that level previously, so I was programmed to look for them further down the chain. Sorry about that. Is that expected behavior (that ToneCategories is not returned)?

**Comment by mediumTaj** [comment]
The service changes based on the `versionDate` supplied. In this case, if `versionDate` is between `2016-05-19` and `2017-09-21` `tone_categories` is returned. After `2017-09-21` `tones` is returned. 

Thank you for pointing out the missing `tone` field. It will be added in https://github.com/watson-developer-cloud/unity-sdk/pull/409.

**Comment by o2deprived** [comment]
I see now. You are welcome and thanks for the explanation!
