### ISSUE TITLE
[speech-to-text] Custom corpus error 415

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#414]
We're suddenly receiving the following error when adding training data to a STT custom corpus:

```
URL: https://stream.watsonplatform.net/speech-to-text/api/v1/customizations/ebd02bfd-4708-426b-8a28-43f19bdee156/corpora/Lexicon_Experimental_Intents?allow_overwrite=True, ErrorCode: 415, Error: 415 Unsupported Media Type, Response: {
   "code": 415,
   "code_description": "Unsupported Media Type",
   "error": "Invalid corpus content type. Please use 'text/plain'."
}
```

The fix is switching the content type header in the AddCustomCorpus function from `application/x-www-form-urlencoded` to `text/plain`.

**Comment by mediumTaj** [comment]
Hey Kimberly - We just found out about this yesterday. A breaking change was introduced to the STT service. They may end up reverting the change. I'll update in this issue!

**Comment by mediumTaj** [comment]
This change is being rolled back - probably at some point this afternoon. I'll keep an eye on it and close this issue once it's reverted!

**Comment by mediumTaj** [comment]
@kimberlysiva it looks like they have reverted and tests are passing again. Can you confirm?

**Comment by kimberlysiva** [comment]
Yep, it's working again, thanks!

**Comment by mediumTaj** [comment]
Closed because the service has reverted the breaking change.
