### ISSUE TITLE
Object reference unable to set to an instance of an object &  IAM Authentication.

### ISSUE THREAD

**Issue by tiancaipipi110** [watson-developer-cloud/unity-sdk#428]
I was unable to assign my character object to the CharacterControllerObj. Also, my CharacterControllerObj is under IAM authentication section for some reason. 

Error below:
```
NullReferenceException: Object reference not set to an instance of an object
CharacterController.Update () (at Assets/my scripts/CharacterController.cs:21)
```
Appreciate the help.

**Comment by mediumTaj** [comment]
Hi @tiancaipipi110 what does your `CharacterController` look like? It is probably missing a reference somewhere. What is on line 21 of `CharacterController.cs` and is there a corresponding field in the inspector where you are attaching `CharacterController.cs`?
