### ISSUE TITLE
Watson Unity SDK major release

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#432]
I'm planning to create a generator for the Watson Unity SDK to bring it in line with all of the other fully generated Watson SDKs. This will give us a more up-to-date and accurate SDK generated from the current api definitions. 

Unfortunately this would be a **breaking change** and would result in users needing to migrate their code if they would like to use the latest release.

I'd like to use this issue to list **any breaking change**s we need to make for the next major release so I can add issues to track features.  **Please suggest in the comments and I will add to the list.**

What versions of Unity should we support? Because of support for .NET 4 I'd like to support 2018.2 and higher but I'm open to suggestions.

I'd like to target **Unite Los Angeles 2018** for release.

@kimberlysiva would love to get your input on this!
@mamoonraja I'd love to get you involved here as well if you have any ideas!

## Features
- [x] WatsonResponse - we should return a `WatsonResponse` object containing the `responseCode`, `responseHeaders` and `result`. Should we also include the error here? Should we use a generic here or make `Result` `dynamic`? We should also expose a `GetJsonResponse()` method here. 
    ```
    public class WatsonResponse<T>()
    {
        public int ResponseCode { get; set; }
        public Dictionary<string, string> ResponseHeaders { get; set; }
        public T Result { get; set; }
        // public WatsonError? Error { get; set; }
    }
    ```
- [x] Support `UnityWebRequest` - Not necessarily a breaking change but we should get this into a major release.
- [ ] Unit/integration test and Code Coverage platforms. **Any suggestions here would be greatly appreciated!**
- [x] Automated release using [Semantic Release](https://github.com/semantic-release/semantic-release). Investigate if we can somehow automate publishing to the asset store.
- [ ] Investigate adapters for breaking changes. Can these be generated? Deprecate the old method for one major release.
- [ ] Do not use `CustomData`. We need to find a way to pass in custom request headers.
- [ ] Use Scriptable Objects?

**Comment by kimberlysiva** [comment]
I think this is a great idea! I'll be happy to update Lexicon to utilize this. Would it be possible to keep a branch with the "old" approach active for a little while, in case we have users that need to stick with an older version of Unity? Also just FYI I'm presenting Lexicon at XRSWeek in mid-October, so I'll be looking for a stable release (probably the current SDK) for that.

Including the error in the response makes sense, unless you're sticking with separate success/error callbacks? In that case you might have two classes to avoid null values (e.g. Result). I haven't used `dynamic` much before, but some quick research suggests that it might be less performant, and the lack of type safety might cause more headache than it's worth. If you have a good reason to use it I'm happy to discuss!

**Comment by mediumTaj** [comment]
Yes we will have a separate v3.0 branch that we will merge these changes to as they are generated. Looks like the Unite conference is a a week after the XRS conference so we should be OK there. I'd like to do a pre-release first at least on github to try to get some feedback. 

I was thinking a single callback with `WatsonResponse` might be a little more straightforward but I think I want to try some things out before I commit to anything. As far as `dynamic` goes I use it in the .NET SDK because there are some models that can have additional properties (Context in Assistant for example). I have to think this through a bit more as well though. 

Please let me know if you think of anything else you'd like to add to this list!

**Comment by castana1962** [comment]
Hi mediumTaj
Although I am new to this subject, I think it would be very good if the support is from 2018.2 and higher.
On the other hand, I think that if you could add the Watson Machine Learning Service into of the Watson SDK, it would be great because it would give to Unity developers a tool of comparison of inputs and outputs of data and associating with Dialogue System Unity plugin, the users could add multiple answers to one question into the game by speaking and it would give us the possibility to create Educational games.....
It was used in another AI platform please see here for more info
http://pixelcrushers.com/phpbb/viewtopic.php?f=3&t=848&p=4388#p4388
Hopefully you can understand me
Regards
Alejandro Castan

**Comment by aestiff** [comment]
In what way would this break things? I have an iOS app that I've deployed for research, and the less time I spend screwing around with engineering the app, the better. I'm still annoyed at being surprised by the TLS incident. Would a compiled app be unable to access the web services (STT and TTS) as it has been?

**Comment by mediumTaj** [comment]
@castana1962 Abstraction of Watson Machine Learning into the Watson Unity SDK is not in the roadmap for any of the Watson SDKs. There is a REST api available for the Watson Machine Learning service [here](https://watson-ml-api.mybluemix.net/).

**Comment by mediumTaj** [comment]
@aestiff The method signatures to call Watson Services would change. Generally I am thinking we will move to a single completion handler that returns the response plus error code, headers and error. 

Sorry about the move to TLS 1.2. Unity 2018.2 supports it if switching over is a possibility. Otherwise, the TLS 1.0 endpoint should remain active for the time being.

Nothing would have to change in the compiled app since it's only the SDK that will have a breaking change. When the actual service (STT, TTS) introduces a breaking change the old version should remain compatible for between 6-12 months before users would need to update to use the new version.

**Comment by aestiff** [comment]
So to confirm: client code (e.g. ExampleStreaming) would need to update if it wants to use the v3.0 API, but since the backend services will not be changing, using the older APIs, or any compiled code, would not disrupt any existing applications?
If you're introducing breaking changes, why don't you just mark the old interface as deprecated and create the new interface alongside it?

**Comment by mediumTaj** [comment]
There will be no disruption of service if you are using the old SDK since the Watson APIs are not changing. To use v3.0 of the SDK client code would have to be migrated. I'll have a migration guide ready for this before release. Adapters to avoid breaking changes is something we may be able to do depending on how the SDK is structured. We have them in some of the other SDKs. There are some things that won't translate though. For example the optional CustomData holds custom request headers, response headers and raw response json along with any other data the user wants to pass to the handler.

**Comment by aestiff** [comment]
I don't know the ins and outs of the API/SDK, so maybe this is a dumb thing to say (and if so, feel free to say so), but I don't know why any kind of adapter would be necessary at all. If you need to change a method signature, instead of changing
```
void method(signature){...}
```
to
```
void method(newSignature){...}
```
why not change it to
```
@deprecated
void method(signature){...}

void newMethod(newSignature){...}
```
?

That way you can stop developing `method`, nothing breaks, users get a warning that they need to migrate, and `newMethod` takes care of all of the needed improvements?

**Comment by mediumTaj** [comment]
This is essentially what we will be doing. One of the reasons we are doing this is because we want the Unity SDK to be generated from an API definition file. We will end up with the generated method with the new sig but will attempt to maintain compatibility by having an overload with the old sig (the adapter method) that would be deprecated and (hopefully) simply call the method with the new sig. I'm not 100% sure this will be possible since we are moving to a single completion handler rather than success/fail handlers.

**Comment by mediumTaj** [comment]
For those following this issue I've started refactoring for major release in this branch
```
https://github.com/watson-developer-cloud/unity-sdk/tree/feature-major-release
```
Right now I only have Assistant V2 in there but please have a look. Any feedback is welcome!

Currently the biggest change is changing to a single callback for each method and including the error in the callback.

```cs
_assistant.Message(OnMessage, assistantId, sessionId);

private void OnMessage(WatsonResponse<MessageResponse> response, WatsonError error, Dictionary<string, object> customData)
{
    Log.Debug("ExampleAssistantV2.OnMessage()", "response: {0}", response.Result.Output.Generic[0].Text);
}
```

**Comment by MichealPeters** [comment]
Quick question about Assistant V2  It looks like there is at least one bit of Assistant V2 in WatsonDeveloperCloud (without the dot between Watson and Developer) that's handling the MessageRequest type.  Will that move to do a different class or namesapce during this conversion?

**Comment by mediumTaj** [comment]
These will all be generated so they should be more consistent
