### ISSUE TITLE
[assistant 2.7.0] messageResponse does not contain a definition for 'intents'

### ISSUE THREAD

**Issue by blula** [watson-developer-cloud/unity-sdk#450]
I was accessing assstant's intents in workspace. It's giving me an error:
`Type 'IBM.Watson.DeveloperCloud.Services.Assistant.v1.MessageResponse' does not contain a definition for 'intents' and no extension method 'intents' of type 'IBM.Watson.DeveloperCloud.Services.Assistant.v1.MessageResponse' could be found. Are you missing an assembly reference?
`

Code below:
```
private void OnCONVMessage(object response, Dictionary<string, object> customData)
{

        fsData fsdata = null;
        fsResult r = _serializer.TrySerialize(response.GetType(), response, out fsdata);
        if (!r.Succeeded)
            throw new WatsonException(r.FormattedMessages);


        MessageResponse messageResponse = new MessageResponse();
        object obj = messageResponse;
        r = _serializer.TryDeserialize(fsdata, obj.GetType(), ref obj);
        if (!r.Succeeded)
            throw new WatsonException(r.FormattedMessages);



        object _tempContext = null;
        (response as Dictionary<string, object>).TryGetValue("context", out _tempContext);

        if (_tempContext != null)
            _context = _tempContext as Dictionary<string, object>;
        else
            Log.Debug("ExampleConversation.OnMessage()", "Failed to get context");

        if (response != null && (messageResponse.intents.Length > 0 || messageResponse.entities.Length > 0))
        {
            string intent = messageResponse.intents[0].intent;
            Debug.Log("Intent: " + intent);
            if (intent == "weather")
            {
                Application.OpenURL("www.unity3d.com");
            }
        }
}
```

**Comment by mediumTaj** [comment]
Can you see what `customData.[“json”]` is? Does the response have an intent?

**Comment by blula** [comment]
@mediumTaj  Where do I find customData.[“json”]?  I can't see the response intent, it didn't get that line yet...

**Comment by mediumTaj** [comment]
It’s the other object in the callback. Just  put this on topic the callback and you can see the Jason output. Possibly no intent is returned. 

```
Log.Debug("ExampleConversation.OnMessage()", customData["json"]);
```

**Comment by blula** [comment]
Like this? Sorry, new to programming. 

```  
private void OnCONVMessage(object response, Dictionary<string, object> customData)
    {
        Log.Debug("ExampleConversation.OnCONVMessage()", customData["json"]);
        //  Convert resp to fsdata
        fsData fsdata = null;
```
![2](https://user-images.githubusercontent.com/43283915/45581267-cbcb2d80-b868-11e8-9e7b-736b42cb055a.jpg)

**Comment by mediumTaj** [comment]
Sorry 
```
Log.Debug("ExampleConversation.OnMessage()", customData["json"].ToString());
```

**Comment by blula** [comment]
Same error...
![3](https://user-images.githubusercontent.com/43283915/45582010-80b81700-b876-11e8-9e1c-8bf30c644042.jpg)

**Comment by blula** [comment]
![watson1](https://user-images.githubusercontent.com/43283915/45591696-bcf78000-b927-11e8-94a5-a50f99a077ef.jpg)

**Comment by mediumTaj** [comment]
```
Log.Debug("ExampleConversation.OnCONVMessage()", "response json: {0}", customData["json"].ToString());
```

**Comment by blula** [comment]
@mediumTaj  Thanks. Where do I find customData["json"]?

**Comment by mediumTaj** [comment]
`customData` Is the second parameter in your `OnCONVMessage` callback. `["json"]` is the response json that is added to the `customData` when the response is received.

**Comment by blula** [comment]
So it should be in the Unity console. 
If I add 
```
if (response != null && (messageResponse.intents.Length > 0 || messageResponse.entities.Length > 0))
        {
            string intent = messageResponse.intents[0].intent;
            Debug.Log("Intent: " + intent);
            if (intent == "weather")
            {
                Application.OpenURL("www.unity3d.com");
            }
        }
```
Console will show the `messageResponse does not contain a definition for 'intents'` error, won't let me play before fixing the compiler errors. 
If I comment out that section, console will not show anything.

**Comment by mediumTaj** [comment]
Intents is a generic object. You will need to use TryGetValue like this 
https://github.com/watson-developer-cloud/unity-sdk/blob/develop/Examples/ServiceExamples/Scripts/ExampleConversation.cs#L179

**Comment by blula** [comment]
Even if I do
```
        object tempIntentsObj = null;
        (response as Dictionary<string, object>).TryGetValue("intents", out tempIntentsObj);
```

How do I access the particular intent?

**Comment by blula** [comment]
Like this? It still didn't do it.
```
        object tempIntents = null;
        (response as Dictionary<string, object>).TryGetValue("intents", out tempIntents);
        object _tempIntentsObj = (tempIntents as List<object>)[0];
        string intent = _tempIntentsObj.ToString();
        if (intent == "weather") {
            Application.OpenURL("www.unity3d.com");
        }
```

**Comment by mediumTaj** [comment]
You are getting the `intents` here but need to get the `intent`.

```
// get intents
object tempIntentsObj = null;
(response as Dictionary<string, object>).TryGetValue("intents", out tempIntentsObj);

// get intent
object tempIntentObj = (tempIntentsObj as List<object>)[0];
object tempIntent = null;
(tempIntentObj as Dictionary<string, object>).TryGetValue("intent", out tempIntent);
string intent = tempIntent.ToString();
```

**Comment by blula** [comment]
I c.....
Thank you. 
But it still didn't open the url if I add 
        if (intent == "weather") {
            Application.OpenURL("www.unity3d.com");
        }
Am I doing it wrong?

**Comment by mediumTaj** [comment]
Can you post what is printed out in your console for customData["json"]? How did you train your intents in the service?

**Comment by blula** [comment]
There's nothing printed out for customData['json']... I don't know why. There's a 'try' button on top right to train, the training was successful. I'm wondering if this is because of the dialog.

**Comment by blula** [comment]
`LogSystem.InstallDefaultReactors();`
was already there.  Yes I followed the tutorial to add the intents, intents shouldn't be the problem.

**Comment by mediumTaj** [comment]
Can you set a breakpoint in your handler and use the Unity debugger to see what is in customData?

**Comment by blula** [comment]
![a1](https://user-images.githubusercontent.com/43283915/45659427-712d0e00-bac2-11e8-8065-38074f203fee.jpg)
Is it in the Class view or Solution Explorer? 
![a2](https://user-images.githubusercontent.com/43283915/45659703-bd2c8280-bac3-11e8-9f33-3a6e9416ff4d.jpg)

**Comment by mediumTaj** [comment]
Please see here for how to debug unity using visual studio. 
https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity?view=vs-2017

Closing this issue since it’s not a problem with the SDK. Please join the #unity-sdk channel in the wdc-community slack workspace for support. 
http://wdc-slack-inviter.mybluemix.net/

**Comment by blula** [comment]
What's the point of the customData? My other intents in Watson assistant worked fine. It's only the one that needs to open the url doesn't work.

**Comment by blula** [comment]
https://github.com/IBM/vr-speech-sandbox-cardboard/blob/master/SpeechSandbox/Assets/Scripts/SpeechSandboxStreaming.cs
And how come in this script, they are able to access the intent by
```
if (response != null && (messageResponse.intents.Length > 0 || messageResponse.entities.Length > 0))
        {
            string intent = messageResponse.intents[0].intent;
            Debug.Log("Intent: " + intent);
            if (intent == "weather")
            {
                Application.OpenURL("www.unity3d.com");
            }
        }
```

**Comment by mediumTaj** [comment]
`customData` is a dictionary that holds anything you'd like to send from the call to your callback. Additionally this is used to send custom request headers and will have any response headers and the raw response json in the callback. 

The code above works because of the block immediately above it where they convert the object to a `MessageResponse`

```
//  Convert fsdata to MessageResponse
MessageResponse messageResponse = new MessageResponse();
object obj = messageResponse;
r = _serializer.TryDeserialize(fsdata, obj.GetType(), ref obj);
if (!r.Succeeded)
    throw new WatsonException(r.FormattedMessages);
```

You can implement it this way but you will lose any fields that are not defined in the `MessageResponse` model. The message response is defined as having additional properties in the api spec so we need this to be an object.
