### ISSUE TITLE
[Assistant] WorkspaceExport.Status is always null

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#462]
When calling `Assistant.GetWorkspace()` the returned `WorkspaceExport.Status` field is always null.

For now, we can work around by parsing `customData["json"]` directly.

**Comment by mediumTaj** [comment]
Thanks Kimberly! Fixed in https://github.com/watson-developer-cloud/unity-sdk/commit/971cfc358432a03fcf5e2f6ebd478a592b7b354f

Will close this once the fix has been released
