### ISSUE TITLE
[Assistant] Bool parameters on REST requests not working

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#463]
Testing with the latest Watson in the Asset Store. Assistant V1.

For methods like `ListIntents` bool parameters like `export` and `includeAudit` are ignored. This seems to be a capitalization issue. Here's the generated url:

https://gateway.watsonplatform.net/assistant/api/v1/workspaces/fa52fef4-3974-41c8-ac96-3e0ca435c23f/intents?version=2018-09-20&export=True&include_audit=True

But we need one with lowercase `true` values:

https://gateway.watsonplatform.net/assistant/api/v1/workspaces/fa52fef4-3974-41c8-ac96-3e0ca435c23f/intents?version=2018-09-20&export=true&include_audit=true

**Comment by mediumTaj** [comment]
Thanks Kimberly! This [commit](https://github.com/watson-developer-cloud/unity-sdk/commit/1e6d379d5b4e0cbe3ffe79e5b25665e2110ae29f) sends these query params as lowercase
