### ISSUE TITLE
[Speech to Text] STT not working on HoloLens .NET

### ISSUE THREAD

**Issue by kimberlysiva** [watson-developer-cloud/unity-sdk#468]
Tested with Unity 2017.4.13f1 and 2018.2.6f1. In all setting combinations except 2018.2 IL2CPP, the STT web socket connection immediately fails with the following error:

```
[10/30/2018 14:29:43][WSConnector.SendMessagesAsync()][ERROR] Caught WebSocket exception: System.Exception: Internal server error (500). (Exception from HRESULT: 0x801901F4)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IBM.Watson.DeveloperCloud.Connection.WSConnector.<SendMessagesAsync>d__48.MoveNext()
```

Apps that were working before are also experiencing this error. This suggests something either changed on the STT service side or the HoloLens. I believe my HoloLens auto-updated since it was last working.

**Comment by kimberlysiva** [comment]
Update: tested again on 2017.4 with IL2CPP and it worked this time. So this seems to be a .NET specific issue.

**Comment by davidbaindesign** [comment]
I had this issue today too using unity 2018.1.9f2 with .net in the US south region. I tried upgrading to the 2018.3 beta and using the IAM authentication US East region with .net and had the same issue, works in the editor but not on the hololens. I will try switching to IL2CPP like you did.

**Comment by ebrainlg** [comment]
I have the same issue, have you managed to fix it?

**Comment by davidbaindesign** [comment]
I ended up using Unity 2018.3 with Il2cpp. I had issues with Il2cpp in 2018.1 so I had to upgrade.

**Comment by mamoonraja** [comment]
Looks like Unity version specific issue. @ebrainlg Please feel free to re-open if you are still seeing the issue.
