### ISSUE TITLE
[speech-to-text] 401 unauthorized

### ISSUE THREAD

**Issue by IanPhilips** [watson-developer-cloud/unity-sdk#473]
Using the ExampleSpeechToText Gameobject in the Service Examples scene I input my api key (I've tried two different ones supplied from the speech to text dashboad) and Iam Url supplied by the speech to text dashboard and press play.

I always get an unauthorized exception:
` [11/12/2018 13:53:30][RESTConnector.ProcessRequestQueue()][ERROR] URL: https://stream.watsonplatform.net/speech-to-text/api, ErrorCode: 401, Error: 401 Unauthorized, Response: {"code":401, "error": "Unauthorized"}`

I'm using Unity 2018.3.0b2 and Watson version 2.11.

When I use the curl commands in the tutorial it doesn't give me this unauthorized exception, though it doesn't work to be honest, even with the file provided (audio-file.flac) it complains about the stream being only 38 bytes (which is I believe the number of characters in the path to the audio file)

**Comment by IanPhilips** [comment]
The url I use is: https://stream.watsonplatform.net/speech-to-text/api

**Comment by kimberlysiva** [comment]
I was having the same problem this morning Ian. Try leaving the Iam Url blank, or setting it to "https://iam.bluemix.net/identity/token". Use the stream url in the Service Url field.

@mediumTaj we might want to change the Iam Url label to "Iam Token Url" to avoid confusion.

**Comment by IanPhilips** [comment]
Hooray! thank you! Yes that name is quite confusing, I am shown the Iam key and url one after another on my dashboard, so I assumed the url I am show is the Iam url.

**Comment by mediumTaj** [comment]
You got it, PR here https://github.com/watson-developer-cloud/unity-sdk/pull/476

Closing this issue - please let me know if there's any other issues!

**Comment by albertveomas** [comment]
can i get any tutorial?
