### ISSUE TITLE
cannot access Assistant V2 workspace via Unity SDK

### ISSUE THREAD

**Issue by melyndahoover** [watson-developer-cloud/unity-sdk#474]
Description: Every time I try to connect to my Watson Assistant workspace using the Unity SDK, I get an error that looks like this:

[RESTConnector.ProcessRequestQueue()][ERROR] URL: https://gateway.watsonplatform.net/assistant/api/v2/assistants/5332aca6-7a09-4485-ae17-be60a002ce39/sessions//message?version=2018-11-08, ErrorCode: 404, Error: 404 Not Found, Response: {"error":"Resource not found","code":404}

I've tried deleting and regenerating the credentials. I've triple checked that I'm using all the right credentials from bluemix. I am configured to the US-south so I believe I am using the correct url (https://gateway.watsonplatform.net/assistant/api). This is really baffling because I am not having any problems with speech-to-text or text-to-speech. My only other thought it that it is a problem with the Assistant V2 beta but I don't see an option to create an assistant with V1.

**Comment by mediumTaj** [comment]
@melyndahoover Did you post this question?
https://stackoverflow.com/questions/53252527/cannot-authenticate-watson-assistant-credentials-using-unity-sdk

I responded this morning. For Assistant V2 you will need to create a session before you attempt to message. 

```
void Start()
{
    _assistant.CreateSession(OnCreateSession, OnFail, _assistantId);

}

private void OnCreateSession(SessionResponse response, Dictionary<string, object> customData)
{
    _sessionId = response.SessionId;
    _assistant.Message(OnMessage, OnFail, _assistantId, _sessionId);
}
```

Please let me know if this helps

**Comment by mediumTaj** [comment]
https://github.com/watson-developer-cloud/unity-sdk/pull/475

**Comment by mediumTaj** [comment]
@melyndahoover does creating a session before sending message resolve your issue?

**Comment by mediumTaj** [comment]
@melyndahoover Closing this issue. Please reopen if you are still having problems.
