### ISSUE TITLE
[text-to-speech] Use default URL if none is explicitly supplied

### ISSUE THREAD

**Issue by melyndahoover** [watson-developer-cloud/unity-sdk#483]
Watson Text to Speech example throws error when attempting to synthesize: 

"[RESTConnector.ProcessRequestQueue()][ERROR] URL: /v1/synthesize?accept=audio%2fwav&voice=en-US_AllisonVoice, ErrorCode: 0, Error: Cannot connect to destination host, Response: 
UnityEngine.Debug:LogError(Object)"

**Comment by mediumTaj** [comment]
Hi, did you populate the iamApikey and service url?

**Comment by melyndahoover** [comment]
Yes, I have the correct iamApikey. I left the service url blank since I am in the North American service region. The speech to text and assistant examples work fine, but the text to speech does not.

**Comment by melyndahoover** [comment]
If it helps, these are the two errors I get, in their entirety.

[12/10/2018 20:42:50][RESTConnector.ProcessRequestQueue()][ERROR] URL: /v1/synthesize?accept=audio%2fwav&voice=en-US_AllisonVoice, ErrorCode: 0, Error: Cannot connect to destination host, Response: 
UnityEngine.Debug:LogError(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Debug/DebugReactor.cs:60)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Error(String, String, Object[]) (at Assets/Watson/Scripts/Logging/Logger.cs:279)
IBM.Watson.DeveloperCloud.Connection.<ProcessRequestQueue>c__Iterator0:MoveNext() (at Assets/Watson/Scripts/Connection/RESTConnector.cs:607)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[12/10/2018 20:42:50][ExampleTextToSpeech.OnFail()][ERROR] Error received: URL: /v1/synthesize?accept=audio%2fwav&voice=en-US_AllisonVoice, ErrorCode: 0, Error: Cannot connect to destination host, Response: 
UnityEngine.Debug:LogError(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Debug/DebugReactor.cs:60)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Error(String, String, Object[]) (at Assets/Watson/Scripts/Logging/Logger.cs:279)
TTS:OnFail(Error, Dictionary`2) (at Assets/Scripts/TTS.cs:339)
IBM.Watson.DeveloperCloud.Services.TextToSpeech.v1.TextToSpeech:ToSpeechResponse(Request, Response) (at Assets/Watson/Scripts/Services/TextToSpeech/v1/TextToSpeech.cs:492)
IBM.Watson.DeveloperCloud.Connection.<ProcessRequestQueue>c__Iterator0:MoveNext() (at Assets/Watson/Scripts/Connection/RESTConnector.cs:647)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by mediumTaj** [comment]
I see the issue - we are not using the default URL if no url is supplied. Fix incoming.

**Comment by mediumTaj** [comment]
Can you please try this when you have a chance?

**Comment by melyndahoover** [comment]
Yes it works now! Thank you so much!
