### ISSUE TITLE
Where can I add credentials to the ExampleStreaming script?

### ISSUE THREAD

**Issue by abudriaz** [watson-developer-cloud/unity-sdk#498]
how to add credential in ExampleStreaming script?

**Comment by mediumTaj** [comment]
For example streaming it's best to add credentials to the GameObject in the inspector. Open the ExampleStreaming scene and click on the ExampleStreaming GameObject in the Hierarchy. In the Inspector you should see public fields exposed for IamApikey and ServiceUrl. 

![example-streaming-credentials](https://user-images.githubusercontent.com/4381558/51039763-8b13c480-157b-11e9-8777-c0fb991e88ad.PNG)
