### ISSUE TITLE
Dynamic MessageOutput and missing certificateHandler in Unity 2017.4.18

### ISSUE THREAD

**Issue by 12xq4** [watson-developer-cloud/unity-sdk#499]
Hi, I'd like to ask for some help as I'm encountering an issue while trying to use the Watson SDK in my project.

I have followed through with the steps until I dragged the sdk folder into my Asset folder, then my Unity editor prompted me with three error messages:

- Assets/unity-sdk-develop/Scripts/Connection/RESTConnector.cs(664,35): error CS0246: The type or namespace name `CertificateHandler' could not be found. Are you missing an assembly reference?
- Assets/unity-sdk-develop/Scripts/Connection/RESTConnector.cs(666,33): error CS0115: `IBM.Watson.DeveloperCloud.Connection.AcceptAllCertificates.ValidateCertificate(byte[])' is marked as an override but no suitable method found to override
- Assets/unity-sdk-develop/Scripts/Services/Assistant/v2/Models/MessageOutput.cs(59,16): error CS1980: Dynamic keyword requires `System.Runtime.CompilerServices.DynamicAttribute' to be defined. Are you missing System.Core.dll assembly reference?

I'm using Unity 2017.4.8f1 and the newest Watson sdk (2.12.0) on Mac OS. Any assistance is appreciated.

Thank you.

**Comment by mediumTaj** [comment]
Hi @12xq4 what build target are you set to? Are you using .NET 4.x?
https://github.com/watson-developer-cloud/unity-sdk#configuring-unity

**Comment by 12xq4** [comment]
hi @mediumTaj My build target is set to Mac OS X. I wasn't aware that I need to use .Net 4.x (since I'm using an Unity version earlier than 2018.2) and after I made the switch it still didn't work for me.

**Comment by 12xq4** [comment]
Thanks for your help. After implementing your suggested fix, it's working now (I had switched back to .Net 3.5 for Scripting Runtime Version and .Net 2.0 Subset for API Compatibility Level). 

Just a question though: Would this change hinder the usage of any features? I mainly want to use the speech recognition feature provided by Watson, would omitting Certificate Handler impact this feature?

**Comment by mediumTaj** [comment]
Sending insecurely is only for IBM Cloud Private which is still in development for the Watson Unity SDK. Glad you have it working.

**Comment by mediumTaj** [comment]
Released https://github.com/watson-developer-cloud/unity-sdk/releases/tag/v2.13.0

**Comment by shannon-wu15** [comment]
> Hi, I'd like to ask for some help as I'm encountering an issue while trying to use the Watson SDK in my project.
> 
> I have followed through with the steps until I dragged the sdk folder into my Asset folder, then my Unity editor prompted me with three error messages:
> 
> * Assets/unity-sdk-develop/Scripts/Connection/RESTConnector.cs(664,35): error CS0246: The type or namespace name `CertificateHandler' could not be found. Are you missing an assembly reference?
> * Assets/unity-sdk-develop/Scripts/Connection/RESTConnector.cs(666,33): error CS0115: `IBM.Watson.DeveloperCloud.Connection.AcceptAllCertificates.ValidateCertificate(byte[])' is marked as an override but no suitable method found to override
> * Assets/unity-sdk-develop/Scripts/Services/Assistant/v2/Models/MessageOutput.cs(59,16): error CS1980: Dynamic keyword requires `System.Runtime.CompilerServices.DynamicAttribute' to be defined. Are you missing System.Core.dll assembly reference?
> 
> I'm using Unity 2017.4.8f1 and the newest Watson sdk (2.12.0) on Mac OS. Any assistance is appreciated.
> 
> Thank you.

I got the same issue, but i'm using Unity 2017.4.19. I tried to change the type of UserDefined and the RESTConnector.cs, and it still not work? Could you give any assistance

**Comment by shannon-wu15** [comment]
> I see, I'm able to reproduce the issue. Can you type `UserDefined` in `MessageOutput.cs` as `object` rather than `dynamic`?
> 
> Can you replace your `RESTConnector.cs` with the attached file? I didn't realize this version of UnityWebRequest did not support `certificateHandler`.
> 
> [RESTConnector.zip](https://github.com/watson-developer-cloud/unity-sdk/files/2752243/RESTConnector.zip)
> 
> I will try to get this in the next release

I tried to change the type of UserDefined and the RESTConnector.cs file, and it still not work? Could you give any assistance. BTW, I'm using Unity 2017.4.19
