### ISSUE TITLE
Add missing services

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/unity-sdk#5]
We should have a plan for eventually achieving coverage of the missing services, some of which will require significant implementation work. We'd like to avoid the long-term situation where different SDKs implement different subsets of the Developer Cloud services.

**Comment by mediumTaj** [comment]
Removed 0.3.0 milestone - this will be ongoing

**Comment by germanattanasio** [comment]
What service is missing @mediumTaj ?

**Comment by mediumTaj** [comment]
of all the stuff in the api explorer: `Concept Insights` `Document Conversion` `Retrieve and Rank` `Visual Insights` `AlchemyData News`

**Comment by mediumTaj** [comment]
From WDC page `Concept Expansion` `Concept Insights` `Relationship Extraction`

**Comment by germanattanasio** [comment]
We only need to add:

- [ ] Document Conversion
- [ ] Retrieve and Rank (do we have a Solr library for Unity?)
- [ ] AlchemyData News

**Comment by mediumTaj** [comment]
Looks like there's a .NET client out there. I'll get these done for next sprint.

**Comment by mediumTaj** [comment]
Basic abstractions of all services will be implemented by merge tomorrow. There is still lots of work to handle developer usability issues such as tools, helper functions, widgets, etc. Closing this one for now.
