### ISSUE TITLE
[Assistant v2] context serialization breaks the api

### ISSUE THREAD

**Issue by rdpeake** [watson-developer-cloud/unity-sdk#510]
Using version: 2.13.2
Also borrowed code from 5fc6c2078f727477a51da047a4261ae40a1373b6

I have set up an assistant using the `Customer Care Sample Skill` example skill and have used `Options = new MessageInputOptions() {ReturnContext = true}` to get the context back from the assistant. When you then send a followup message with the returned content - the Global System context contains null userID's  which were not sent to me in the previous interaction, but the API complains that they are not strings.

Further to this, using the linked code from the feature-major-release branch, i was able to get user defined custom variables to work - sending strings... however the demo assistant also includes other json raw types - such as booleans - which were not deserialised.  If you change the user defined dictionary into an 'object' value fsSerializer as type metadata designed to ensure correct deserialisation, but it breaks web api's

The expected behaviour would be the context.global, and context.skills objects are serialised without fs metadata and only include what is required to work

**Comment by mediumTaj** [comment]
Hi @rdpeake ,
Can you provide some sample code so I can try to reproduce the issue? The `feature-major-release` branch is still in development and will consist of mainly generated code. It isn't fully working yet.

**Comment by rdpeake** [comment]
I am aware that the feature-major-release branch is a WIP, however the commit i linked made a change to the existing context code, so i wanted to test if it improved my experience for that situation.

Steps to reproduce error:
Create a new assistant using the `Customer Care Sample Skill` skill
Create new unity project, add watson sdk
Open Service Example sceene
Enable ExampleAssistantV2 object, and disable the others
Copy login info for the assistant made at the start
Run it to ensure the assistant is set up correctly
Change ExampleAssistantV2.cs with the following gist
https://gist.github.com/rdpeake/754128574e6c7513a4b9f3f651c05be7

Note the included comments, and that the first message to include a context object (which was obtained from watson) fails, and that there is no included way to add variables without looking into the WIP branch mentioned, and even when you do that, not all json primitive types are supported, and if you change the dictionary to 'object' value type, FullSerialize adds metadata to the object which is not compatible with the API

**Comment by rdpeake** [comment]
I've added a `UserDefinedConverter.cs` file to the gist i sent which may help (though may be missing features when it comes to nested dictionaries, or lists)
