### ISSUE TITLE
Have to change computer culture to United States to get the right values from Speech to Text service.

### ISSUE THREAD

**Issue by cocapasteque** [watson-developer-cloud/unity-sdk#517]
We banged our heads on the walls trying to find where this issue was..

Basically our company computers are set to German language. The from and to Timestamps and the confidence value were really weird until we realized this afternoon that we should change the culture of the computer to United State to get the correct values.

I tried to parse the double values from SpeechToText.cs  with culture info but it gave me some parsing exception and was not working at all.

On my computer (set to United State) I get values like this for confidence : 
- 0.845
- 0.7585
- 0.5

On my colleague's computer (set to Germany) we get values like this :
- 847
- 758
- 500

**Comment by cocapasteque** [comment]
After a lot of investigation, I got it working by modifying the ParseNumber method in MiniJson.cs

```
            object ParseNumber() {
                string number = NextWord;
                var culture = new CultureInfo("en-US");
                if (number.IndexOf('.') == -1) {
                    long parsedInt;
                    Int64.TryParse(number, out parsedInt);
                    return parsedInt;
                }

                double parsedDouble;
                Double.TryParse(number, NumberStyles.Any, culture, out parsedDouble);
                return parsedDouble;
            }
```

**Comment by mediumTaj** [comment]
Reopening to look at this in the SDK

**Comment by mediumTaj** [comment]
As I understand it this issue is a limitation of an external dependency. Closing this issue but thanks for pointing out the fix for other users.

**Comment by mediumTaj** [comment]
This issue seems to be popping up frequently the past few days. @cocapasteque would you be able to put in a PR to the Watson Unity SDK with this change to MiniJson.cs?

**Comment by cocapasteque** [comment]
Yes I'm gonna do that now :)

**Comment by mediumTaj** [comment]
fixed with https://github.com/watson-developer-cloud/unity-sdk/pull/520
