### ISSUE TITLE
Keywords feature missing

### ISSUE THREAD

**Issue by zkaiser** [watson-developer-cloud/unity-sdk#519]
[speech-to-text][v2.15.0][Unity 2018.2.0f2] Including keywords to be detected an error occurs : "Failed to enter listening state", and everything is ok if keywords not set

**Comment by mediumTaj** [comment]
Hi @zkaiser . Can you post sample code you are using? Did you set `KeywordsThreshold`?

```
_service.Keywords = new string[] { "IBM", "Watson"};
_service.KeywordsThreshold = 0.5f;
```

Keywords is working in the ExampleStreaming scene if you add these two lines to the `Active` setter. If the threshold wasn't set you would see the error:
>Error: keywords_threshold must be set if keywords list is not empty.

**Comment by zkaiser** [comment]
Hi mediumTaj,

I´m using SpeechSandboxStreaming example with this:

 _speechToText.RecognizeModel = "es-ES_NarrowbandModel";//para que reconozca en español -- es-ES_NarrowbandModel -- es-ES_BroadbandModel

List<string> keywords = new List<string>();
keywords.Add("ayuda");
keywords.Add("buscandome");
_speechToText.KeywordsThreshold = 0.1f;
_speechToText.StreamMultipart = false;
_speechToText.Keywords = keywords.ToArray();
_speechToText.InactivityTimeout = 600;
_speechToText.DetectSilence = true;
_speechToText.EnableWordConfidence = true;
_speechToText.EnableTimestamps = true;
_speechToText.SilenceThreshold = 0.01f;
_speechToText.MaxAlternatives = 7;//0
_speechToText.WordAlternativesThreshold = 0.2f;
_speechToText.EnableInterimResults = true;
_speechToText.OnError = OnError;
_speechToText.ProfanityFilter = false;
_speechToText.SmartFormatting = true;
_speechToText.SpeakerLabels = false;
_speechToText.WordAlternativesThreshold = null;*/
_speechToText.StartListening(OnRecognize, OnRecognizeSpeaker);


And I´m getting the error I posted before.
I´m getting the same error when trying ExampleStreaming.unity scene adding keywords (with threshold, of course), and the two scenes works ok without keywords....


When running ExampleSpeechToText example I´m getting following error:


https://gateway-lon.watsonplatform.net/speech-to-text/api/v1/recognize?inactivity_timeout=120&keywords=speech&keywords_threshold=0,1&max_alternatives=1&model=en-US_BroadbandModel&profanity_filter=true&smart_formatting=false&speaker_labels=false&timestamps=false&word_confidence=false, ErrorCode: 400, Error: Generic/unknown HTTP error, Response: {
   "code_description": "Bad Request", 
   "code": 400, 
   "error": "Expected float for parameter \"keywords_threshold\", value \"0,1\" cannot be parsed to float."
}

Using following parameters:
List<string> keywords = new List<string>();
        keywords.Add("speech");
        _service.KeywordsThreshold = 0.1f;
        _service.InactivityTimeout = 120;
        _service.StreamMultipart = false;
        _service.Keywords = keywords.ToArray();
        _service.Recognize(HandleOnRecognize, OnFail, _acousticResourceData, _acousticResourceMimeType);



Is there some version of IBM SDK or Unity SDK do you know where this is working??

**Comment by mediumTaj** [comment]
@zkaiser Can you take a look at this issue https://github.com/watson-developer-cloud/unity-sdk/issues/517

It looks like we need to make an update to an external dependency to specify culture in a serialization script.

**Comment by cocapasteque** [comment]
Yes I'm gonna do that now :)

**Comment by mediumTaj** [comment]
This should be fixed with https://github.com/watson-developer-cloud/unity-sdk/pull/520. Please comment if you have any more issues with this.
