### ISSUE TITLE
Visual Recognition Classify post image failing. Error code 400

### ISSUE THREAD

**Issue by k2nt** [watson-developer-cloud/unity-sdk#522]
I am trying to use the Visual Recognition code in Unity. For some reason, when I played the ExampleVisualRecognition scene, I have the following error:

<img width="1117" alt="screen shot 2019-02-23 at 17 06 24" src="https://user-images.githubusercontent.com/19535716/53292356-290bc900-378f-11e9-8844-b2f3375939e0.png">

I haven't programmed anything. I simply added my service url, version date, and IAM API key. A thing to note is that when I ran the ExampleVisualRecognition scene after I commented out the Classify post image code snippet in the Example Visual Recognition script, the code ran without problem.

I hope someone can help me with my issue. Thank you.

**Comment by mediumTaj** [comment]
@k2nt What version of Unity and the Watson SDK are you using?

**Comment by k2nt** [comment]
I am using the latest version of Unity and Watson SDK

**Comment by mediumTaj** [comment]
Thanks for the issue - I'm able to reproduce. Let me check with the service team. I don't see any `vmodel-id` header being sent.

**Comment by mediumTaj** [comment]
I see... this is an error in the example script. We have no value for `classifier_id` unless a classifier is trained. I will fix this but you can remove `_classifierID` from the `classifierIDs` array in line 155 of ExampleVisualRecognition.cs.

**Comment by mediumTaj** [comment]
Addressed in https://github.com/watson-developer-cloud/unity-sdk/pull/523
