### ISSUE TITLE
[speech-to-text] RD_ERROR

### ISSUE THREAD

**Issue by mundinbass** [watson-developer-cloud/unity-sdk#527]
When opening up a scene very close to the examplescene for speech to text I am getting this error: 

[03/05/2019 08:00:55][SpeechToText.OnListenMessage()][ERROR] Error: <2019-03-05 08:00:55,095 api/src/rapi_common.cc:127>	RD_ERROR	RAPI: "RReco" -> "settings" -> "nbest_size" -> Integer 0 is lower than 1.

UnityEngine.Debug:LogError(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Debug/DebugReactor.cs:60)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/Watson/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Error(String, String, Object[]) (at Assets/Watson/Scripts/Logging/Logger.cs:279)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:OnListenMessage(Message) (at Assets/Watson/Scripts/Services/SpeechToText/v1/SpeechToText.cs:931)
IBM.Watson.DeveloperCloud.Connection.<ProcessReceiveQueue>d__47:MoveNext() (at Assets/Watson/Scripts/Connection/WSConnector.cs:400)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/Watson/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

I expect it to start listening and obtain my voice. It was working yesterday with 2018.3.6 on Linux but today I opened up the project and it was not working. I updated to 2018.3.7 and I'm getting the same error.  You can clone my project from here:
git clone https://mundinbass@bitbucket.org/mundinbass/speech-project.git

I'm honestly not sure what version of the SDK I have but I cloned it from the repo March 3.

EDIT: A fact I stated was incorrect. SpeechToText.cs is stock as it came in the SDK. The rest of the issue is correct

**Comment by anthonyherveHCS** [comment]
Hello, 
I notice exactly the same error since this morning!
I didn't make any changes in my project.
My Watson Unity SDK version : 2.15.0
Thank you

**Comment by anthonyherveHCS** [comment]
I just tested with Watson Unity SDK 2.15.2 and the issue is the same.
Thx

**Comment by kireyzambon** [comment]
hello i have the same error. i'm using lite tier Dallas intance

[03/05/2019 15:35:15][SpeechToText.OnListenMessage()][ERROR] Error: <2019-03-05 15:35:13,893 api/src/rapi_common.cc:127>	RD_ERROR	RAPI: "RReco" -> "settings" -> "nbest_size" -> Integer 0 is lower than 1.

UnityEngine.Debug:LogError(Object)
IBM.Watson.DeveloperCloud.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/unity-sdk/Scripts/Debug/DebugReactor.cs:60)
IBM.Watson.DeveloperCloud.Logging.LogSystem:ProcessLog(LogRecord) (at Assets/unity-sdk/Scripts/Logging/Logger.cs:206)
IBM.Watson.DeveloperCloud.Logging.Log:Error(String, String, Object[]) (at Assets/unity-sdk/Scripts/Logging/Logger.cs:279)
IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText:OnListenMessage(Message) (at Assets/unity-sdk/Scripts/Services/SpeechToText/v1/SpeechToText.cs:931)
IBM.Watson.DeveloperCloud.Connection.<ProcessReceiveQueue>d__47:MoveNext() (at Assets/unity-sdk/Scripts/Connection/WSConnector.cs:400)
IBM.Watson.DeveloperCloud.Utilities.Routine:MoveNext() (at Assets/unity-sdk/Scripts/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by mediumTaj** [comment]
Were projects changed at all? or the error just started happening out of the blue?

**Comment by mundinbass** [comment]
Literally out of the blue for me; I saved it (its even pushed to my repository) and it was working. Opened it up to test for my presentation and I'm getting this error.
Also, it doesn't always give this error... Sometimes it shows no errors but it doesn't pick up the microphone and times out. All with absolutely no changes

**Comment by kireyzambon** [comment]
hello @mediumTaj i'm using this sdk for the first time.

i'm trying to follow this tutorial:
https://developer.ibm.com/recipes/tutorials/create-a-3d-digital-human-with-ibm-watson-assistant-and-unity3d/#r_overview

and this example code
https://github.com/YnotZer0/unity3d_watsonSdk/blob/master/Watson_newServices.cs

tts works
stt close the connection

**Comment by mediumTaj** [comment]
This is a bug in the service. They are working on it but currently the workaround is to set `MaxAlternatives` to anything above `0`

```
_service.MaxAlternatives = 1;
```

@kireyzambon @mundinbass @anthonyherveHCS Please let me know if this workaround fixes the issue for now

**Comment by mundinbass** [comment]
I tried putting this line of code in the CreateService() and then the Start() function in the ExampleStreaming class and it only serves to give me the same error more reliably. 

Is this where I should set the maxAlternatives for the service? or where?

**Comment by davidjbain** [comment]
I think you have to put it after that. I put mine in the "set" part of the Active Boolean.  
It works for me I had the same error, but it seems to create another problem, I don't get the final result as often for longer phrases.

**Comment by mundinbass** [comment]
> I think you have to put it after that. I put mine in the "set" part of the Active Boolean.
> It works for me I had the same error, but it seems to create another problem, I don't get the final result as often for longer phrases.
> 

Yes, my bad, I should have seen the Active Bool. I can confirm settings it to 1 does work. I am also experiencing not getting the final result as much.
@davidjbain @mediumTaj

**Comment by mcarman8** [comment]
I can confirm setting to 1 works as well. However, I then seem to be getting an error in converting the json data every 5 seconds or so. Attached is a file with the text of the two errors it generates. Is this related, or should it be in its own issue?
[watson_unity_errors.txt](https://github.com/watson-developer-cloud/unity-sdk/files/2934710/watson_unity_errors.txt)

**Comment by kireyzambon** [comment]
thanks it works

**Comment by anthonyherveHCS** [comment]
@mediumTaj @mcarman8  It seems that when an alternative timestamp is an integer, the parse fails to convert in double.
Thx

**Comment by mediumTaj** [comment]
Can you check out this PR? It should address the casting issues for WordConfidence https://github.com/watson-developer-cloud/unity-sdk/pull/528

**Comment by Chapmania** [comment]
> This is a bug in the service. They are working on it but currently the workaround is to set `MaxAlternatives` to anything above `0`
> 
> ```
> _service.MaxAlternatives = 1;
> ```
> @kireyzambon @mundinbass @anthonyherveHCS Please let me know if this workaround fixes the issue for now

I tried the workaround, but it didn't work. Thanks for your efforts in fixing this Taj.
