### ISSUE TITLE
[speech-to-text] Null word_alternatives and double parsing on time stamps

### ISSUE THREAD

**Issue by LDanderz** [watson-developer-cloud/unity-sdk#532]
While using speech-to-text, res.word_alternatives always come back null, the speech recognition event never seems to come back with a key of "word_alternatives". Also on speech-to-text, parsing to double on timestamp values has the same issue as it did on confidence values (just rare that a time stamp will start/finish exactly on an integer value).

Im using the latest sdk version v2.15.3.

**Comment by McGake** [comment]
Confirming the timestamp issue. Just ran into it. Also the same cast issue with ialternative["confidence"] in the same function.

**Comment by mediumTaj** [comment]
Looking at converting all of these values to strings and then converting to doubles. For the `word_alternatives` did you set the `WordAlternativesThreshold`?

```
_service.WordAlternativesThreshold = 0.5f;
```

**Comment by mediumTaj** [comment]
Can you guys try out this PR and see if you have any more issues with double parsing? https://github.com/watson-developer-cloud/unity-sdk/pull/533

**Comment by LDanderz** [comment]
I did go through and fix all the casting myself. As to the null word alternatives, I did have the threshold set but it seems IBM may have done something their end as it all words as it should now. Many thanks for the replies.
