### ISSUE TITLE
[SpeechToText] Websocket disconnecting

### ISSUE THREAD

**Issue by shramikdalvi** [watson-developer-cloud/unity-sdk#536]
**Overview**
Speech to text service isn't working, please check the attached screen shot 

 **Expected behavior**
to work fine

 **Actual behavior**
didn't work

 **How to reproduce**
i am using Watson Unity sdk v2.15.4

 **Screenshots**
_If applicable, add screenshots to help explain your problem._

 **SDK Version**
v2.15.4

![watsonSTT](https://user-images.githubusercontent.com/35919083/54434407-33006680-4754-11e9-8bef-c2da5798f728.png)

**Comment by mediumTaj** [comment]
Let me take a look at this today.

**Comment by mediumTaj** [comment]
I've tested the scene with a speech to text instance in London and it seems to be working. Have you set the Scripting Runtime Version to .NET 4.x in the build settings?

https://github.com/watson-developer-cloud/unity-sdk#configuring-unity

The API Compatibility Level should also be set to .NET 4.x

**Comment by shramikdalvi** [comment]
Hi, 
As you said i tested with API Compatibility Level .NET 4.x, and it seems to be working fine though there is a bit latency.  
It would be great if you can add (The API Compatibility Level should also be set to .NET 4.x) to the documentation as its not there.
thanks for the support, appreciated !
