### ISSUE TITLE
[speech to text] OnListenClosed(), State = DISCONNECTED

### ISSUE THREAD

**Issue by wearywitness** [watson-developer-cloud/unity-sdk#541]
![Screenshot](https://user-images.githubusercontent.com/9262986/54823654-2b3f4580-4cb1-11e9-917b-ec24ce33ff1c.png)

Hi, 
Speech to Text Streaming has been working fine so far, but I get this error out of the blue over the past two days.
I have the correct IAM authentication. My runtime version and API compatibility is at 4.x.

Don't know why this is happening. Please help me out.

Thanks in advance!

**Comment by mediumTaj** [comment]
What version of the SDK are you using? Is this happening consistently? I just tried with a service in london and had no issues connecting. It's possible that this is a temporary service issue.

**Comment by wearywitness** [comment]
You're right... I hadn't updated to the latest version!
Working perfectly now... Thanks!
