### ISSUE TITLE
[speech to text] OnListenClosed(), state = Disconnected

### ISSUE THREAD

**Issue by mcarman8** [watson-developer-cloud/unity-sdk#542]
**Overview**
Getting OnListenClosed immediately upon creation with example scene and valid Credentials

 **Expected behavior**
I expected the speech to text algorithm to continue.

 **Actual behavior**
Immediately after starting the service, the service exits.

 **How to reproduce**
Using Unity 2017.4.24f1 and unity-sdk version 2.15.4. Using Script runtime version 3.5 yields this error. Using Script runtime version 4.6 (listed as experimental on 2017.4) yields build error namespace name 'CertificateHandler' cannot be found, and ValidCertificate(byte[]) is marked as override but but no suitable method is found to override.

 **Screenshots**
![image](https://user-images.githubusercontent.com/19908759/54875020-0cce6c80-4dcd-11e9-960b-d49762a77e5a.png)
![image](https://user-images.githubusercontent.com/19908759/54875041-65056e80-4dcd-11e9-882d-5a827816372f.png)

 **SDK Version**
2.15.4

 **Additional information:**
- OS: Windows and Mac

**Comment by mcarman8** [comment]
My bad, Apparently the Washington D.C. Node is not working, and creating a new key switching to Dallas fixed my problem, even though the Unity status page says everything is working.

**Comment by mediumTaj** [comment]
Every region except for Dallas is on TLS 1.2. To use Speech to Text in the other regions you will need to change your build settings to use .NET 4.x equivalent (both Scripting Runtime Version and API Compatibility Level).

https://github.com/watson-developer-cloud/unity-sdk#configuring-unity
