### ISSUE TITLE
Failed to open listening state

### ISSUE THREAD

**Issue by ckowall** [watson-developer-cloud/unity-sdk#557]
ExampleStreaming throws this 
[04/08/2019 22:10:00][SpeechToText.OnListen()][ERROR] Failed to enter listening state.
UnityEngine.Debug:LogError(Object)
IBM.Cloud.SDK.Debug.DebugReactor:ProcessLog(LogRecord) (at C:/Users/Correy Kowall/Desktop/unity/Beacon/IBM/Assets/unity-sdk-core-0.1.0/unity-sdk-core-0.1.0/Debug/DebugReactor.cs:60)
IBM.Cloud.SDK.LogSystem:ProcessLog(LogRecord) (at C:/Users/Correy Kowall/Desktop/unity/Beacon/IBM/Assets/unity-sdk-core-0.1.0/unity-sdk-core-0.1.0/Logging/Logger.cs:207)
IBM.Cloud.SDK.Log:Error(String, String, Object[]) (at C:/Users/Correy Kowall/Desktop/unity/Beacon/IBM/Assets/unity-sdk-core-0.1.0/unity-sdk-core-0.1.0/Logging/Logger.cs:280)
IBM.Watson.SpeechToText.V1.SpeechToTextService:OnListen(AudioData) (at C:/Users/Correy Kowall/Desktop/unity/Beacon/IBM/Assets/unity-sdk-3.1.0/unity-sdk-3.1.0/Scripts/Services/SpeechToText/V1/SpeechToTextServiceExtension.cs:361)
IBM.Watsson.Examples.<RecordingHandler>d__18:MoveNext() (at C:/Users/Correy Kowall/Desktop/unity/Beacon/IBM/Assets/unity-sdk-3.1.0/unity-sdk-3.1.0/Examples/ExampleStreaming.cs:189)
IBM.Cloud.SDK.Utilities.Routine:MoveNext() (at C:/Users/Correy Kowall/Desktop/unity/Beacon/IBM/Assets/unity-sdk-core-0.1.0/unity-sdk-core-0.1.0/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

I am running Unity 2018,3,8f1 for PC Standalone

The bug is intermittent, seemingly unpredictable.  The example scene does however transcribe some speech to text.  It always ends the process with that error.

**Comment by sebastienspas** [comment]
I encounter the same issue with Unity 2018.3.12f1 and Unity 2018.3.14f1.
Is there any way to try catch this error and avoid the process to be stopped ?

**Comment by mamoonraja** [comment]
@sebastienspas Thanks for the update, can you provide more info about your scenario, I was not able to re-create the issue.

**Comment by daniellovell** [comment]
@mamoonraja I can corroborate these reports of "Failed to enter listening state" on Unity 2018.3.5f1 by simply running the (unchanged, current release) of ExampleStreaming scene and speaking in short bursts for 30-60s.

However! It seems like the DetectSilence flag is connected to this issue as setting it to false will prevent this error. While I don't much about the Watson API, I suspect the issue might be upstream where the service times out when given audio signal that has been filtered for silence.

**Comment by Code-Console** [comment]
I solved Error 

I encounter the same issue with Unity 2018.3.14f1.
I just change player settings and then works fine
file -> build settings - > player settings -> Other Settings
Configuration
Scripting runtime version : .Net 4x equivalent
API Compatibility level: .Net 4x

![update](https://user-images.githubusercontent.com/52966236/74748814-23a46a00-528f-11ea-9ded-ff08074a5f3e.jpg)
