### ISSUE TITLE
[ICP] Do not yield for token data if connecting to an ICP service

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#558]
When authenticating using IAM Apikey we need to yield for the IAM service to return tokenData before creating the service. When authenticating using an `icp-` apikey we do basicauth behind the scenes. We need to clarify in documentation that the Unity SDK supports ICP (but without Proxy) and that when authenticating we don't need to yield for tokenData.

**Comment by mamoonraja** [comment]
Will not be valid after v4.
