### ISSUE TITLE
[text to speech] Add TextToSpeech example

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#562]
#### Context
@akeller created a TextToSpeech example for the Unity SDK
https://gist.github.com/akeller/4e16cd9e0154af55133678e7ca83c9d9

It would be great to get this into the SDK as an example. Thanks @akeller !

#### Acceptance criteria
- [ ] Standardize the above gist and add to the examples in the SDK

**Comment by mamoonraja** [comment]
still valid.

**Comment by mhadji05** [comment]
I m trying to make Text To Speech but i fail. Any help please?

**Comment by GwilymNewton** [comment]
Still an issue for me, trying to work out how to use the service by reading your test scripts. 

Cant currently get it working seeing a `403 forbidden` even though the service gets created with an authenticated.

**Comment by mamoonraja** [comment]
@GwilymNewton I have created a pr to showcase an example for Text to Speech, please checkout https://github.com/watson-developer-cloud/unity-sdk/pull/616. Let me know if that helps.
