### ISSUE TITLE
[speech to text] Add steps to enable microphone for Mojave

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#563]
#### Context
Updating MacOS to Mojave may disable microphone for Unity. We should add steps to enable the microphone for SDK users who were having trouble.

https://support.apple.com/en-us/HT209175

#### Acceptance criteria
- [ ] Add section in readme pointing to the above article if they have trouble with their microphone on OSX

**Comment by mamoonraja** [comment]
Instructions added in the readme.
