### ISSUE TITLE
A small issue with line endings on Mac

### ISSUE THREAD

**Issue by scprotz** [watson-developer-cloud/unity-sdk#565]
I loaded the most recent version into Unity 2017.3.1f1 on my Mac (v3.1.0 and v0.2.0).  There were a few files that show as having Windows line endings and Unity complains this can throw off the debug messages.  I manually changed them on my system when opening them with the mono editor, but probably should be consistent, as most files using all the same line endings.

**Comment by mamoonraja** [comment]
Hi! Thanks for opening the issue, can you please provide more info about the files you noticed the issue for?
