### ISSUE TITLE
The type or namespace name 'Cloud' does not exist in the namespace 'IBM' [Unity 2019.1]

### ISSUE THREAD

**Issue by jBachalo** [watson-developer-cloud/unity-sdk#567]
Simply adding the SDK to an empty Unity 2019.1 project and getting several compile errors in the editor

Assets/unity-sdk-master/Common/Common.cs(18,11): error CS0234: The type or namespace name 'Cloud' does not exist in the namespace 'IBM' (are you missing an assembly reference?)

**Comment by mediumTaj** [comment]
Did you also add the [`unity-sdk-core`](https://github.com/ibm/unity-sdk-core) repo to your Assets directory?
https://github.com/watson-developer-cloud/unity-sdk#getting-the-watson-sdk-and-adding-it-to-unity

**Comment by jBachalo** [comment]
Thanks.
