### ISSUE TITLE
Assembly has reference to non-existent assembly 'IBM.Cloud.SDK'  [unity 2018.3]

### ISSUE THREAD

**Issue by jBachalo** [watson-developer-cloud/unity-sdk#568]
So simply adding SDK to empty 2018.3 project. Much better that with 2019.1 however still get 2 compile errors in editor

Assembly has reference to non-existent assembly 'IBM.Cloud.SDK' (Assets/watson/Tests/IBM.Watson.Tests.asmdef)

Assembly has reference to non-existent assembly 'IBM.Cloud.SDK' (Assets/watson/WatsonUnitySDK.asmdef)

**Comment by mediumTaj** [comment]
Did you also add the `unity-sdk-core` repo to your Assets directory?
https://github.com/watson-developer-cloud/unity-sdk#getting-the-watson-sdk-and-adding-it-to-unity

**Comment by jBachalo** [comment]
Thanks for quick reply. Yes read that on the github page. Was following the youtube tutorial and that might have been omitted.
https://www.youtube.com/watch?v=woKMumx3TcY&list=PLZDyxLlNKRY9b2vurEhkSoNWZN5c5l4Nr&index=4

**Comment by AlexNiculae** [comment]
Hello,

I have used the latest releases of watson unity-sdk (4.1.1) and unity-sdk-core (1.2.0) and I get this error:
`Assembly has reference to non-existent assembly 'UnityEngine.TestRunner' (Assets/Scenes/unity-sdk-core-1.2.0/Tests/IBM.Cloud.SDK.Tests.asmdef)`

I have also configured Unity as specified in the unity-sdk README.

**Comment by mamoonraja** [comment]
Hi @AlexNiculae, thanks for bringing it up, which version of unity are you using?

**Comment by AlexNiculae** [comment]
I am using Unity 2018.4.12f1 Personal.

**Comment by sanky369** [comment]
Has this issue resolved? I am getting the same error. Unity 2018.4.0f1 and latest watson SDK from github.
Assembly has reference to non-existent assembly 'UnityEngine.TestRunner' (Assets/Scenes/unity-sdk-core-1.2.0/Tests/IBM.Cloud.SDK.Tests.asmdef)

**Comment by kuravista** [comment]
I am getting same problem too.. any suggestion ?
- SDK v4.8.0
- unity-sdk-core v1.2.1
- unity 2018.3.3f1
