### ISSUE TITLE
NullReferenceException with Example Streaming

### ISSUE THREAD

**Issue by jBachalo** [watson-developer-cloud/unity-sdk#574]
Hi
Occasionally am getting the following error. Although it doesn't break the application thought I should share.

> [Unity][CRITICAL] Unity Exception NullReferenceException: Object reference not set to an instance of an object : IBM.Cloud.SDK.AudioClipUtil.GetL16 (UnityEngine.AudioClip clip) (at Assets/IBMSdkCore/Utilities/AudioClipUtil.cs:96)
> IBM.Watson.SpeechToText.V1.SpeechToTextService+<KeepAlive>d__224.MoveNext () (at Assets/Watson/Scripts/Services/SpeechToText/V1/SpeechToTextServiceExtension.cs:522)
> IBM.Cloud.SDK.Utilities.Runnable+Routine.MoveNext () (at Assets/IBMSdkCore/Utilities/Runnable.cs:131)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
> 
> UnityEngine.Debug:LogError(Object)
> IBM.Cloud.SDK.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/IBMSdkCore/Debug/DebugReactor.cs:60)
> IBM.Cloud.SDK.LogSystem:ProcessLog(LogRecord) (at Assets/IBMSdkCore/Logging/Logger.cs:207)
> IBM.Cloud.SDK.Log:Critical(String, String, Object[]) (at Assets/IBMSdkCore/Logging/Logger.cs:295)
> IBM.Cloud.SDK.LogSystem:UnityLogCallback(String, String, LogType) (at Assets/IBMSdkCore/Logging/Logger.cs:168)
> UnityEngine.Application:CallLogCallback(String, String, LogType, Boolean)
>

**Comment by mamoonraja** [comment]
Thanks for opening the issue, I have not seen it before but will take a look at it.

**Comment by mamoonraja** [comment]
Should've been fixed in https://github.com/watson-developer-cloud/unity-sdk/pull/602. Please re-open if you see the issue again.
