### ISSUE TITLE
Modifying SDK to support a Custom Language Model

### ISSUE THREAD

**Issue by jBachalo** [watson-developer-cloud/unity-sdk#575]
I realize I should not be asking questions here, however, this is directly related to the Unity SDK so I believe it is still appropriate to ask here.

I want to improve the accuracy of the Speech to Text by creating a Custom language Model.

https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-languageCreate#createModel-language

Is this possible by modifying the existing UnitySDK?
If so is there any documentation on how to accomplish this?

**Comment by mamoonraja** [comment]
Hi @jBachalo, thanks for opening the issue. You can create custom models using the SDK, check the method [CreateLanguageModel](https://github.com/watson-developer-cloud/unity-sdk/blob/master/Scripts/Services/SpeechToText/V1/SpeechToTextService.cs#L1445) out.

**Comment by jBachalo** [comment]
Thanks! Yes documentation is quite good. One more step and I am good to go.

I've
-created a custom model
-created a grammar file
-uploaded and trained my new grammar file
-checked status of new model to confirm it is ok

According to documentation I need to add 2 additional parameters to my request in the Watson Unity SDK
1 language_customization_id (which I assume is my custom model ID)
and
2 grammar_name
If you could at least tell me which class file I should be looking at in the Unity SDK it would be a HUGE help. Thanks again.
https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-grammarUse

**Comment by jBachalo** [comment]
Update
This is resolved by updating the Active method in ExampleStreaming.cs with language_customization_id and grammar_name.
