### ISSUE TITLE
Unity SDK v4

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#578]
We are planning to do a major release of the Watson Unity SDK in September. This issue will be used to track features and changes we want to make in the next major release. We welcome community feedback on these goals - do people want these things? Are there other implementations/packages we should be looking at? Any comments are appreciated!

## Planned changes
- [x] Provide more flexible and extensible support for authorization. This may include allowing the application to specify headers to be passed on token requests, and whether token requests can use insecure connections (e.g. self-signed certificates). This might be a breaking change for some applications.
- [x] Parameter order change for operations that have synthesized parameters in the SDK generator.
- [ ] **suggestion:** change class naming for services. E.g, `AssistantService` to `AssistantV1`.

cc @akeller @kimberlysiva

**Comment by mamoonraja** [comment]
released
