### ISSUE TITLE
[credential] get a critical error ( can't parse json )

### ISSUE THREAD

**Issue by yutatoga** [watson-developer-cloud/unity-sdk#580]
When not connected to the internet,
can't parse JSON below and get a critical error.
RESTConnector.cs：642

Unity2018.4.3f1

**Comment by oslindstrm** [comment]
I had a similar issue yesterday, it magically went away after some tinkering. Now it seems like the Credentials are never fetched, resulting in the Speech to text service not working.

**Comment by mamoonraja** [comment]
Hi @yutatoga and @oslindstrm for reporting the issue. Can you please provide more info on the error. E.g, 

- which version of Unity SDK and SDK core are you using
- Error trace if possible, and steps to reproduce.
