### ISSUE TITLE
Invalid return response for Visual recognition - 3.4.0

### ISSUE THREAD

**Issue by kpradp** [watson-developer-cloud/unity-sdk#584]
Cannot implicitly convert type 'System.Collections.Generic.Dictionary<string,object>' to 'string'
(wrapper dynamic-method)

The response from visualRecognitionService.Classify is no longer returning valid response to the call back.

void OnClassify(DetailedResponse<ClassifiedImages> response, IBMError error)

There is a type mismatch.

**Comment by mamoonraja** [comment]
Thanks for opening the issue, I am investigating the issue and will have a fix out asap.

**Comment by mamoonraja** [comment]
`Classify` is working for me, can you provide info on what version of sdk's [core](https://github.com/IBM/unity-sdk-core) are you using and what parameters are you providing in `classify`?

**Comment by kpradp** [comment]
v0.3.0
The previous version had a call back for Dict<string, object>

**Comment by kpradp** [comment]
Bump

**Comment by mamoonraja** [comment]
@kpradp Were you able to resolve the issue by using the above example?
