### ISSUE TITLE
[unity-sdk-core-0.3.0] websocket-sharp.dll conflicts with other plugins since they have the same Namespace

### ISSUE THREAD

**Issue by MirajM** [watson-developer-cloud/unity-sdk#587]
IBM Watson SDK and SendBird SDK Both have the same name for websocket-sharp which causing conflicts with code, unable to use both in one project. 

**Steps to reproduce:**
- Create new unity project
- Download IBM Watson SDK : unity-sdk-3.4.1 and unity-sdk-core-0.3.0 from Github
- Download SendBird SDK from Github (https://github.com/sendbird/SendBird-SDK-dotNET)
- Import Both into the project

**Expected behaviour:**

- Being able to use IBM Watson SDK with other third party plugins to different services.

**Actual behaviour:**

- Unity shows the following errors:
`PrecompiledAssemblyException: Multiple precompiled assemblies with the same name websocket-sharp.dll included for the current platform. Only one assembly with the same name is allowed per platform`

**Development Environment:**
- Unity 2018.3.5f1
- IBM Waston SDK: unity-sdk-3.4.1 & unity-sdk-core-0.3.0
- SendBird .NET SDK
- Windows 7

**Found similar closed issue #334 but still facing this Issue in current websocket from unity-sdk-core-0.3.0\Plugins\websocket-sharp.dll**

**Comment by mamoonraja** [comment]
@MirajM Thanks a lot for opening the issue, we will review your request and decide on whether add this change in next major release next month or do a patch release.

**Comment by MirajM** [comment]
@mamoonraja Thank you for your reply , is there any other way i can use these both SDK in one project? I would appreciate if you cloud let me know one.

**Comment by mediumTaj** [comment]
@MirajM can you try to remove the websocket sharp plugin from the core/Plugins directory?

**Comment by MirajM** [comment]
@mediumTaj  I tried deleting websocket sharp plugin from the core/Plugins directory but then i get `(are you missing a using directive or an assembly reference?)` for all of the files in core and sdk folder. on the other-side i tried deleting the websocket from Sendbird  SDK then its not getting connected.
