### ISSUE TITLE
[assistant v2] Bug using Watson SDK on Lumin OS with Magic Leap One

### ISSUE THREAD

**Issue by CJParry** [watson-developer-cloud/unity-sdk#592]
I have made a Magic Leap One project with the Watson-Unity SDK Assistant. I found a bug when deploying to the Magic Leap device, which uses the Lumin OS. The `Common.cs` class is trying to access the `SystemInformation.Os`. 

In Windows, this would return something like `Windows 10.0.0`. The OS version number is then extracted from this. When deployed on the Lumin device, it returns only `Lumin`. When the version number is accessed, it throws an empty version string error. 

I bypassed this error by checking for an empty version string in the Common.cs class. If it was empty, this meant I was deployed on the Magic Leap Lumin device. I would then hard-code my current Lumin OS in `Common.cs`.

I am using the unity-sdk v3.5 and unity-sdk-core v0.3 I used Lumin OS 0.97, Lumin Runtime SDK v0.22, Unity v2019.2.0b10, and the Magic Leap version 0.97.0

I hope you can find a more elegant fix then mine, I had limited time.

Cheers

**Comment by mamoonraja** [comment]
Thanks a lot for opening the issue @CJParry. We will make sure we have the check for the empty string as a minimum requirement to fix this one and look into another elegant way to fix this.

**Comment by hitch22** [comment]
@CJParry Do you mind sharing more information on your workaround? I am having the same problem.  Hardcoded in OS and version info, but I am still having problem. I'd greatly appreciate it if you shared more.
