### ISSUE TITLE
Change namespace versioning design

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/unity-sdk#6]
The namespaces are currently designed so that v1 of all of the services sit together in the same namespace. They should be like the Java SDK (https://github.com/watson-developer-cloud/java-sdk/tree/master/src/main/java/com/ibm/watson/developer_cloud), where there is a package for each service and then each version.

**Comment by rolyle** [comment]
C# doesn't have packages, so not entirely sure how we would address this.
 
 
                                                                        Regards,
                         
                        RICHARD O. LYLE                        Creative 3D Developer                                                                         
                                                                                                                                Phone: 1-512-968-1266                        E-mail: rolyle@us.ibm.com                        Watson CTO Labs Tour request form:: ibm.biz/watsonlabstourrequest                                                                        11501 Burnet Rd                        Austin, TX 78758-3400                        United States                        
 
 
----- Original message -----From: Jeffrey Stylos <notifications@github.com>To: watson-developer-cloud/unity-sdk <unity-sdk@noreply.github.com>Cc:Subject: [unity-sdk] Change namespace versioning design (#6)Date: Thu, Jan 28, 2016 3:44 PM 
The namespaces are currently designed so that v1 of all of the services sit together in the same namespace. They should be like the Java SDK (https://github.com/watson-developer-cloud/java-sdk/tree/master/src/main/java/com/ibm/watson/developer_cloud), where there is a package for each service and then each version.
—Reply to this email directly or view it on GitHub.

**Comment by germanattanasio** [comment]
You seems to be using `namespace` which is fine but the organization you use is what is wrong.

Right now you have something like:

```c
namespace IBM.Watson.DeveloperCloud.Services.v1
{
    /// <summary>
    /// This class wraps the Language Translation service.
    /// <a href="http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/language-translation.html">Language Translation Service</a>
    /// </summary>
    public class LanguageTranslation : IWatsonService
    {
```

```c
namespace IBM.Watson.DeveloperCloud.Services.LanguageTranslation.v1
{
    /// <summary>
    /// This class wraps the Language Translation service.
    /// <a href="http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/language-translation.html">Language Translation Service</a>
    /// </summary>
    public class LanguageTranslation : IWatsonService
    {
```

The namespace should be: `namespace IBM.Watson.DeveloperCloud.Services.LanguageTranslation.v1
`

**Comment by rolyle** [comment]
So your suggestion is to make a namespace that holds one class named the same as the namespace? 
 
 
                                                                        Regards,
                         
                        RICHARD O. LYLE                        Creative 3D Developer                                                                         
                                                                                                                                Phone: 1-512-968-1266                        E-mail: rolyle@us.ibm.com                        Watson CTO Labs Tour request form:: ibm.biz/watsonlabstourrequest                                                                        11501 Burnet Rd                        Austin, TX 78758-3400                        United States                        
 
 
----- Original message -----From: German Attanasio Ruiz <notifications@github.com>To: watson-developer-cloud/unity-sdk <unity-sdk@noreply.github.com>Cc: Richard O Lyle/Austin/IBM@IBMUSSubject: Re: [unity-sdk] Change namespace versioning design (#6)Date: Fri, Jan 29, 2016 9:30 AM 
You seems to be using namespace which is fine but the organization you use is what is wrong.
Right now you have something like:
namespace IBM.Watson.DeveloperCloud.Services.v1{    /// <summary>    /// This class wraps the Language Translation service.    /// <a href="http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/language-translation.html">Language Translation Service</a>    /// </summary>    public class LanguageTranslation : IWatsonService    {
namespace IBM.Watson.DeveloperCloud.Services.LanguageTranslation.v1{    /// <summary>    /// This class wraps the Language Translation service.    /// <a href="http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/language-translation.html">Language Translation Service</a>    /// </summary>    public class LanguageTranslation : IWatsonService    {
The namespace should be: namespace IBM.Watson.DeveloperCloud.Services.LanguageTranslation.v1
—Reply to this email directly or view it on GitHub.

**Comment by jsstylos** [comment]
Files should be grouped by service and then version, not version and then service. The rest of the SDKs get this right. (The Python SDK puts the version in the class name, but the structure is the same.)

**Comment by rolyle** [comment]
yes, i see your point. I guess we could roll the data models into the namespace as well, which might make it all a bit better organized.

**Comment by germanattanasio** [comment]
That's a good idea.

**Comment by rolyle** [comment]
OK, new branch is pushed "refactor-service-namespaces"... we are waiting until next week sometime before we merge into the develop branch.
