### ISSUE TITLE
[speech-to-text] "ExampleStreaming" not working

### ISSUE THREAD

**Issue by doukasd** [watson-developer-cloud/unity-sdk#601]
ExampleStreaming is not working. Consequently, it's not clear to a developer new to this how to get Speech-to-Text to work using IBM Watson...

Steps to reproduce:
- Download latest IBM Watson Unity SDK (i got [v4.0.0](https://github.com/watson-developer-cloud/unity-sdk/releases))
- Download latest IBM Unity Core (I got [v1.0.0](https://github.com/IBM/unity-sdk-core/releases))
- Create a new Unity project using your Unity version or preference (I used 2019.2) and drag the unzipped above folders inside it
- Make sure you are targeting .NET 4,x
- Open the "ExampleStreaming" scene from the Watson samples
- Fill in the API key and URL based on your account credentials and set the model to `en-US_BroadbandModel`
- Play
- Observe that nothing changes in the UI, nothing seems to be parsed or returned. Also observer that after a few seconds you get this warning and it seems that it's all stopped at that point:

```
[10/16/2019 13:37:38][SpeechToText.KeepAlive()][DEBUG] KeepAlive exited.
UnityEngine.Debug:Log(Object)
IBM.Cloud.SDK.Debug.DebugReactor:ProcessLog(LogRecord) (at Assets/IBM/unity-sdk-core-1.0.0/Debug/DebugReactor.cs:68)
IBM.Cloud.SDK.LogSystem:ProcessLog(LogRecord) (at Assets/IBM/unity-sdk-core-1.0.0/Logging/Logger.cs:207)
IBM.Cloud.SDK.Log:Debug(String, String, Object[]) (at Assets/IBM/unity-sdk-core-1.0.0/Logging/Logger.cs:229)
IBM.Watson.SpeechToText.V1.<KeepAlive>d__226:MoveNext() (at Assets/IBM/unity-sdk-4.0.0/Scripts/Services/SpeechToText/V1/SpeechToTextServiceExtension.cs:554)
IBM.Cloud.SDK.Utilities.Routine:MoveNext() (at Assets/IBM/unity-sdk-core-1.0.0/Utilities/Runnable.cs:131)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by mamoonraja** [comment]
@doukasd thanks for opening the issue, It looks like problem might be that your mic is not picking up the audio and service is exiting after not detecting anything in a while. There should be a log for which device you are connected to, it should look like: `devices: Built-in Microphone` or whatever device you are using. For debugging purposes can you confirm if you see any other error before `KeepAlive exited.`

**Comment by doukasd** [comment]
Thank you for the quick response. There is no error I am afraid. My mic device is picked up correctly too.

![Unity_2019-10-16_16-53-52](https://user-images.githubusercontent.com/357876/66925774-9da0ba00-f035-11e9-8171-cf177fc7519a.png)

**Comment by doukasd** [comment]
Following @mamoonraja 's advice, adding `_service.SetServiceUrl(_serviceUrl);` after [this line](https://github.com/watson-developer-cloud/unity-sdk/blob/master/Examples/ExampleStreaming.cs#L81) sets the `_serviceUrl` correctly and then the example works fine!

I guess we can leave this issue open until this is part of the next release/master.

Thank you.
