### ISSUE TITLE
[Speech-to-Text] Expected a JSON header message before receiving binary data.

### ISSUE THREAD

**Issue by DTClarke** [watson-developer-cloud/unity-sdk#604]
When using the Speech to Text API I receive the error [SpeechToText.OnListenMessage()][ERROR] Error: Expected a JSON header message before receiving binary data.
UnityEngine.Debug:LogError(Object).

I get the error even when using the `ExampleStreaming` example code and scene. Although, sometimes it does work albeit very rarely.

I'm using the latest Watson SDKs on GitHub (as of 7th of November). And I've tried the issue in unity `2019.2.11f1` and `2019.2.10f1`. 

I've tried reinstalling the SDK, Unity, and upgrading my Mac from Mojave to Catalina with no luck. I've also looked through old issues however the only workaround I found was increasing `service.MaxAlternatives` which is already fixed in the updated code and increasing it further does nothing.

I've tested my microphone (it's working), and made sure unity has permission to access it. I've made sure to set my build settings so that API compatibility is `.NET 4.x`.

I tried recreating the issue on another machine, using the same STT api key and url, however the same set up worked fine on that machine.

<img width="1269" alt="Screenshot 2019-11-06 at 16 38 39" src="https://user-images.githubusercontent.com/26624131/68402981-1fd35880-0174-11ea-9a24-253e395ed94a.png">

To get to this stage I used the latest Unity and Watson SDKs, allowed access to my mic, set API Compatability to `.NET 4.x`, opened up `ExampleStreaming`, and inserted the credentials of a Speech to text service.

**Comment by mamoonraja** [comment]
Hi @DTClarke, thanks for opening the issue. 

Can you try one thing:

- on line https://github.com/watson-developer-cloud/unity-sdk/blob/master/Examples/ExampleStreaming.cs#L174

- replace `(bFirstBlock && writePos >= midPoint)` with `(bFirstBlock)`
my guess is that somehow your app is not sending start message here: https://github.com/watson-developer-cloud/unity-sdk/blob/master/Examples/ExampleStreaming.cs#L186, so trying to verify that.

**Comment by DTClarke** [comment]
I've just quickly tried that. If i remove `&& writePos >= midPoint` and hit play it seems to make unity unresponsive and I have to force quit. Adding it back in gets me back to the first issue.

**Comment by mamoonraja** [comment]
Thanks for testing that out @DTClarke. My guess us that we are never getting into the following if statement `(bFirstBlock && writePos >= midPoint) || (!bFirstBlock && writePos < midPoint)`. So we need to look into why that's happening.

**Comment by mamoonraja** [comment]
We talked about the issue and debugged it, the issue was with microphone not getting started. Trying another microphone worked so probably not an SDK issue, it is probably an issue with the microphone. I am closing this for now please feel free to open if you see the issue again.
