### ISSUE TITLE
LanguageTranslator

### ISSUE THREAD

**Issue by mhadji05** [watson-developer-cloud/unity-sdk#605]
LanguageTranslator

I saw this tutorial
https://youtu.be/c6x78IlYtpk?list=PLZDyxLlNKRY9b2vurEhkSoNWZN5c5l4Nr&t=67

I cant import :
using IBM.Watson.DeveloperCloud.Services.LanguageTranslator.V3;

**Comment by mamoonraja** [comment]
Hi, if you are using the recent version of the SDK please use `using IBM.Watson.LanguageTranslator.V3;` to import.

**Comment by mhadji05** [comment]
Do you mean private ExampleLanguageTranslatorV3 languageTranslator;

Also credentials give error. no class of credentials.
Credentials languageTranslatorCredentials = new Credentials(languageTranslatorTokenOptions, serviceURL);

Some tutorial of new Watson?

**Comment by mediumTaj** [comment]
Yes sorry @mhadji05 - we need to update the tutorial videos from the last major release. Please see this repo for adding language translator to the example streaming scene 

https://github.com/mediumTaj/unity-sdk-demo-languageTranslation

Just add speech to text credentials in the inspector and language translator credentials in the examplestreaming script.

**Comment by mhadji05** [comment]
Just add speech to text credentials in the inspector. where in Inspector?

**Comment by mhadji05** [comment]
Just add speech to text credentials in the inspector. where in Inspector?

I add credentials on ExampleStreaming.scene on Gameobject with name ExampleStreaming and i success speech to text but how can i make language translator?

**Comment by mediumTaj** [comment]
If you check the `ExampleStreaming` GameObject in the `ExampleStreaming` scene you will see where to add the API Key in the inspector.

<img width="753" alt="Screen Shot 2019-11-11 at 7 42 57 AM" src="https://user-images.githubusercontent.com/4381558/68591774-176e6c80-0457-11ea-931c-07cdf1b81408.png">

If you open the `ExampleStreaming.cs` script you can add the LanguageTranslator API key directly to the example script. See `apikey: "<apikey>"`  below.

<img width="785" alt="example_streaming" src="https://user-images.githubusercontent.com/4381558/68592077-dcb90400-0457-11ea-9b6b-f7bd5f04cf52.png">

**Comment by mhadji05** [comment]
how many languages can i translate. Can i translate to greek? If yes how?

**Comment by mhadji05** [comment]
this line must be in comments? 

// Translate!
//languageTranslatorService.Translate(OnTranslate, new List<string> { alt.transcript }, "en-es");

how many languages can i translate. Can i translate to greek? If yes how?

**Comment by mhadji05** [comment]
this line must be in comments?

// Translate!
//languageTranslatorService.Translate(OnTranslate, new List { alt.transcript }, "en-es");

how many languages can i translate. Can i translate to greek? If yes how?

**Comment by mediumTaj** [comment]
Uncomment that line to send the speech to text transcription result to Language Translator. Greek language is supported. 

https://cloud.ibm.com/docs/services/language-translator?topic=language-translator-translation-models

In the above line you can change `en-es` to `en-el` to translate from english to greek. 

Speech to Text does not support greek

https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-models

So you will not be able to translate from greek to english using this application. Language Translator does support greek to english (`el-en`) via text input.

**Comment by mhadji05** [comment]
i follow all of your instructions but i fail.

No errors  i cant understand why

![Untitled](https://user-images.githubusercontent.com/22151801/68955355-81c43b80-07ce-11ea-8e4b-3d4245093a3e.png)

**Comment by mhadji05** [comment]
I follow all of your instructions but i get error on languageTranslator

![Untitled](https://user-images.githubusercontent.com/22151801/68957492-d5d11f00-07d2-11ea-9877-4c054de34709.png)

**Comment by mediumTaj** [comment]
what region is you language translator instance? The default is US South (Dallas). You may need to add the service url

```cs
Authenticator languageTranslatorAuthenticator = new IamAuthenticator(apikey: "<apikey>", url: "<service-url>");
```

**Comment by mediumTaj** [comment]
You also may want to check the error in the translate handler

```cs
private void OnTranslate(DetailedResponse<TranslationResult> response, IBMError error)
{
    if (error != null)
    {
        Log.Debug("ExampleStreaming", "error: {0}, {1}", error.StatusCode, error.ErrorMessage);
    }
    else
    {
        ResultsField.text = response.Result.Translations[0]._Translation;
    }
}
```

**Comment by mhadji05** [comment]
Error again :(


![Untitled](https://user-images.githubusercontent.com/22151801/68964167-5eef5280-07e1-11ea-892a-4191ba2fc7bb.png)



`namespace IBM.Watsson.Examples
{
    public class ExampleStreaming : MonoBehaviour
    {
        #region PLEASE SET THESE VARIABLES IN THE INSPECTOR
        [Space(10)]
        [Tooltip("The service URL (optional). This defaults to \"https://stream.watsonplatform.net/speech-to-text/api\"")]
        [SerializeField]
        private string SST_serviceUrl;
        [Tooltip("Text field to display the results of streaming.")]
        public Text ResultsField;
        [Header("IAM Authentication")]
        [Tooltip("The IAM apikey.")]
        [SerializeField]
        private string SST_Apikey;

        [SerializeField]
        private string langTrans_ServiceUrl;

        [SerializeField]
        private string langTrans_ApiKey;


        [Header("Parameters")]
        // https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#get-model
        [Tooltip("The Model to use. This defaults to en-US_BroadbandModel")]
        [SerializeField]
        private string _recognizeModel;
        #endregion


        private int _recordingRoutine = 0;
        private string _microphoneID = null;
        private AudioClip _recording = null;
        private int _recordingBufferSize = 1;
        private int _recordingHZ = 22050;

        private SpeechToTextService _service;
        private LanguageTranslatorService languageTranslatorService;

        void Start()
        {
            LogSystem.InstallDefaultReactors();
            Runnable.Run(CreateService());
        }

        private IEnumerator CreateService()
        {
            if (string.IsNullOrEmpty(SST_Apikey))
            {
                throw new IBMException("Plesae provide IAM ApiKey for the service.");
            }

            IamAuthenticator authenticator = new IamAuthenticator(apikey: SST_Apikey, url: SST_serviceUrl);

            //  Wait for tokendata
            while (!authenticator.CanAuthenticate())
                yield return null;

            _service = new SpeechToTextService(authenticator);
            if (!string.IsNullOrEmpty(SST_serviceUrl))
            {
                _service.SetServiceUrl(SST_serviceUrl);
            }
            _service.StreamMultipart = true;

            //  Create LanguageTranslator
            Authenticator languageTranslatorAuthenticator = new IamAuthenticator(apikey: langTrans_ApiKey, url: langTrans_ServiceUrl);
            while (!languageTranslatorAuthenticator.CanAuthenticate())
                yield return null;

            languageTranslatorService = new LanguageTranslatorService("2019-11-08", languageTranslatorAuthenticator);
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            
            Active = true;
            StartRecording();
        }

        public bool Active
        {
            get { return _service.IsListening; }
            set
            {
                if (value && !_service.IsListening)
                {
                    _service.RecognizeModel = (string.IsNullOrEmpty(_recognizeModel) ? "en-US_BroadbandModel" : _recognizeModel);
                    _service.DetectSilence = true;
                    _service.EnableWordConfidence = true;
                    _service.EnableTimestamps = true;
                    _service.SilenceThreshold = 0.01f;
                    _service.MaxAlternatives = 1;
                    _service.EnableInterimResults = true;
                    _service.OnError = OnError;
                    _service.InactivityTimeout = -1;
                    _service.ProfanityFilter = false;
                    _service.SmartFormatting = true;
                    _service.SpeakerLabels = false;
                    _service.WordAlternativesThreshold = null;
                    _service.StartListening(OnRecognize, OnRecognizeSpeaker);
                }
                else if (!value && _service.IsListening)
                {
                    _service.StopListening();
                }
            }
        }

        private void StartRecording()
        {
            if (_recordingRoutine == 0)
            {
                UnityObjectUtil.StartDestroyQueue();
                _recordingRoutine = Runnable.Run(RecordingHandler());
            }
        }

        private void StopRecording()
        {
            if (_recordingRoutine != 0)
            {
                Microphone.End(_microphoneID);
                Runnable.Stop(_recordingRoutine);
                _recordingRoutine = 0;
            }
        }

        private void OnError(string error)
        {
            Active = false;

            Log.Debug("ExampleStreaming.OnError()", "Error! {0}", error);
        }

        private IEnumerator RecordingHandler()
        {
            Log.Debug("ExampleStreaming.RecordingHandler()", "devices: {0}", Microphone.devices);
            _recording = Microphone.Start(_microphoneID, true, _recordingBufferSize, _recordingHZ);
            yield return null;      // let _recordingRoutine get set..

            if (_recording == null)
            {
                StopRecording();
                yield break;
            }

            bool bFirstBlock = true;
            int midPoint = _recording.samples / 2;
            float[] samples = null;

            while (_recordingRoutine != 0 && _recording != null)
            {
                int writePos = Microphone.GetPosition(_microphoneID);
                if (writePos > _recording.samples || !Microphone.IsRecording(_microphoneID))
                {
                    Log.Error("ExampleStreaming.RecordingHandler()", "Microphone disconnected.");

                    StopRecording();
                    yield break;
                }

                if ((bFirstBlock && writePos >= midPoint)
                  || (!bFirstBlock && writePos < midPoint))
                {
                    // front block is recorded, make a RecordClip and pass it onto our callback.
                    samples = new float[midPoint];
                    _recording.GetData(samples, bFirstBlock ? 0 : midPoint);

                    AudioData record = new AudioData();
                    record.MaxLevel = Mathf.Max(Mathf.Abs(Mathf.Min(samples)), Mathf.Max(samples));
                    record.Clip = AudioClip.Create("Recording", midPoint, _recording.channels, _recordingHZ, false);
                    record.Clip.SetData(samples, 0);

                    _service.OnListen(record);

                    bFirstBlock = !bFirstBlock;
                }
                else
                {
                    // calculate the number of samples remaining until we ready for a block of audio, 
                    // and wait that amount of time it will take to record.
                    int remaining = bFirstBlock ? (midPoint - writePos) : (_recording.samples - writePos);
                    float timeRemaining = (float)remaining / (float)_recordingHZ;

                    yield return new WaitForSeconds(timeRemaining);
                }
            }
            yield break;
        }

        private void OnRecognize(SpeechRecognitionEvent result)
        {
            if (result != null && result.results.Length > 0)
            {
                foreach (var res in result.results)
                {
                    foreach (var alt in res.alternatives)
                    {
                        string text = string.Format("{0} ({1}, {2:0.00})\n", alt.transcript, res.final ? "Final" : "Interim", alt.confidence);
                        Log.Debug("ExampleStreaming.OnRecognize()", text);
                        ResultsField.text = text;

                        // Translate!
                        languageTranslatorService.Translate(OnTranslate, new List<string> { alt.transcript }, "en-el");
                    }

                    if (res.keywords_result != null && res.keywords_result.keyword != null)
                    {
                        foreach (var keyword in res.keywords_result.keyword)
                        {
                            Log.Debug("ExampleStreaming.OnRecognize()", "keyword: {0}, confidence: {1}, start time: {2}, end time: {3}", keyword.normalized_text, keyword.confidence, keyword.start_time, keyword.end_time);
                        }
                    }

                    if (res.word_alternatives != null)
                    {
                        foreach (var wordAlternative in res.word_alternatives)
                        {
                            Log.Debug("ExampleStreaming.OnRecognize()", "Word alternatives found. Start time: {0} | EndTime: {1}", wordAlternative.start_time, wordAlternative.end_time);
                            foreach (var alternative in wordAlternative.alternatives)
                                Log.Debug("ExampleStreaming.OnRecognize()", "\t word: {0} | confidence: {1}", alternative.word, alternative.confidence);
                        }
                    }
                }
            }
        }


        private void OnTranslate(DetailedResponse<TranslationResult> response, IBMError error)
        {
            if (error != null)
            {
                Log.Debug("ExampleStreaming", "error: {0}, {1}", error.StatusCode, error.ErrorMessage);
            }
            else
            {
                ResultsField.text = response.Result.Translations[0]._Translation;
            }
        }



        private void OnRecognizeSpeaker(SpeakerRecognitionEvent result)
        {
            if (result != null)
            {
                foreach (SpeakerLabelsResult labelResult in result.speaker_labels)
                {
                    Log.Debug("ExampleStreaming.OnRecognizeSpeaker()", string.Format("speaker result: {0} | confidence: {3} | from: {1} | to: {2}", labelResult.speaker, labelResult.from, labelResult.to, labelResult.confidence));
                }
            }
        }
    }
}`

**Comment by mhadji05** [comment]
Error again :(

When I add this line of code:
` IamAuthenticator authenticator = new IamAuthenticator(apikey: SST_Apikey, url: SST_serviceUrl);`

or this line of code:
`Authenticator languageTranslatorAuthenticator = new IamAuthenticator(apikey: langTrans_ApiKey, url: langTrans_ServiceUrl);`

I get error.


![Untitled](https://user-images.githubusercontent.com/22151801/68964167-5eef5280-07e1-11ea-892a-4191ba2fc7bb.png)



`namespace IBM.Watsson.Examples
{
    public class ExampleStreaming : MonoBehaviour
    {
        #region PLEASE SET THESE VARIABLES IN THE INSPECTOR
        [Space(10)]
        [Tooltip("The service URL (optional). This defaults to \"https://stream.watsonplatform.net/speech-to-text/api\"")]
        [SerializeField]
        private string SST_serviceUrl;
        [Tooltip("Text field to display the results of streaming.")]
        public Text ResultsField;
        [Header("IAM Authentication")]
        [Tooltip("The IAM apikey.")]
        [SerializeField]
        private string SST_Apikey;

        [SerializeField]
        private string langTrans_ServiceUrl;

        [SerializeField]
        private string langTrans_ApiKey;


        [Header("Parameters")]
        // https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#get-model
        [Tooltip("The Model to use. This defaults to en-US_BroadbandModel")]
        [SerializeField]
        private string _recognizeModel;
        #endregion


        private int _recordingRoutine = 0;
        private string _microphoneID = null;
        private AudioClip _recording = null;
        private int _recordingBufferSize = 1;
        private int _recordingHZ = 22050;

        private SpeechToTextService _service;
        private LanguageTranslatorService languageTranslatorService;

        void Start()
        {
            LogSystem.InstallDefaultReactors();
            Runnable.Run(CreateService());
        }

        private IEnumerator CreateService()
        {
            if (string.IsNullOrEmpty(SST_Apikey))
            {
                throw new IBMException("Plesae provide IAM ApiKey for the service.");
            }

            IamAuthenticator authenticator = new IamAuthenticator(apikey: SST_Apikey, url: SST_serviceUrl);

            //  Wait for tokendata
            while (!authenticator.CanAuthenticate())
                yield return null;

            _service = new SpeechToTextService(authenticator);
            if (!string.IsNullOrEmpty(SST_serviceUrl))
            {
                _service.SetServiceUrl(SST_serviceUrl);
            }
            _service.StreamMultipart = true;

            //  Create LanguageTranslator
            Authenticator languageTranslatorAuthenticator = new IamAuthenticator(apikey: langTrans_ApiKey, url: langTrans_ServiceUrl);
            while (!languageTranslatorAuthenticator.CanAuthenticate())
                yield return null;

            languageTranslatorService = new LanguageTranslatorService("2019-11-08", languageTranslatorAuthenticator);
            ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            
            Active = true;
            StartRecording();
        }

        public bool Active
        {
            get { return _service.IsListening; }
            set
            {
                if (value && !_service.IsListening)
                {
                    _service.RecognizeModel = (string.IsNullOrEmpty(_recognizeModel) ? "en-US_BroadbandModel" : _recognizeModel);
                    _service.DetectSilence = true;
                    _service.EnableWordConfidence = true;
                    _service.EnableTimestamps = true;
                    _service.SilenceThreshold = 0.01f;
                    _service.MaxAlternatives = 1;
                    _service.EnableInterimResults = true;
                    _service.OnError = OnError;
                    _service.InactivityTimeout = -1;
                    _service.ProfanityFilter = false;
                    _service.SmartFormatting = true;
                    _service.SpeakerLabels = false;
                    _service.WordAlternativesThreshold = null;
                    _service.StartListening(OnRecognize, OnRecognizeSpeaker);
                }
                else if (!value && _service.IsListening)
                {
                    _service.StopListening();
                }
            }
        }

        private void StartRecording()
        {
            if (_recordingRoutine == 0)
            {
                UnityObjectUtil.StartDestroyQueue();
                _recordingRoutine = Runnable.Run(RecordingHandler());
            }
        }

        private void StopRecording()
        {
            if (_recordingRoutine != 0)
            {
                Microphone.End(_microphoneID);
                Runnable.Stop(_recordingRoutine);
                _recordingRoutine = 0;
            }
        }

        private void OnError(string error)
        {
            Active = false;

            Log.Debug("ExampleStreaming.OnError()", "Error! {0}", error);
        }

        private IEnumerator RecordingHandler()
        {
            Log.Debug("ExampleStreaming.RecordingHandler()", "devices: {0}", Microphone.devices);
            _recording = Microphone.Start(_microphoneID, true, _recordingBufferSize, _recordingHZ);
            yield return null;      // let _recordingRoutine get set..

            if (_recording == null)
            {
                StopRecording();
                yield break;
            }

            bool bFirstBlock = true;
            int midPoint = _recording.samples / 2;
            float[] samples = null;

            while (_recordingRoutine != 0 && _recording != null)
            {
                int writePos = Microphone.GetPosition(_microphoneID);
                if (writePos > _recording.samples || !Microphone.IsRecording(_microphoneID))
                {
                    Log.Error("ExampleStreaming.RecordingHandler()", "Microphone disconnected.");

                    StopRecording();
                    yield break;
                }

                if ((bFirstBlock && writePos >= midPoint)
                  || (!bFirstBlock && writePos < midPoint))
                {
                    // front block is recorded, make a RecordClip and pass it onto our callback.
                    samples = new float[midPoint];
                    _recording.GetData(samples, bFirstBlock ? 0 : midPoint);

                    AudioData record = new AudioData();
                    record.MaxLevel = Mathf.Max(Mathf.Abs(Mathf.Min(samples)), Mathf.Max(samples));
                    record.Clip = AudioClip.Create("Recording", midPoint, _recording.channels, _recordingHZ, false);
                    record.Clip.SetData(samples, 0);

                    _service.OnListen(record);

                    bFirstBlock = !bFirstBlock;
                }
                else
                {
                    // calculate the number of samples remaining until we ready for a block of audio, 
                    // and wait that amount of time it will take to record.
                    int remaining = bFirstBlock ? (midPoint - writePos) : (_recording.samples - writePos);
                    float timeRemaining = (float)remaining / (float)_recordingHZ;

                    yield return new WaitForSeconds(timeRemaining);
                }
            }
            yield break;
        }

        private void OnRecognize(SpeechRecognitionEvent result)
        {
            if (result != null && result.results.Length > 0)
            {
                foreach (var res in result.results)
                {
                    foreach (var alt in res.alternatives)
                    {
                        string text = string.Format("{0} ({1}, {2:0.00})\n", alt.transcript, res.final ? "Final" : "Interim", alt.confidence);
                        Log.Debug("ExampleStreaming.OnRecognize()", text);
                        ResultsField.text = text;

                        // Translate!
                        languageTranslatorService.Translate(OnTranslate, new List<string> { alt.transcript }, "en-el");
                    }

                    if (res.keywords_result != null && res.keywords_result.keyword != null)
                    {
                        foreach (var keyword in res.keywords_result.keyword)
                        {
                            Log.Debug("ExampleStreaming.OnRecognize()", "keyword: {0}, confidence: {1}, start time: {2}, end time: {3}", keyword.normalized_text, keyword.confidence, keyword.start_time, keyword.end_time);
                        }
                    }

                    if (res.word_alternatives != null)
                    {
                        foreach (var wordAlternative in res.word_alternatives)
                        {
                            Log.Debug("ExampleStreaming.OnRecognize()", "Word alternatives found. Start time: {0} | EndTime: {1}", wordAlternative.start_time, wordAlternative.end_time);
                            foreach (var alternative in wordAlternative.alternatives)
                                Log.Debug("ExampleStreaming.OnRecognize()", "\t word: {0} | confidence: {1}", alternative.word, alternative.confidence);
                        }
                    }
                }
            }
        }


        private void OnTranslate(DetailedResponse<TranslationResult> response, IBMError error)
        {
            if (error != null)
            {
                Log.Debug("ExampleStreaming", "error: {0}, {1}", error.StatusCode, error.ErrorMessage);
            }
            else
            {
                ResultsField.text = response.Result.Translations[0]._Translation;
            }
        }



        private void OnRecognizeSpeaker(SpeakerRecognitionEvent result)
        {
            if (result != null)
            {
                foreach (SpeakerLabelsResult labelResult in result.speaker_labels)
                {
                    Log.Debug("ExampleStreaming.OnRecognizeSpeaker()", string.Format("speaker result: {0} | confidence: {3} | from: {1} | to: {2}", labelResult.speaker, labelResult.from, labelResult.to, labelResult.confidence));
                }
            }
        }
    }
}`

**Comment by mediumTaj** [comment]
You shouldn't add the code to the Speech to Text section - you should add speech to text credentials in the inspector. The second line of code should be fine.

**Comment by mhadji05** [comment]
I don't understand what I need to do. Can you please provide what line of code must remove and what code I need to add? In the inspector of ExampleStreaming.cs I add all of the needed credentials.
If you can provide some complete code, video tutorial i will apreciate it a lot.

**Comment by mhadji05** [comment]
Now i have this error 

![Untitled](https://user-images.githubusercontent.com/22151801/68980363-f5833a00-0808-11ea-905c-7c03c6576737.png)

**Comment by mediumTaj** [comment]
You can comment out these lines
```cs
string text = string.Format("{0} ({1}, {2:0.00})\n", alt.transcript, res.final ? "Final" : "Interim", alt.confidence);
Log.Debug("ExampleStreaming.OnRecognize()", text);
ResultsField.text = text;
```

Please set all apikey values and service urls in the inspector and double check they are correct. It looks like the url might not be correct for language translator.

**Comment by mhadji05** [comment]
yes from this error cant find it: 

[11/15/2019 22:55:18][RESTConnector.ProcessRequestQueue()][ERROR] URL: https://gateway-lon.watsonplatform.net/language-translator/api, ErrorCode: 404, Error: HTTP/1.1 404 Not Found, Response: {"code":404, "error": "Not Found"}

I cant understand why. I am completely sure apiKeys and urls are true.
I comment the 3 lines you said. 
The same error.

**Comment by mhadji05** [comment]
yes from this error cant find it: 

[11/15/2019 22:55:18][RESTConnector.ProcessRequestQueue()][ERROR] URL: https://gateway-lon.watsonplatform.net/language-translator/api, ErrorCode: 404, Error: HTTP/1.1 404 Not Found, Response: {"code":404, "error": "Not Found"}

I cant understand why. I am completely sure apiKeys and urls are true.
I comment the 3 lines you said. 
The same error.

**Comment by mhadji05** [comment]
any idea whats going wrong?

**Comment by mamoonraja** [comment]
@mhadji05 are you still seeing the same error?

**Comment by mhadji05** [comment]
@mamoonraja  yes. Can i have an example scene with language translator and another one with TTS?
