### ISSUE TITLE
DetailedResponse struct null when using IamAuthenticator

### ISSUE THREAD

**Issue by jkredzvr** [watson-developer-cloud/unity-sdk#610]
Unity Version 2019.2.10f1
unity-sdk-core-1.1.1
unity-sdk-4.1.0

Trying to deploy the SpeechToText example on a Magic Leap and during the authentication process on a build it is throwing an error on line 147 in IamAuthenticator.cs

tokenData = new IamToken(response.Result);

![image](https://user-images.githubusercontent.com/19713488/70192454-9484ae80-16b0-11ea-937d-09f6ed1c21a3.png)

I've also verified that the device is connected to the internet before creating the speechToTextAuthenticator

**Comment by mamoonraja** [comment]
Hi @jkredzvr, Thanks for opening the issue. It looks like a network issue, we have seen it before with the magic leap device. Does the example work if you run it with the simulator or you still get the same issue?

**Comment by jkredzvr** [comment]
Hi @mamoonraja, yes running the same project in editor works, but just not on device for some reason.  Any suggestions on debugging this?

**Comment by mamoonraja** [comment]
I don't have access to a Magic leap device, can you please do a log inside [OnGetToken](https://github.com/IBM/unity-sdk-core/blob/master/Authentication/Iam/IamAuthenticator.cs#L140) and let me know what you see?

**Comment by jkredzvr** [comment]
After logging the response object from OnGetToken (check the snippet of my logs)

![image](https://user-images.githubusercontent.com/19713488/70958995-c17d7d80-202f-11ea-81a9-feaa70efa20a.png)


Debugging or accessing the following struct fields results in null error
- response.Response

This last screenshot shows the Logged values from the response that didnt throw an error

![image](https://user-images.githubusercontent.com/19713488/70958882-69467b80-202f-11ea-94d2-617d3c3da52d.png)

This is Response struct
![image](https://user-images.githubusercontent.com/19713488/70958623-b2e29680-202e-11ea-87c2-02dfdbad4dc2.png)

To me it looks like its getting a "null" response where the fields arent filled for some reason.

**Comment by jkredzvr** [comment]
I figured out why I was getting empty string values in the response.  I had not set NewtonSoft JSON AOT DLL to target Lumin, so the Deserialization was not occurring.  Since Deserialization failed silently and didnt throw an exception, it prevented response.Response = json; from being set as well.

This issue can be closed, though it is strange the code didnt throw an exception when Deserialization failed or couldnt even be called.
