### ISSUE TITLE
Poor performance in ExampleStreaming.cs

### ISSUE THREAD

**Issue by ryan-motive** [watson-developer-cloud/unity-sdk#611]
The RecordingHandler loop in ExampleStreaming.cs causes noticeable pauses in the app every time it runs. In particular, the array alloc is generating a lot of GC activity and the Max Level calculation is taking a measurable amount of time looking at each sample. On top of this, the Microphone API seems to just be slow (this is more of an observation, not directly related to this code). It's not really usable as-is. I'm in the process of reworking it, but has anyone successfully used this code in a deployment or are there other examples we should be using for deployed apps?

It seems like we'll need to tie directly into the native microphone code and push the stream straight to the service. Just wondering if anyone has done something like this already.

**Comment by mamoonraja** [comment]
@ryan-motive Thanks a lot for opening the issue, I will leave this one open to see if we get any response from developers who tried to optimize the example code. Some of the changes you mentioned are out of our control, and `ExampleStreaming` serves as a starting point.

**Comment by rezasys2** [comment]
I have the same problem, this service is very slow, I hope someone finds a way or optimize the code soon.
