### ISSUE TITLE
I got two errors on a clean project

### ISSUE THREAD

**Issue by shiranova** [watson-developer-cloud/unity-sdk#612]
I followed the YouTube tutorial and got two errors.

Assembly has reference to non-existent assembly 'IBM.Cloud.SDK' (Assets/Watson/Tests/IBM.Watson.Tests.asmdef)

Assembly has reference to non-existent assembly 'IBM.Cloud.SDK' (Assets/Watson/WatsonUnitySDK.asmdef)

Unity version 2018.4.12f1

**Comment by shiranova** [comment]
Now tested on 2019.2.9f1 and got these errors:

![image](https://user-images.githubusercontent.com/18250769/70813710-9ba76d00-1dd2-11ea-8978-cde69c3e2eac.png)

**Comment by shiranova** [comment]
Update: 
I added core, chenged to .NET 4X

![image](https://user-images.githubusercontent.com/18250769/70814414-1d4bca80-1dd4-11ea-89fd-f8298015695e.png)


Unity version 2018.4.12f1 + 2019.2.9f1

**Comment by mediumTaj** [comment]
Sorry @shiranova, the youtube tutorials are out of date and we need to find some time to make an updated tutorial. Are you downloading the SDK core into your Assets directory? 

https://github.com/watson-developer-cloud/unity-sdk#getting-the-watson-sdk-and-adding-it-to-unity

**Comment by shiranova** [comment]
> Sorry @shiranova, the youtube tutorials are out of date and we need to find some time to make an updated tutorial. Are you downloading the SDK core into your Assets directory?
> 
> https://github.com/watson-developer-cloud/unity-sdk#getting-the-watson-sdk-and-adding-it-to-unity

Yes. I just downloaded the most recent versions. It's working on 2019.2.9f1 but not on 2018.4.12f1. I'll just work with this version. Thanks.

**Comment by pavithra-IT** [comment]
Same error here.

Any solve?
