### ISSUE TITLE
Simple endpoint to test if service is up and running

### ISSUE THREAD

**Issue by Naphier** [watson-developer-cloud/unity-sdk#620]
Is there an endpoint url we can call that will give a 200 response and tell us that the service is up and running? 
https://stream.watsonplatform.net
returns a 404 (wasn't a 404 a few days ago)
We just need a VERY simple check to see if watson is accessible so that we can warn our military users before actually attempting to connect. Thanks!

**Comment by mamoonraja** [comment]
Hi @Naphier, Thanks a lot for opening the issue, can you please explain your use case and how you are trying to invoke the endpoint?

**Comment by Naphier** [comment]
Use case is to just be able to send an http/s request and get a simple 200 response telling us that the service is up. For example if the service is down we want to potentially warn the user or fallback to another method. Also we need a way to test the service without sending credentials.
We have found this endpoint which seems to be fine.
https://api.us-south.speech-to-text.watson.cloud.ibm.com
Oftentime REST APIs will allow a non-authorized request to just check if the service is up.
