### ISSUE TITLE
[unity-sdk] CS0246: The type or namespace name 'CoveredMethodStats' could not be found

### ISSUE THREAD

**Issue by israteneda** [watson-developer-cloud/unity-sdk#624]
I started a new project with 2018.4.18f1 Unity version. I added unity-sdk and unity-sdk-core in Assets then changed the name folders to Watson and IBMSdkCore and changed the build settings to .NET 4.x equivalent.

The following errors appear:
* Assets\Watson\Tests\LanguageTranslatorV3UnitTests.cs(266,17): error CS0246: The type or namespace name 'CoveredMethodStats' could not be found (are you missing a using directive or an assembly reference?)
* Assets\Watson\Tests\LanguageTranslatorV3UnitTests.cs(266,44): error CS0103: The name 'Coverage' does not exist in the current context
 
Sdk version:
unity-sdk-4.5.0
unity-sdk-core-1.2.0

**Comment by mamoonraja** [comment]
@israteneda thanks a lot for opening the issue. I am not able to reproduce it, it looks like an import issue, I will try to look into it asap.

**Comment by israteneda** [comment]
I tried with Unity 2019.2.8f1 and works normally the errors don't show. I think the problem is related to @mediumTaj said. 
P.D.:I used Unity 2018.4.18f1 because it is the LTS version.

**Comment by mediumTaj** [comment]
I would probably move up to the latest version of Unity if your project doesn't have any dependencies on legacy versions. I'm glad the issue is resolved!
