### ISSUE TITLE
[Assistant] Crashes on Android il2cpp

### ISSUE THREAD

**Issue by Faalvare** [watson-developer-cloud/unity-sdk#625]
When i try to send a message my code crashes and fails, this only happens when i compile on il2cpp for the android platform, this is the error message:

```
InvalidOperationException: Sequence contains no elements
03-05 17:12:51.638 15874 15901 E Unity   :   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <00000000000000000000000000000000>:0
03-05 17:12:51.638 15874 15901 E Unity   :   at Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates (Newtonsoft.Json.Serialization.JsonObjectContract contract, System.Reflection.MemberInfo member) [0x00000] in <00000000000000000000000000000000>:0
03-05 17:12:51.638 15874 15901 E Unity   :   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract (System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0
03-05 17:12:51.638 15874 15901 E Unity   :   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0
03-05 17:12:51.638 15874 15901 E Unity   :   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract (System.Type type) [0x00000] in <00000000000000000000000000000000>:0
03-05 17:12:51.638 15874 15901 E Unity   :   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues (Newtonsoft.Json.JsonWriter writer, System.Obje
```

this is the code that causes the crash:

```
assistantService.Message(
            callback: OnMessage,
            assistantId: assistantId,
            sessionId: sessionId,
            input: new MessageInput()
            {
                Text = msg,
                Options = new MessageInputOptions()
                {
                    ReturnContext = true
                }
            },
            context: new MessageContext()
            {
                Global = new MessageContextGlobal()
                {
                    System = new MessageContextGlobalSystem()
                    {
                        UserId = PlayerPrefs.GetString("PerfilOn")
                    }
                }
            });
```

looking for a solution, i found that this is can be caused by the unity's code stripping, a functionality that cannot be disabled when using the Il2cpp compiler. This is a problem because this is the only way to compile in 64 bits for android...

**Comment by mediumTaj** [comment]
Is il2ccp the only way to compile 64 bit android applications? Looks like this is coming from Json.NET. We should look into seeing if we can address this or if it has already been addressed in newer versions.

**Comment by Faalvare** [comment]
yes, mono is not able to compile 64 bit apps at least in the unity engine. this happens when i call the  `WatsonService.message` im in big trouble here because one of the main features of my app comes with the watson assistant service, and google doesn't allow to publish 32 bit apps, i will still be looking for any solution here, thanks for the help @mediumTaj

**Comment by Faalvare** [comment]
Looking for information i found this: 

> It might be code stripping: if your code doesn't have an explicit constructor call for a WP class (i.e., somewhere that says new WP(); ), then the constructor might get stripped. Look up code stripping and how to control it.

https://forum.unity.com/threads/serialization-works-well-in-editor-but-not-on-mobile.803520/

**Comment by Faalvare** [comment]
Update: Seems like this is the line that causes the problem:

### AssistantService.cs:
`req.Send = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(bodyObject));`

so indeed, when JSON.net is used to serialize an object it crashed...
i made a couple of test where i used the Json.NET to serialize an object of type `MessageInput` in the same class and it crashed too.. but the strange is,when i use Json.NET to serialize an object of the same type in my class it works perfectly

**Comment by realitygarage** [comment]
There seems to be a AOT version of the JsonDotNet DLL in the thirdparty subdir, but my guess is that it was not built to include all the methods required... I believe there is workaround to delete the prebuilt dll, and include this package, and then create helper classes to force the compilation inclusion for the missing functions. Seems that this should have already been done - for text to speech feature, I am getting  Missing constructor for enumerator type Newtonsoft.Json.Serialization.DefaultContractResolver+EnumerableDictionaryWrapper`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Newtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]


https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Reference-Newtonsoft.Json.Utilities.AotHelper

**Comment by realitygarage** [comment]
Fixed the iss running the text to speech service with IL2CPP build was throwing exceptions... 
   
see links in previous post

Here are the exceptions and resulting code I created in a AoTHelper that fixed:

EXCEPTIONS
=======
'Newtonsoft.Json.Utilities.CollectionWrapper`1[[System.Nullable`1[[System.Int64, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]::.ctor' for which no ahead of time (AOT) code was generated. at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <00000000000000000000000000000000>:0 

 Newtonsoft.Json.JsonException: Missing constructor for enumerator type Newtonsoft.Json.Serialization.DefaultContractResolver+EnumerableDictionaryWrapper`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Newtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]]. Perhaps it got stripped?



AoTHelpherCode snippet
=================
    private void Awake()
        {
            AotHelper.EnsureList<Int64?>();
            AotHelper.EnsureDictionary<string, Newtonsoft.Json.Linq.JToken>();
        }

   private void Start()
        {
      var data3 = JsonConvert.DeserializeObject<MyData2>(json3); // we're not running this , do don't care if the string is correct - we just need it to compile and link

            var data4 = JsonConvert.DeserializeObject<MyData3>(json3);  // we're not running this , do don't care if the string is correct - we just need it to compile and link
        }

        private class MyData2
        {
            public List<Int64?> myList;
        }


        private class MyData3
        {
            public IDictionary<string, Newtonsoft.Json.Linq.JToken> myDictionary;
        }

**Comment by mamoonraja** [comment]
Hi, seems like it's related to your comment around https://docs.unity3d.com/Manual/ScriptingRestrictions.html. You can submit a PR if your workaround fixed the issues, and we'll look into it. I have added a `major release` tag so that we will pull it into workstream while we get ready for that.

**Comment by shyamraje1012** [comment]
I am shyam pandule from india. I am developing 3d voice bot by using unity 2019.3.1f7, vuforia , watson 4.6 sdk from gethub. I created 1)  speech to text 2) voice bot. It works fine in unity playmode and windows pc . but when i create android application. android app  does not work. in condo i get error message with this line.  
System.Windows.Forms.dll assembly is referenced by user code, but is not supported on Android platform. Various failures might follow.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Kindly suggest me solution. 

Regards,
shyam pandule
7744084479
