### ISSUE TITLE
[Text-to-Speech-V1] Example does not work well

### ISSUE THREAD

**Issue by Sebastian-Schuchmann** [watson-developer-cloud/unity-sdk#627]
**What I am using:**

- Unitiy 2019.3.5f1
- Watson 4.5.0.
- Example: ExampleTextToSpeechV1
- Editor & Build

**Issue:**
First of all, the Example scene works and I can type in a sentence and I get an Audio file back that I can play.

The problem is that it works very inconsistently. As an example, I am sending the sentence "Please type text here and press enter.". Sometimes I get an audio file of about 104358 bytes back that contains the whole sentence but in at least 1/5 cases I get a file of about 58290 bytes, which misses a big chunk of the sentence.

If I look at the JSON that gets sent, it is the same every time, containing the whole sentence:
 {"text":"Please type text here and press enter.","accept":"audio/wav"}.

This happens with every input, the sentence above is just an example. The interesting thing is that even in way longer sentences when it fails the size of missing bytes is always ~40.000 bytes. This is further confirmed when looking at the individual binary packages that are received: Most of them are either 1764 or 3528 bytes in Size. In the end, though there is a package with the size of ~40.000 bytes (45864 in the example given), which is missing in the cases it fails.

This problem appears with the "audio/wav" format used in the example but as far as I can tell all other formats appear to have the same problem, though byte sizes vary (mp3 and FLAC tested). Again the same for different voices.

This may not be a problem with this library. Is there any chance the Text To Speech service is broken? 

**Steps to reproduce:**
- Open the ExampleTextToSpeechV1 Scene and fill out the necessary fields in the inspector
- Use a sentence of your choice in the input field
- Try sending the same request multiple times
- Wait for it to fail

**Comment by Sebastian-Schuchmann** [comment]
I was just able to reproduce the Error in a completely fresh install of 2018.4.18f (LTS). I am using Windows 10 by the way.

**Comment by mamoonraja** [comment]
@Sebastian-Schuchmann Thanks a lot for opening the issue and providing detailed feedback. I am able to re-create the issue intermittently. I will try to debug it as soon as I can depending on the bandwidth. You can also use the [older example](https://github.com/watson-developer-cloud/unity-sdk/blob/master/Examples/ExampleTextToSpeechV1.cs#L143) if you are fine with not using WebSocket, this might be an issue with websokcet interface, so we need to investigate more.

**Comment by Sebastian-Schuchmann** [comment]
Thanks, I completely missed that the non-ws function is still in there. You are correct now it works without a hitch. Great work!
