### ISSUE TITLE
[Speech-To-Text not working] [RESTConnector.ProcessRequestQueue()] [Credentials.OnRequestIamTokenResponse()][ERROR]

### ISSUE THREAD

**Issue by longnh176040** [watson-developer-cloud/unity-sdk#628]
Hi guys,
Im completely new to this. I did everything exactly the same with the tutorials. But when I hit play, i got these issues and I could not find any solution to fix these. 
![Screenshot (1)](https://user-images.githubusercontent.com/45277447/77146375-7e62f880-6abd-11ea-8086-564b4b509ff4.png)
![Screenshot (2)](https://user-images.githubusercontent.com/45277447/77146377-7f942580-6abd-11ea-9ae1-ee19384d4b69.png)
![Screenshot (3)](https://user-images.githubusercontent.com/45277447/77146378-7f942580-6abd-11ea-96ed-61537c718d36.png)

So please guys, tell me what are these and how to fix them. Thank you so much :<<<

**Comment by mamoonraja** [comment]
@longnh176040 Looks like an issue with the API key, can you confirm if `apikey` and `url` are correct?

**Comment by longnh176040** [comment]
> @longnh176040 Looks like an issue with the API key, can you confirm if `apikey` and `url` are correct?

Yes, I just followed this video and did everything the same https://www.youtube.com/watch?v=xKzSzTvRH68

**Comment by mamoonraja** [comment]
Did you hide the `apikey` in screenshot on purpose, or that's what you have entered in the `apikey` field? If yes, then you need to copy the actual `apikey` instead of hidden characters.

**Comment by longnh176040** [comment]
> Did you hide the `apikey` in screenshot on purpose, or that's what you have entered in the `IAM apikey` field? If yes, then you need to copy the actual `apikey` instead of hidden characters.

No, the api key which i pasted was masked automatically. I did nothing different from the above video.

**Comment by longnh176040** [comment]
and of course it is not hidden on the web :( just masked automatically when i pasted in unity

**Comment by mamoonraja** [comment]
Interestingly, if you copied the `key` from the `Credentials` tab as shown in the video, it should be masked. Anyways, can you try to copy the actual key instead of `masked` one and see if that works?

**Comment by longnh176040** [comment]
> Interestingly, if you copied the `key` from the `Credentials` tab as shown in the video, it should be masked. Anyways, can you try to copy the actual key instead of `masked` one and see if that works?

Thank you so much for you help <3 <3. It works now !!

**Comment by mamoonraja** [comment]
Glad it worked :)
