### ISSUE TITLE
The type or namespace 'Credentials' could not be found [Unity 2019.3.6f1]

### ISSUE THREAD

**Issue by vander-al** [watson-developer-cloud/unity-sdk#629]
Followed this [repository](https://github.com/IBM/Watson-Unity-ARKit), simply putting the SDK and SDK Core into the project and immediately getting several line errors with the same problem in the editor. I'm pretty new to this, I really appreciate it if you guys could help me--- thanks!

Assets\WatsonLogic.cs(75,9): error CS0246: The type or namespace name 'Credentials' could not be found (are you missing a using directive or an assembly reference?)

**Comment by mamoonraja** [comment]
@vander-al Looks like the repo you mentioned is not maintained anymore. They are using older version of the SDK. You can probably use version `3.x` of SDK to make it work with that repo.
