### ISSUE TITLE
[Text To Speech] Received audio is cut off when using WebSockets

### ISSUE THREAD

**Issue by mmoussa** [watson-developer-cloud/unity-sdk#635]
The problem doesn't happen every time, but happens quite often. The code is adapted from the TTS example.
```
void Update()
    {
        if (Input.GetKeyUp(KeyCode.Space))
        {
            SendText(input);
        }

        if (ttsService != null && !ttsService.IsListening && audioStream != null)
        {
            AudioClip clip = WaveFile.ParseWAV("clip", audioStream);
            PlayClip(clip);
            audioStream = null;
            
        }
    }
```

```
void SendText(string text)
    {
        ttsService.StartListening(OnSynthesizeUsingWebsockets);
        ttsService.SynthesizeUsingWebsockets(text);
    }
```

```
void OnSynthesizeUsingWebsockets(byte[] result)
    {
        if (result != null && result.Length > 0)
        {
            audioStream = ConcatenateByteArrays(audioStream, result);

            Debug.Log("Result length: " + result.Length);
            Debug.Log("AudioStream length: " + audioStream.Length);
        }

    }
```

I added some debug messages to WSConnector.cs, and it seems the final chunk of the data is not received sometimes. It is also much larger than the rest of the packets.
Full audio received:
<img src="https://user-images.githubusercontent.com/6563738/81305084-e9f02d80-904b-11ea-877c-d3434ec41ada.png" width="50%"/>
Incomplete audio received:
<img src="https://user-images.githubusercontent.com/6563738/81305252-1ad06280-904c-11ea-828d-ead4e145a1fa.png" width="50%"/>

Regular packet size, as opposed to the huge packet at the end:
<img src="https://user-images.githubusercontent.com/6563738/81305349-3cc9e500-904c-11ea-8b96-290cc225687c.png" width="50%"/><img src="https://user-images.githubusercontent.com/6563738/81307673-ec07bb80-904e-11ea-8dab-6225570292fd.png" width="50%"/>

**Comment by mamoonraja** [comment]
Hi! Thanks for opening the issue, we will try to look into it asap. Meanwhile, you can use the`non-websocket` example here: https://github.com/watson-developer-cloud/unity-sdk/blob/master/Examples/ExampleTextToSpeechV1.cs#L142. If that works for you.

**Comment by mmoussa** [comment]
Thanks, but I need word timing which is only available using websocket.

**Comment by kpprt** [comment]
I'm having the same issue with data being cut off at the end using websocket. Is this still being worked on?
I already have the non-websocket version running, but I'd like to switch to websocket for streaming the audio while it is still being downloaded. I hope to get a faster startup time, especially when the audio gets longer and therefore bigger.

**Comment by mamoonraja** [comment]
@kpprt we have the issue in the backlog, I will look at it next week.

**Comment by kpprt** [comment]
Perfect! Thank you, @mamoonraja !

**Comment by mamoonraja** [comment]
Hi guys, I spent some time on this and looks like WebSocket is closing connection earlier than it should. Can you confirm if changing the wait time in https://github.com/IBM/unity-sdk-core/blob/master/Connection/WSConnector.cs#L482 helps? I was able to make it work but I need to spend more time on it. If it works we can provide the wait time as a feature if it helps. Otherwise, we might need to get in touch with the service team.

Also, which version of SDK are you using?

**Comment by kpprt** [comment]
Hi @mamoonraja, Thanks for looking into it! Unfortunately changing the wait time didn't help. The end of the audio is still cut off occasionally. I tried 100, 200 and 500, but I didn't recognize any differences. The version of the SDK is 4.8.0 and 1.2.1 for the core (currently latest).

**Comment by mamoonraja** [comment]
@kpprt Thanks for confirming, I will look into what's going on at server-side and get back to you, thanks for the patience.

**Comment by mamoonraja** [comment]
Hi guys, we do have an issue opened on the service side for this one, I will provide more info once I have it.

**Comment by creichel** [comment]
@mamoonraja Hi! Are there any news for this issue? I'd like to use this feature as well but I am not sure if it's ready to be used..

**Comment by bomanden** [comment]
I know this is an old issue , has anyone tried the newly release .net standard 2.0 version ? 
https://www.nuget.org/packages/IBM.Watson.TextToSpeech.v1/5.2.0-rc1
https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/websockets-rc/src/IBM.Watson.TextToSpeech.v1/StreamingExample/ServiceExample.cs#L55-L101

**Comment by PanoramaStudio8** [comment]
using System.Collections;
using System.Collections.Generic;
using IBM.Cloud.SDK;
using IBM.Cloud.SDK.Authentication.Iam;
using IBM.Cloud.SDK.Utilities;
using IBM.Watson.SpeechToText.V1;
using IBM.Watson.TextToSpeech.V1;
using UnityEngine;

public class TextToSpeechUsingWebSockets : MonoBehaviour
{
    private string input;
    private Queue<byte[]> audioChunks = new Queue<byte[]>();
    private TextToSpeechService ttsService;

    [Space(10)]
    [Tooltip("The IAM apikey.")]
    [SerializeField]
    private string iamApikey;
    [Tooltip("The service URL (optional). This defaults to \"https://api.us-south.text-to-speech.watson.cloud.ibm.com\"")]
    [SerializeField]
    private string serviceUrl;

    private AudioSource audioSource;
    private bool isPlaying = false;

    private void Start()
    {
        input =
            "Sohail is a skilled Unity programmer, proficient in creating immersive experiences and " +
            "interactive applications. His expertise in game development and Unity engine allows him to bring " +
            "ideas to life with precision and creativity.";

        LogSystem.InstallDefaultReactors();
        Runnable.Run(CreateService());

        // Create an AudioSource component to play the audio
        audioSource = gameObject.AddComponent<AudioSource>();
        audioSource.spatialBlend = 0.0f;
        audioSource.loop = false;
    }

    private IEnumerator CreateService()
    {
        if (string.IsNullOrEmpty(iamApikey))
        {
            throw new IBMException("Please add IAM ApiKey to the Iam Apikey field in the inspector.");
        }

        IamAuthenticator authenticator = new IamAuthenticator(apikey: iamApikey);

        while (!authenticator.CanAuthenticate())
        {
            yield return null;
        }

        ttsService = new TextToSpeechService(authenticator);
        if (!string.IsNullOrEmpty(serviceUrl))
        {
            ttsService.SetServiceUrl(serviceUrl);
        }

        // Start listening for audio chunks
        ttsService.StartListening(OnSynthesizeUsingWebsockets);
    }

    void Update()
    {
        if (Input.GetKeyUp(KeyCode.Space))
        {
            SendText(input);
        }
    }

    void SendText(string text)
    {
        ttsService.SynthesizeUsingWebsockets(text);
    }

    void OnSynthesizeUsingWebsockets(byte[] result)
    {
        if (result != null && result.Length > 0)
        {
            audioChunks.Enqueue(result); // Enqueue the audio chunk
            Debug.Log("Received audio chunk. Length: " + result.Length);

            if (!isPlaying)
            {
                StartCoroutine(PlayAudioChunks());
            }
        }
    }

    IEnumerator PlayAudioChunks()
    {
        isPlaying = true;

        while (audioChunks.Count > 0)
        {
            byte[] chunk = audioChunks.Dequeue();
            PlayAudioChunk(chunk);

            // Wait for the audio clip to finish playing
            yield return new WaitForSeconds(audioSource.clip.length);
        }

        isPlaying = false;
    }

    void PlayAudioChunk(byte[] chunk)
    {
        // Convert byte array to float array
        float[] floatData = new float[chunk.Length / 2];
        for (int i = 0; i < floatData.Length; i++)
        {
            floatData[i] = (float)(short)((chunk[i * 2 + 1] << 8) | chunk[i * 2]) / 32768f;
        }

        // Create an AudioClip with the desired settings
        AudioClip clip = AudioClip.Create("clip", floatData.Length, 1, 24000, false);
        clip.SetData(floatData, 0);

        // Play the AudioClip using the AudioSource component
        audioSource.clip = clip;
        audioSource.Play();
    }
}
