### ISSUE TITLE
@Watson failed to deploy on android with system.window.form.dll error

### ISSUE THREAD

**Issue by shyamraje1012** [watson-developer-cloud/unity-sdk#639]
I am developing 3d voice bot by using unity 2019.3.1f7, vuforia , watson 4.6 sdk from gethub. I created 1)  speech to text 2) voice bot. It works fine in unity playmode and windows pc . but when i create android application. android app  does not work. in condo i get error message with this line.  
System.Windows.Forms.dll assembly is referenced by user code, but is not supported on Android platform. Various failures might follow.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Kindly suggest me solution.

**Comment by mamoonraja** [comment]
@shyamraje1012 Thanks a lot for opening the issue, looks like it's coming from an underlying library, can you provide a full trace of error message
