### ISSUE TITLE
[Speech-To-Text] using keywords will corrput service

### ISSUE THREAD

**Issue by JPM87** [watson-developer-cloud/unity-sdk#641]
Hi I am trying to use the keyword feature to detect words in text.
When using this feature the KeepAlive exited immediately and no voice recognition is available anymore.

- [ ] Steps to reproduce:
  Use the ExampleStreaming Scene and insert following lines of Code after line 112

  `_service.Keywords = new[] { "hallo" };`
  `_service.KeywordsThreshold = .5f;`

- [ ] Expected behavior
  When using keywords the user service should recognize the user voice and translate it into text.

- [ ] Actual behavior
   Voice recognition not working because KeepAlive exited immediately.

   `[SpeechToText.KeepAlive()][DEBUG] KeepAlive exited.`

- [ ] IBM Watson SDK for Unity version
   Latest (v4.6.1)

**Comment by mamoonraja** [comment]
Hi @JPM87 , thanks a lot for opening the issue, I will try to debug it soon and get back to you.

**Comment by mamoonraja** [comment]
@JPM87 can you still reproduce this issue?
