### ISSUE TITLE
watson services work properly in unity editor but not when i compile for android

### ISSUE THREAD

**Issue by dclaresr** [watson-developer-cloud/unity-sdk#642]
Hello,
I am making a virtual reality app and I am currently using the services "conversation", "speech to text" and "text to speech", in the unity editor it works perfectly for me but when I compile for android it does nothing,
When I check the log in the ADB console what I have is this:
[log.txt](https://github.com/watson-developer-cloud/unity-sdk/files/4732160/log.txt)
There are several null exceptions, I tried directly with the examples that come in the SDK and I get the same results
I would appreciate any help or advice with this,

**Comment by mamoonraja** [comment]
Hi @dclaresr , thanks a lot for opening the issue, can you put a debug log here: https://github.com/IBM/unity-sdk-core/blob/master/Utilities/CredentialUtils.cs#L216 or provide me how your env variables are setup? Looks like issue is happening in that method where we try to map credentials. Thanks!

**Comment by dclaresr** [comment]
I am using the examples that come in the SDK, with some modifications for the interactions between them

https://github.com/watson-developer-cloud/unity-sdk/blob/master/Examples/ExampleStreaming.cs
https://github.com/watson-developer-cloud/unity-sdk/blob/master/Examples/ExampleAssistantV2.cs
https://github.com/watson-developer-cloud/unity-sdk/blob/master/Examples/ExampleTextToSpeechV1.cs


[log2.txt](https://github.com/watson-developer-cloud/unity-sdk/files/4739237/log2.txt)

**Comment by dclaresr** [comment]
in the unity Widget

**Comment by mamoonraja** [comment]
Try setting up the env file, it's possible that android is having issues with unity widget. I don't have an android device to test on, so I can not debug it :(
