### ISSUE TITLE
SpeechToText.OnListenMessage() not working

### ISSUE THREAD

**Issue by longnh176040** [watson-developer-cloud/unity-sdk#644]
Hi guys, 

Normally, the speech to text works fine for me. But today, I got a strange problem. Whenever the  StartRecording() function is called, it gave me an ERROR like this "[SpeechToText.OnListenMessage()][ERROR] Error: '>' not supported between instances of 'float' and 'NoneType'. "
I'm using unity 2019.2.12f1, and I haven't fixed any scripts. 
So what is the main problem and how can I fix it ? Please help me !!!

![Screenshot (1)](https://user-images.githubusercontent.com/45277447/85517897-eb8ca980-b629-11ea-9693-78a8e8b80374.png)

**Comment by mamoonraja** [comment]
Hi @longnh176040 , thanks for opening the issue, which version of SDK are you using? and are you using the example code as is, or you have made customizations?

**Comment by longnh176040** [comment]
> Hi @longnh176040 , thanks for opening the issue, which version of SDK are you using? and are you using the example code as is, or you have made customizations?

I'm using unity 2019.2.12f1 and using the example code, haven't changed anything :( . 
I've been searching that error on google for a while, some answers said that error came from web socket or callback or something. But I still can't find out the issue and how to fix it...

**Comment by mamoonraja** [comment]
I meant the SDK version, not the Unity version. Also, which plan of STT service are you using? `lite` or `standard`?

**Comment by longnh176040** [comment]
> I meant the SDK version, not the Unity version. Also, which plan of STT service are you using? `lite` or `standard`?

can u elaborate on that ? what do you mean by "SDK version", of what ?
Im using the lite service. I also thought that my STT is expired, but I tried another one from a different account and still got the same error....

**Comment by longnh176040** [comment]
if you are asking about the unity sdk version, I dunno what it is. I downloaded both unity-sdk and unity-sdk-core from March.
Did you just release a new sdk ? Does it affect to the one that I am using ?

**Comment by DOUCOUREALY** [comment]
@longnh176040 @mamoonraja  please can someone help me . I have the same error.
![Capture](https://user-images.githubusercontent.com/67519171/85930143-c316e080-b8b1-11ea-858f-f74d67a534ad.PNG)

**Comment by mamoonraja** [comment]
@longnh176040 there's not breaking change since March so it should not affect it. My guess was around you running out of `lite` plan initially. But @DOUCOUREALY is also running into the issue, so let me see debug it once and I'll get back to you.

**Comment by dombarnard1** [comment]
I've getting the same issue too. I'm not on the Lite plan.

**Comment by DOUCOUREALY** [comment]
Update the version of sdk To the last. It work for me.

Le lun. 29 juin 2020 à 15:23, dombarnard1 <notifications@github.com> a
écrit :

**Comment by dombarnard1** [comment]
Thanks DOUCOUREALY. I updated the SDK to the latest (unity-sdk-4.7.1) and there are no more issues.

**Comment by DOUCOUREALY** [comment]
What is exatly your error ?

Le lun. 29 juin 2020 à 15:37, dombarnard1 <notifications@github.com> a
écrit :

**Comment by dombarnard1** [comment]
I have no errors now, the update fixed the error I was having (which was the same as you had)

**Comment by DOUCOUREALY** [comment]
Si it's ok now ?

Le lun. 29 juin 2020 à 16:06, dombarnard1 <notifications@github.com> a
écrit :

**Comment by mamoonraja** [comment]
@dombarnard1 @DOUCOUREALY thanks for confirming! @longnh176040 please re-open if you see the issue again.

**Comment by dombarnard1** [comment]
@DOUCOUREALY yes, all is okay now thank you.

**Comment by DOUCOUREALY** [comment]
You are welcome .

Le lun. 29 juin 2020 à 16:15, dombarnard1 <notifications@github.com> a
écrit :
