### ISSUE TITLE
Speech to Text example not working properly.

### ISSUE THREAD

**Issue by jecheverria-dev** [watson-developer-cloud/unity-sdk#645]
Hi there, I am currently trying to run the Speech to Text example provided by the repository. I have completed the following steps:

-Make sure API compatibility is set to NET 4.X
- Download and place both the latest sdk and sdk core
- Create the Speech to Text Service in the IBM Cloud website in order to receive credentials
- Open streaming example and place both the unmasked API Key and Service URL

Despite following these steps, when I press play, the console will show that a microphone has been detected but it will not transcribe anything that I am saying to my device. I will appreciate any advice or tips that may be helpful as I have tried these on multiple versions on Unity of different machines and it wont work.

I also followed what was commented here as a potential solution, but unfortunately it did not work:
https://github.com/watson-developer-cloud/unity-sdk/issues/601

If it helps, my current version of unity is 2019.4.1f1 and I am developing on a Windows 10 machine. Thanks again!
![Annotation 2020-06-24 224125](https://user-images.githubusercontent.com/54328039/85647199-e94b3f00-b66b-11ea-90dc-6184d844153c.png)

**Comment by mamoonraja** [comment]
@jecheverria-dev thanks a lot for opening the issue. Looks like WebSocket is timing out. Are you sure the microphone works fine? seems like audio is not getting picked up and silence has been sent.

**Comment by jecheverria-dev** [comment]
Hi @mamoonraja, I just tried it on a new machine, and it worked perfectly! Thank you again for the help. For others with similar problems, try using either another machine or an external microphone. Thanks again!
