### ISSUE TITLE
Not Working With Vuforia AR Camera

### ISSUE THREAD

**Issue by DelManari** [watson-developer-cloud/unity-sdk#646]
When trying the watson with Vuforia sdk For Unity3d AR apps not working!

**Comment by mamoonraja** [comment]
@DelManari Thanks for opening the issue, what kind of issues are you running into?

**Comment by DelManari** [comment]
> @DelManari Thanks for opening the issue, what kind of issues are you running into?

when am trying to use watson SDK with Vuforia SDK i got errors like 
Namespace '<global namespace>' contains a definition conflicting with alias 'Utility'

**Comment by DelManari** [comment]
![image](https://user-images.githubusercontent.com/32303930/86855113-9f257d00-c0b1-11ea-8bbb-3a8b429b6c2b.png)

**Comment by AhmadIftikhar** [comment]
You need to move this line 
`using IBM.Cloud.SDK.Utilities.Utility;` 
in the Namespace that fixes the issue
