### ISSUE TITLE
[text-to-speech] TTS aborts while speaking probably because of keep alive highhat of STT

### ISSUE THREAD

**Issue by ChrissiOu** [watson-developer-cloud/unity-sdk#648]
Hello!

I combined the ExampleStreaming script and ExampleTextToSpeechV1 script to create an Q&A System. Everything works fine. When TextToSpeech is speaking and Keep Alive play high Hat executes, the speaking aborts. How can I use both services together, without them influencing each other badly?

Hope you can reproduce my issue. Thanks for your help!

**Comment by mamoonraja** [comment]
@ChrissiOu Hi, thanks for opening the issue, We have the TTS WebSocket issue in unity SDK in our backlog. I will take a look at it next week. Thanks a lot for the patience.

**Comment by ChrissiOu** [comment]
@mamoonraja Hi, do you have already made progress with my problem? Have you been able to reproduce it? Thankts for your effort!

**Comment by mamoonraja** [comment]
@ChrissiOu I have made both of them work separately and it works, do you have a snippet of how you are trying to use them together. That will help with debugging.

**Comment by ChrissiOu** [comment]
@mamoonraja the file contains my script for the STT and TTS. The Answermanager finally receives the recognized text and returns an answer to synthesize in line 520. Everything works except when "KeepAlive play high" is executed while TTS service is talking. 
Thanks for helping!
[ExampleSTTWithTTS.txt](https://github.com/watson-developer-cloud/unity-sdk/files/5323308/ExampleSTTWithTTS.txt)
