### ISSUE TITLE
[speech-to-text] WebSockets CSharp DLL conflict

### ISSUE THREAD

**Issue by tomszirtes** [watson-developer-cloud/unity-sdk#651]
### When reporting a bug, please be sure to include the following:

- [ ] Steps to reproduce
- Create Unity Project
- Import Watson Unity SDK
- Import another SDK using websocket-sharp.dll

- [ ] Expected behavior
Would work with other SDK requiring websockets connecting to different services.

- [ ] Actual behavior
Compiled fails with error message:
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name websocket-sharp.dll included or the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: 

- [ ] IBM Watson SDK for Unity version
unity-sdk-core-1.2.1
Unity 2914.4.8f1

Notes:
I've seen other issues opened before and closed on this topic. I'm not sure what the status is because I'm still getting this with the latest version.

I've tried renaming the websocket-sharp.dll to say websocket-sharp2.dll which does fix the issue in the Editor at least, however then I can't compile with IL2CPP to the Android device as that reports

IL2CPP error for type 'IBM.Cloud.SDK.Plugins.WebSocketSharp.WebSocket' in assembly 'E:\Dev2020\BodyswapVRImmerse\Temp\StagingArea\assets\bin\Data\Managed\websocket-sharp.dll'
Additional information: Exception has been thrown by the target of an invocation.

**Comment by mamoonraja** [comment]
We did fix it in the core in the [past](https://github.com/IBM/unity-sdk-core/commit/d9b0bc9b5126069bb38cf8e85f37c1f57a0ff58e), seems like just updating the library path does not help. I am adding a major release label and we will take a look at it in our upcoming major release. Were you able to figure out how to solve it for now?
