### ISSUE TITLE
[Speech to text] Access to path is denied (Mac)

### ISSUE THREAD

**Issue by StavEW** [watson-developer-cloud/unity-sdk#656]
Hi, 
I've been using speech to text and everything works great, except when I compile a build trough Xcode for Mac

This is the error I get:
> UnauthorizedAccessException: Access to the path is denied.
System.IO.Directory.InsecureGetCurrentDirectory () (at <fb001e01371b4adca20013e0ac763896>:0)
System.IO.Directory.GetCurrentDirectory () (at <fb001e01371b4adca20013e0ac763896>:0)
IBM.Cloud.SDK.Utilities.CredentialUtils.GetFilesToCheck () (at <9265dc5ba7cf4f39bf687b99412a42a3>:0)
IBM.Cloud.SDK.Utilities.CredentialUtils.GetFileCredentialsAsMap (System.String serviceName) (at <9265dc5ba7cf4f39bf687b99412a42a3>:0)
IBM.Cloud.SDK.Utilities.CredentialUtils.GetServiceProperties (System.String serviceName) (at <9265dc5ba7cf4f39bf687b99412a42a3>:0)
IBM.Cloud.SDK.BaseService..ctor (IBM.Cloud.SDK.Authentication.Authenticator authenticator, System.String serviceId) (at <9265dc5ba7cf4f39bf687b99412a42a3>:0)
IBM.Watson.SpeechToText.V1.SpeechToTextService..ctor (IBM.Cloud.SDK.Authentication.Authenticator authenticator) (at <f6a460210d76405c80f0166f3c4e4fb1>:0)
Session_Voice+<CreateService>d__14.MoveNext () (at <29a2266d0e4140f48628417a46f6af30>:0)
IBM.Cloud.SDK.Utilities.Runnable+Routine.MoveNext () (at <9265dc5ba7cf4f39bf687b99412a42a3>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ae0d7d57c024472ebc42789a7f4e6d20>:0)
> 

This problem is caused when I use Xcode's sandbox capabilities, because If I compile a build without sandbox, it works fine. I must use the sandbox capabilities to be able to upload the app to the store

Maybe I've missed something?

Using:
SDKCore (1.2.1)
Watson (4.8.0)
Unity (2019.4.10)
Xcode (12.1)

Thanks!

**Comment by mamoonraja** [comment]
@StavEW Thanks a lot for opening the issue. Seems like a permissions issue to me. I am not familiar with how Xcode's sandbox set up permissions, SDK is trying to read credentials from the file. Maybe try providing the credentials in the authenticator instead of via credentials file.

**Comment by StavEW** [comment]
@mamoonraja
Ok, this is a super easy fix!

The background:
In order to submit an app to the Mac's App Store, you must enable sandbox. 
Once enabling it, the app will have limited file access, nothing to do about it.
When trying to enable the speech to text services, the plugin will try getting the service properties via three different ways, "credential file", "environment variables" and "VCAP_SERVICES".
Even if your credentials are in the environment variables, it’ll still try reading from file first, and cause the error 

The fix:
Simple, ignore reading the file. 
In my specific case, i just added and ignore specificly for Mac platform since I'm using this plugin for 4 platforms

Add the next code in the beginning of "GetFileCredentialsAsMap" of CredentialUtils script
`if (Application.platform == RuntimePlatform.OSXPlayer)
    return null;`

also, `using UnityEngine;`

SOLVED
