### ISSUE TITLE
Assistant V2 not working on Magic Leap Build

### ISSUE THREAD

**Issue by alessiograncini** [watson-developer-cloud/unity-sdk#667]
Hello everyone, I did managed to run streaming services on Magic Leap (speech to text) - unfortunately not still able to use the Assistant v2 and the Text To Speech features. It work flawlessly on editor and Z-Iterator but when I build seems like the assistant service does not start at all.

More precisely. I believe I am encountering issues discussed previously here. 
https://github.com/watson-developer-cloud/unity-sdk/issues/566 
here 
https://github.com/watson-developer-cloud/unity-sdk/issues/622 
and also here 
https://forum.unity.com/threads/newtonsoft-json-with-magic-leap.651034/

I am taking advantage of the STT - TTS and Assistant V2 (standard combo). STT works perfect both on editor and headset. Assistant V2 work just on the editor and not when built on device.
I also would like to add that I tested and the STT doesn't work in my build when imported the json-net-for-unity package from unity asset store 
https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347

the only way to have TTS working on device is using this package 
https://github.com/jilleJr/Newtonsoft.Json-for-Unity 
and removing the one equivalent  from the watson sdk folder  

my log from the lab too attached

using 
last watson sdk 
last lumin os
unity 2019.3.15f1
* permission are checked correctly 
* .NET 4 is checked 

![image](https://user-images.githubusercontent.com/10515494/104829680-ea6fd380-582a-11eb-800a-4aa1907a73cd.png)

**Comment by alessiograncini** [comment]
Just wanted to update the request. I managed to make it work and I would like sharing my solution for anyone else in the same spot. 

**Step 01**
Make sure you are using 2019.3.15f1 and magic leap SDK 24.1 / API 8 / All permissions checked / .NET 4 is checked/ Watson v5.0.1/v1.2.1

**Step 02** 
delete the json-net-for-unity that the Watson SDK provides and replace it with this 
https://github.com/jilleJr/Newtonsoft.Json-for-Unity/releases/tag/12.0.301
**don't install the unity package**  download the .zip file move it to the asset folder 

**Step 03** 
in the script **SystemInformation.cs** (from the watson sdk) modify the line at the beginning 
Under the hood - the problem is that the string recognized in the device is a composition of system + version number 
this solution is actually part of one of the issues #622 

`private static string osInfo = null;
        public static string OsInfo
        {
            get
            {
                if (string.IsNullOrEmpty(osInfo))
                {
                    osInfo = SystemInfo.operatingSystem;
                }

                if (SystemInfo.operatingSystem == "Lumin") // Checks if it the Lumin OS and adds the Version after the OS Name
                {
                    osInfo = SystemInfo.operatingSystem + " 0.98.11"; // your version might be different 
                }
                else
                {
                    osInfo = SystemInfo.operatingSystem;
                }

                return osInfo;
            }
        }`

**Step 04**

Hopefully you don't run into any other problem, this worked well for me!

**Comment by alessiograncini** [comment]
. After seeing the following sources online

https://github.com/watson-developer-cloud/unity-sdk/issues/566

https://github.com/watson-developer-cloud/unity-sdk/issues/622

https://forum.unity.com/threads/newtonsoft-json-with-magic-leap.651034/

. The solution have been founded at this link. It is required a script that forces the serialization

(AoT helper)

https://github.com/watson-developer-cloud/unity-sdk/issues/596

**Comment by mediumTaj** [comment]
Glad you figured it out - sorry we don't have a magic leap device to test with.
