### ISSUE TITLE
Configuring a service always defaults to US zone.

### ISSUE THREAD

**Issue by SimonBenAnderson** [watson-developer-cloud/unity-sdk#7]
When installing the Watson Unity-sdk and setting up the available watson services, all the hyperlink shortcuts automatically default to the US South Region. This causes a Retrieve Space Error (BXNUI0515E) to occur, if you are outside of the US.

**Short term solution**: I have added a note to the ReadMe which explains how to fix this if it occurs, by simply altering the region every time a fresh Service page loads.
https://github.com/SimonBenAnderson/unity-sdk/tree/docs#configuring-your-service-credentials

**Comment by mediumTaj** [comment]
The bluemix link in the read me

https://apps.admin.ibmcloud.com/manage/trial/bluemix.html?cm_mmc=WatsonDeveloperCloud-_-LandingSiteGetStarted-_-x-_-CreateAnAccountOnBluemixCLI

Will this be ok to link to from within unity? Can I assume this will redirect to the proper region for the user? Do we want to change any of these tracking tags?
