### ISSUE TITLE
Determine code coverage for Unity SDK

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/unity-sdk#71]
Find code coverage for Unity SDK

Need windows access (parallels)
http://codingdebauchery.blogspot.de/2014/03/code-coverage-for-unityc.html

**Comment by mediumTaj** [comment]
rafah suggested VMWare Fusion. I put a request in  but it was rejected. Apparently I need a MSDN license first.

**Comment by mediumTaj** [comment]
Moved this to next sprint

**Comment by mediumTaj** [comment]
tracking this from dev experience

**Comment by mamoonraja** [comment]
Closing it and adding it as a nice to have for next major release.
