### ISSUE TITLE
Watson NLC Editor Path

### ISSUE THREAD

**Issue by SimonBenAnderson** [watson-developer-cloud/unity-sdk#8]
I'am currently going through the ReadMe, and when trying to perform the Refresh in the NLC Editor, nothing appears. After taking a closer look, it seems that it is looking for the ```*.json``` file in a folder called **Watson** .

```C#
m_ClassifierDirectory = "Watson/Scripts/Editor/Classifiers/";
```
https://github.com/watson-developer-cloud/unity-sdk/blob/develop/Scripts/Utilities/Config.cs#L109

Once the path is renamed to match that of the repo which has been pulled, it works.
```C#
private string m_ClassifierDirectory = "unity-sdk/Scripts/Editor/Classifiers/";
```

Should the repo master folder be renamed to "Watson" or should the path be renamed?  As this isn't mentioned anywhere in the ReadMe, I would suggest one of two options:
1. Correct it by amending the path.
2. Adding into the ReaMme docs that one must move the *.json file into the newly made folder, or automating this process when the plugin initialises and checks to see if the folder structure exists.

I can implement one of the two, but I think it would be good to get some input from your side before going ahead with it, As I do not know what you have planned for the greater scheme of the plugin.

**Comment by mediumTaj** [comment]
I think the repo master folder should be renamed "Watson". "unity-sdk" as a directory name doesn't mean much when imported into the unity ide.

**Comment by germanattanasio** [comment]
Paths should be relative so that you don't have a dependency on the name of the folder.
